// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const OIDCAuthType = {
    DefaultAuthType: "DEFAULT_AUTH_TYPE",
    UrlEncodedBody: "URL_ENCODED_BODY",
    BasicAuth: "BASIC_AUTH",
} as const;

export type OIDCAuthType = (typeof OIDCAuthType)[keyof typeof OIDCAuthType];

export const OIDCCookieConfigSameSite = {
    Disabled: "DISABLED",
    Strict: "STRICT",
    Lax: "LAX",
    None: "NONE",
} as const;

export type OIDCCookieConfigSameSite = (typeof OIDCCookieConfigSameSite)[keyof typeof OIDCCookieConfigSameSite];

export const OIDCGrantType = {
    DefaultGrantType: "DEFAULT_GRANT_TYPE",
    AuthorizationCode: "AUTHORIZATION_CODE",
} as const;

export type OIDCGrantType = (typeof OIDCGrantType)[keyof typeof OIDCGrantType];

export const TLSMode = {
    Disabled: "DISABLED",
    Simple: "SIMPLE",
    Mutual: "MUTUAL",
    IstioMutual: "ISTIO_MUTUAL",
} as const;

export type TLSMode = (typeof TLSMode)[keyof typeof TLSMode];
