// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const Permission = {
    Invalid: "INVALID",
    Read: "READ",
    Write: "WRITE",
    Create: "CREATE",
    Delete: "DELETE",
    SetPolicy: "SET_POLICY",
    GetPolicy: "GET_POLICY",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];
