// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const ConfigMode = {
    Bridged: "BRIDGED",
    Direct: "DIRECT",
} as const;

export type ConfigMode = (typeof ConfigMode)[keyof typeof ConfigMode];

export const ControlPlaneMode = {
    Unset: "UNSET",
    Control: "CONTROL",
    Observe: "OBSERVE",
} as const;

export type ControlPlaneMode = (typeof ControlPlaneMode)[keyof typeof ControlPlaneMode];

export const FailoverSettingsTopologyChoice = {
    None: "NONE",
    Cluster: "CLUSTER",
    Locality: "LOCALITY",
} as const;

export type FailoverSettingsTopologyChoice = (typeof FailoverSettingsTopologyChoice)[keyof typeof FailoverSettingsTopologyChoice];

export const IdentityMatch = {
    Unknown: "UNKNOWN",
    PeerCertificate: "PEER_CERTIFICATE",
    Permissive: "PERMISSIVE",
    SourceIdentity: "SOURCE_IDENTITY",
} as const;

export type IdentityMatch = (typeof IdentityMatch)[keyof typeof IdentityMatch];

export const PropagationStrategy = {
    Replace: "REPLACE",
    Stricter: "STRICTER",
} as const;

export type PropagationStrategy = (typeof PropagationStrategy)[keyof typeof PropagationStrategy];

export const WorkloadMode = {
    Undefined: "UNDEFINED",
    Client: "CLIENT",
    Server: "SERVER",
    ClientAndServer: "CLIENT_AND_SERVER",
} as const;

export type WorkloadMode = (typeof WorkloadMode)[keyof typeof WorkloadMode];
