// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class ExtensionWasmExtension extends pulumi.CustomResource {
    /**
     * Get an existing ExtensionWasmExtension resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ExtensionWasmExtensionState, opts?: pulumi.CustomResourceOptions): ExtensionWasmExtension {
        return new ExtensionWasmExtension(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:extension/extensionWasmExtension:ExtensionWasmExtension';

    /**
     * Returns true if the given object is an instance of ExtensionWasmExtension.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ExtensionWasmExtension {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ExtensionWasmExtension.__pulumiType;
    }

    /**
     * List of fqns where this extension is allowed to run. If it is empty, the extension can be used across the entire organization. Currently only Tenant resources are considered.
     */
    declare public readonly allowedIns: pulumi.Output<string[]>;
    /**
     * Configuration parameters sent to the WASM plugin execution The configuration can be overwritten when instantiating the extensions in IngressGateways or Security groups. The config is serialized using proto3 JSON marshaling and passed to proxyOnConfigure when the host environment starts the plugin.
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * A description of the extension.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the extension.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Deprecated. Use the `url` field instead. Repository and tag of the OCI image containing the WASM extension.
     */
    declare public readonly image: pulumi.Output<string>;
    /**
     * The pull behaviour to be applied when fetching Wasm module by either OCI image or http/https. Only relevant when referencing Wasm module without any digest, including the digest in OCI image URL or sha256 field in `vmConfig`. Defaults to IfNotPresent, except when an OCI image is referenced in the `url` and the `latest` tag is used, in which case `Always` is the default, mirroring K8s behaviour. Possible values: UNSPECIFIED_POLICY, IfNotPresent, Always.
     */
    declare public readonly imagePullPolicy: pulumi.Output<string>;
    /**
     * Credentials to use for OCI image pulling. Name of a K8s Secret that contains a docker pull secret which is to be used to authenticate against the registry when pulling the image. If TSB is configured to use the WASM download proxy, this secret must exist in the `istio-system` namespace of each cluster that has applications that use the extension. If the download proxy is disabled, the secret must exist in each application namespace that is using the extension.
     */
    declare public readonly imagePullSecret: pulumi.Output<string>;
    /**
     * Specifies the criteria to determine which traffic is passed to WasmExtension. These settings are propagated to all WASMExtension Attachments. It can be overridden at attachment points. If a traffic satisfies the TrafficSelector, the traffic passes to the WasmExtension.
     */
    declare public readonly match: pulumi.Output<outputs.extension.ExtensionWasmExtensionMatch | undefined>;
    /**
     * Short name of the WasmExtension resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the WasmExtension resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * The phase in the filter chain where the extension will be injected. https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/#PluginPhase. Possible values: UNSPECIFIED_PHASE, AUTHN, AUTHZ, STATS.
     */
    declare public readonly phase: pulumi.Output<string>;
    /**
     * Determines the ordering of WasmExtensions in the same phase. When multiple WasmExtensions are applied to the same workload in the same phase, they will be applied by priority, in descending order. If no priority is assigned it will use the default 0 value. In case of several extensions having the same priority in the same phase, the fqn will be used to sort them.
     */
    declare public readonly priority: pulumi.Output<number>;
    /**
     * Source to find the code for the WASM extension
     */
    declare public readonly source: pulumi.Output<string>;
    /**
     * URL of a Wasm module or OCI container. If no scheme is present, defaults to oci://, referencing an OCI image. Other valid schemes are file:// for referencing .wasm module files present locally within the proxy container, and http[s]:// for .wasm module files hosted remotely.
     */
    declare public readonly url: pulumi.Output<string>;
    /**
     * VM Configuration sent to the WASM plugin execution
     */
    declare public readonly vmConfig: pulumi.Output<outputs.extension.ExtensionWasmExtensionVmConfig | undefined>;

    /**
     * Create a ExtensionWasmExtension resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ExtensionWasmExtensionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ExtensionWasmExtensionArgs | ExtensionWasmExtensionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ExtensionWasmExtensionState | undefined;
            resourceInputs["allowedIns"] = state?.allowedIns;
            resourceInputs["config"] = state?.config;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["image"] = state?.image;
            resourceInputs["imagePullPolicy"] = state?.imagePullPolicy;
            resourceInputs["imagePullSecret"] = state?.imagePullSecret;
            resourceInputs["match"] = state?.match;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["phase"] = state?.phase;
            resourceInputs["priority"] = state?.priority;
            resourceInputs["source"] = state?.source;
            resourceInputs["url"] = state?.url;
            resourceInputs["vmConfig"] = state?.vmConfig;
        } else {
            const args = argsOrState as ExtensionWasmExtensionArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            if (args?.url === undefined && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["allowedIns"] = args?.allowedIns;
            resourceInputs["config"] = args?.config;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["image"] = args?.image;
            resourceInputs["imagePullPolicy"] = args?.imagePullPolicy;
            resourceInputs["imagePullSecret"] = args?.imagePullSecret;
            resourceInputs["match"] = args?.match;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["phase"] = args?.phase;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["source"] = args?.source;
            resourceInputs["url"] = args?.url;
            resourceInputs["vmConfig"] = args?.vmConfig;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ExtensionWasmExtension.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ExtensionWasmExtension resources.
 */
export interface ExtensionWasmExtensionState {
    /**
     * List of fqns where this extension is allowed to run. If it is empty, the extension can be used across the entire organization. Currently only Tenant resources are considered.
     */
    allowedIns?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Configuration parameters sent to the WASM plugin execution The configuration can be overwritten when instantiating the extensions in IngressGateways or Security groups. The config is serialized using proto3 JSON marshaling and passed to proxyOnConfigure when the host environment starts the plugin.
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * A description of the extension.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the extension.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Deprecated. Use the `url` field instead. Repository and tag of the OCI image containing the WASM extension.
     */
    image?: pulumi.Input<string | undefined>;
    /**
     * The pull behaviour to be applied when fetching Wasm module by either OCI image or http/https. Only relevant when referencing Wasm module without any digest, including the digest in OCI image URL or sha256 field in `vmConfig`. Defaults to IfNotPresent, except when an OCI image is referenced in the `url` and the `latest` tag is used, in which case `Always` is the default, mirroring K8s behaviour. Possible values: UNSPECIFIED_POLICY, IfNotPresent, Always.
     */
    imagePullPolicy?: pulumi.Input<string | undefined>;
    /**
     * Credentials to use for OCI image pulling. Name of a K8s Secret that contains a docker pull secret which is to be used to authenticate against the registry when pulling the image. If TSB is configured to use the WASM download proxy, this secret must exist in the `istio-system` namespace of each cluster that has applications that use the extension. If the download proxy is disabled, the secret must exist in each application namespace that is using the extension.
     */
    imagePullSecret?: pulumi.Input<string | undefined>;
    /**
     * Specifies the criteria to determine which traffic is passed to WasmExtension. These settings are propagated to all WASMExtension Attachments. It can be overridden at attachment points. If a traffic satisfies the TrafficSelector, the traffic passes to the WasmExtension.
     */
    match?: pulumi.Input<inputs.extension.ExtensionWasmExtensionMatch | undefined>;
    /**
     * Short name of the WasmExtension resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the WasmExtension resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * The phase in the filter chain where the extension will be injected. https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/#PluginPhase. Possible values: UNSPECIFIED_PHASE, AUTHN, AUTHZ, STATS.
     */
    phase?: pulumi.Input<string | undefined>;
    /**
     * Determines the ordering of WasmExtensions in the same phase. When multiple WasmExtensions are applied to the same workload in the same phase, they will be applied by priority, in descending order. If no priority is assigned it will use the default 0 value. In case of several extensions having the same priority in the same phase, the fqn will be used to sort them.
     */
    priority?: pulumi.Input<number | undefined>;
    /**
     * Source to find the code for the WASM extension
     */
    source?: pulumi.Input<string | undefined>;
    /**
     * URL of a Wasm module or OCI container. If no scheme is present, defaults to oci://, referencing an OCI image. Other valid schemes are file:// for referencing .wasm module files present locally within the proxy container, and http[s]:// for .wasm module files hosted remotely.
     */
    url?: pulumi.Input<string | undefined>;
    /**
     * VM Configuration sent to the WASM plugin execution
     */
    vmConfig?: pulumi.Input<inputs.extension.ExtensionWasmExtensionVmConfig | undefined>;
}

/**
 * The set of arguments for constructing a ExtensionWasmExtension resource.
 */
export interface ExtensionWasmExtensionArgs {
    /**
     * List of fqns where this extension is allowed to run. If it is empty, the extension can be used across the entire organization. Currently only Tenant resources are considered.
     */
    allowedIns?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Configuration parameters sent to the WASM plugin execution The configuration can be overwritten when instantiating the extensions in IngressGateways or Security groups. The config is serialized using proto3 JSON marshaling and passed to proxyOnConfigure when the host environment starts the plugin.
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * A description of the extension.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the extension.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Deprecated. Use the `url` field instead. Repository and tag of the OCI image containing the WASM extension.
     */
    image?: pulumi.Input<string | undefined>;
    /**
     * The pull behaviour to be applied when fetching Wasm module by either OCI image or http/https. Only relevant when referencing Wasm module without any digest, including the digest in OCI image URL or sha256 field in `vmConfig`. Defaults to IfNotPresent, except when an OCI image is referenced in the `url` and the `latest` tag is used, in which case `Always` is the default, mirroring K8s behaviour. Possible values: UNSPECIFIED_POLICY, IfNotPresent, Always.
     */
    imagePullPolicy?: pulumi.Input<string | undefined>;
    /**
     * Credentials to use for OCI image pulling. Name of a K8s Secret that contains a docker pull secret which is to be used to authenticate against the registry when pulling the image. If TSB is configured to use the WASM download proxy, this secret must exist in the `istio-system` namespace of each cluster that has applications that use the extension. If the download proxy is disabled, the secret must exist in each application namespace that is using the extension.
     */
    imagePullSecret?: pulumi.Input<string | undefined>;
    /**
     * Specifies the criteria to determine which traffic is passed to WasmExtension. These settings are propagated to all WASMExtension Attachments. It can be overridden at attachment points. If a traffic satisfies the TrafficSelector, the traffic passes to the WasmExtension.
     */
    match?: pulumi.Input<inputs.extension.ExtensionWasmExtensionMatch | undefined>;
    /**
     * Short name of the WasmExtension resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the WasmExtension resource.
     */
    parent: pulumi.Input<string>;
    /**
     * The phase in the filter chain where the extension will be injected. https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/#PluginPhase. Possible values: UNSPECIFIED_PHASE, AUTHN, AUTHZ, STATS.
     */
    phase?: pulumi.Input<string | undefined>;
    /**
     * Determines the ordering of WasmExtensions in the same phase. When multiple WasmExtensions are applied to the same workload in the same phase, they will be applied by priority, in descending order. If no priority is assigned it will use the default 0 value. In case of several extensions having the same priority in the same phase, the fqn will be used to sort them.
     */
    priority?: pulumi.Input<number | undefined>;
    /**
     * Source to find the code for the WASM extension
     */
    source?: pulumi.Input<string | undefined>;
    /**
     * URL of a Wasm module or OCI container. If no scheme is present, defaults to oci://, referencing an OCI image. Other valid schemes are file:// for referencing .wasm module files present locally within the proxy container, and http[s]:// for .wasm module files hosted remotely.
     */
    url: pulumi.Input<string>;
    /**
     * VM Configuration sent to the WASM plugin execution
     */
    vmConfig?: pulumi.Input<inputs.extension.ExtensionWasmExtensionVmConfig | undefined>;
}
