// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { ExtensionWasmExtensionArgs, ExtensionWasmExtensionState } from "./extensionWasmExtension";
export type ExtensionWasmExtension = import("./extensionWasmExtension").ExtensionWasmExtension;
export const ExtensionWasmExtension: typeof import("./extensionWasmExtension").ExtensionWasmExtension = null as any;
utilities.lazyLoad(exports, ["ExtensionWasmExtension"], () => require("./extensionWasmExtension"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tsb:extension/extensionWasmExtension:ExtensionWasmExtension":
                return new ExtensionWasmExtension(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tsb", "extension/extensionWasmExtension", _module)
