// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const AuthenticationSettingsAuthenticationMode = {
    Unset: "UNSET",
    Optional: "OPTIONAL",
    Required: "REQUIRED",
} as const;

export type AuthenticationSettingsAuthenticationMode = (typeof AuthenticationSettingsAuthenticationMode)[keyof typeof AuthenticationSettingsAuthenticationMode];

export const FailoverSettingsTopologyChoice = {
    None: "NONE",
    Cluster: "CLUSTER",
    Locality: "LOCALITY",
} as const;

export type FailoverSettingsTopologyChoice = (typeof FailoverSettingsTopologyChoice)[keyof typeof FailoverSettingsTopologyChoice];

export const LoadBalancerSettingsSimpleLB = {
    Unspecified: "UNSPECIFIED",
    Random: "RANDOM",
    Passthrough: "PASSTHROUGH",
    RoundRobin: "ROUND_ROBIN",
    LeastRequest: "LEAST_REQUEST",
} as const;

export type LoadBalancerSettingsSimpleLB = (typeof LoadBalancerSettingsSimpleLB)[keyof typeof LoadBalancerSettingsSimpleLB];

export const ProxyType = {
    Any: "ANY",
    Sidecar: "SIDECAR",
    Gateway: "GATEWAY",
} as const;

export type ProxyType = (typeof ProxyType)[keyof typeof ProxyType];

export const RateLimitSettingsRateLimitValueUnit = {
    Unknown: "UNKNOWN",
    Second: "SECOND",
    Minute: "MINUTE",
    Hour: "HOUR",
    Day: "DAY",
} as const;

export type RateLimitSettingsRateLimitValueUnit = (typeof RateLimitSettingsRateLimitValueUnit)[keyof typeof RateLimitSettingsRateLimitValueUnit];

export const ReachabilitySettingsMode = {
    Unset: "UNSET",
    Namespace: "NAMESPACE",
    Group: "GROUP",
    Workspace: "WORKSPACE",
    Cluster: "CLUSTER",
    Custom: "CUSTOM",
} as const;

export type ReachabilitySettingsMode = (typeof ReachabilitySettingsMode)[keyof typeof ReachabilitySettingsMode];

export const TLSMode = {
    Disabled: "DISABLED",
    Simple: "SIMPLE",
    Mutual: "MUTUAL",
} as const;

export type TLSMode = (typeof TLSMode)[keyof typeof TLSMode];

export const UpstreamResilienceSettingsSensitivity = {
    Unset: "UNSET",
    Low: "LOW",
    Medium: "MEDIUM",
    High: "HIGH",
    Custom: "CUSTOM",
} as const;

export type UpstreamResilienceSettingsSensitivity = (typeof UpstreamResilienceSettingsSensitivity)[keyof typeof UpstreamResilienceSettingsSensitivity];
