// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const AuthorizationSettingsMode = {
    Unset: "UNSET",
    Namespace: "NAMESPACE",
    Group: "GROUP",
    Workspace: "WORKSPACE",
    Cluster: "CLUSTER",
    Disabled: "DISABLED",
    Custom: "CUSTOM",
    Rules: "RULES",
} as const;

export type AuthorizationSettingsMode = (typeof AuthorizationSettingsMode)[keyof typeof AuthorizationSettingsMode];

export const SecuritySettingAuthenticationMode = {
    Unset: "UNSET",
    Optional: "OPTIONAL",
    Required: "REQUIRED",
} as const;

export type SecuritySettingAuthenticationMode = (typeof SecuritySettingAuthenticationMode)[keyof typeof SecuritySettingAuthenticationMode];
