// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class RbacRole extends pulumi.CustomResource {
    /**
     * Get an existing RbacRole resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RbacRoleState, opts?: pulumi.CustomResourceOptions): RbacRole {
        return new RbacRole(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:rbac/rbacRole:RbacRole';

    /**
     * Returns true if the given object is an instance of RbacRole.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RbacRole {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RbacRole.__pulumiType;
    }

    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Short name of the Role resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the Role resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * A set of rules that define the permissions associated with each API group.
     */
    declare public readonly rules: pulumi.Output<outputs.rbac.RbacRoleRule[] | undefined>;

    /**
     * Create a RbacRole resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RbacRoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RbacRoleArgs | RbacRoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RbacRoleState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["rules"] = state?.rules;
        } else {
            const args = argsOrState as RbacRoleArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["rules"] = args?.rules;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RbacRole.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RbacRole resources.
 */
export interface RbacRoleState {
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the Role resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the Role resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * A set of rules that define the permissions associated with each API group.
     */
    rules?: pulumi.Input<pulumi.Input<inputs.rbac.RbacRoleRule>[] | undefined>;
}

/**
 * The set of arguments for constructing a RbacRole resource.
 */
export interface RbacRoleArgs {
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the Role resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the Role resource.
     */
    parent: pulumi.Input<string>;
    /**
     * A set of rules that define the permissions associated with each API group.
     */
    rules?: pulumi.Input<pulumi.Input<inputs.rbac.RbacRoleRule>[] | undefined>;
}
