// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const AuthorizationSettingsMode = {
    Unset: "UNSET",
    Namespace: "NAMESPACE",
    Group: "GROUP",
    Workspace: "WORKSPACE",
    Cluster: "CLUSTER",
    ServiceAccount: "SERVICE_ACCOUNT",
} as const;

export type AuthorizationSettingsMode = (typeof AuthorizationSettingsMode)[keyof typeof AuthorizationSettingsMode];

export const GatewaySpecType = {
    Unified: "UNIFIED",
    Ingress: "INGRESS",
    Egress: "EGRESS",
    Eastwest: "EASTWEST",
} as const;

export type GatewaySpecType = (typeof GatewaySpecType)[keyof typeof GatewaySpecType];

export const RateLimitSettingsRateLimitValueUnit = {
    Unknown: "UNKNOWN",
    Second: "SECOND",
    Minute: "MINUTE",
    Hour: "HOUR",
    Day: "DAY",
} as const;

export type RateLimitSettingsRateLimitValueUnit = (typeof RateLimitSettingsRateLimitValueUnit)[keyof typeof RateLimitSettingsRateLimitValueUnit];

export const ServerTLSSettingsTLSMode = {
    Disabled: "DISABLED",
    Simple: "SIMPLE",
    Mutual: "MUTUAL",
    OptionalMutual: "OPTIONAL_MUTUAL",
} as const;

export type ServerTLSSettingsTLSMode = (typeof ServerTLSSettingsTLSMode)[keyof typeof ServerTLSSettingsTLSMode];

export const TLSProtocol = {
    TlsAuto: "TLS_AUTO",
    Tlsv10: "TLSV1_0",
    Tlsv11: "TLSV1_1",
    Tlsv12: "TLSV1_2",
    Tlsv13: "TLSV1_3",
} as const;

export type TLSProtocol = (typeof TLSProtocol)[keyof typeof TLSProtocol];

export const TrafficMode = {
    Auto: "AUTO",
    Ingress: "INGRESS",
    Egress: "EGRESS",
    Transit: "TRANSIT",
} as const;

export type TrafficMode = (typeof TrafficMode)[keyof typeof TrafficMode];
