// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const GatewaySpecType = {
    Unified: "UNIFIED",
    Ingress: "INGRESS",
    Egress: "EGRESS",
    Eastwest: "EASTWEST",
} as const;

export type GatewaySpecType = (typeof GatewaySpecType)[keyof typeof GatewaySpecType];
