// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const ElasticSearchSettingsProtocol = {
    Https: "https",
    Http: "http",
} as const;

export type ElasticSearchSettingsProtocol = (typeof ElasticSearchSettingsProtocol)[keyof typeof ElasticSearchSettingsProtocol];

export const Route53SettingsFilterSettingsAWSZoneType = {
    None: "NONE",
    Public: "PUBLIC",
    Private: "PRIVATE",
} as const;

export type Route53SettingsFilterSettingsAWSZoneType = (typeof Route53SettingsFilterSettingsAWSZoneType)[keyof typeof Route53SettingsFilterSettingsAWSZoneType];

export const Route53SettingsPolicy = {
    Sync: "SYNC",
    UpsertOnly: "UPSERT_ONLY",
    CreateOnly: "CREATE_ONLY",
} as const;

export type Route53SettingsPolicy = (typeof Route53SettingsPolicy)[keyof typeof Route53SettingsPolicy];

export const XCPCentralAuthMode = {
    Unknown: "UNKNOWN",
    MutualTls: "MUTUAL_TLS",
    Jwt: "JWT",
} as const;

export type XCPCentralAuthMode = (typeof XCPCentralAuthMode)[keyof typeof XCPCentralAuthMode];
