// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class IstiointernalGroup extends pulumi.CustomResource {
    /**
     * Get an existing IstiointernalGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IstiointernalGroupState, opts?: pulumi.CustomResourceOptions): IstiointernalGroup {
        return new IstiointernalGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:istiointernal/istiointernalGroup:IstiointernalGroup';

    /**
     * Returns true if the given object is an instance of IstiointernalGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IstiointernalGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IstiointernalGroup.__pulumiType;
    }

    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.istiointernal.IstiointernalGroupConfigGenerationMetadata | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    declare public readonly deletionProtectionEnabled: pulumi.Output<boolean>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Short name of the Group resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Set of namespaces owned exclusively by this group. Use `*&#47;*` to claim all cluster resources under the workspace.
     */
    declare public readonly namespaceSelector: pulumi.Output<outputs.istiointernal.IstiointernalGroupNamespaceSelector>;
    /**
     * The parent id for the Group resource.
     */
    declare public readonly parent: pulumi.Output<string>;

    /**
     * Create a IstiointernalGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IstiointernalGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IstiointernalGroupArgs | IstiointernalGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IstiointernalGroupState | undefined;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["deletionProtectionEnabled"] = state?.deletionProtectionEnabled;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["name"] = state?.name;
            resourceInputs["namespaceSelector"] = state?.namespaceSelector;
            resourceInputs["parent"] = state?.parent;
        } else {
            const args = argsOrState as IstiointernalGroupArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.namespaceSelector === undefined && !opts.urn) {
                throw new Error("Missing required property 'namespaceSelector'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["deletionProtectionEnabled"] = args?.deletionProtectionEnabled;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespaceSelector"] = args?.namespaceSelector;
            resourceInputs["parent"] = args?.parent;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IstiointernalGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IstiointernalGroup resources.
 */
export interface IstiointernalGroupState {
    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.istiointernal.IstiointernalGroupConfigGenerationMetadata | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the Group resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Set of namespaces owned exclusively by this group. Use `*&#47;*` to claim all cluster resources under the workspace.
     */
    namespaceSelector?: pulumi.Input<inputs.istiointernal.IstiointernalGroupNamespaceSelector | undefined>;
    /**
     * The parent id for the Group resource.
     */
    parent?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IstiointernalGroup resource.
 */
export interface IstiointernalGroupArgs {
    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.istiointernal.IstiointernalGroupConfigGenerationMetadata | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the Group resource.
     */
    name: pulumi.Input<string>;
    /**
     * Set of namespaces owned exclusively by this group. Use `*&#47;*` to claim all cluster resources under the workspace.
     */
    namespaceSelector: pulumi.Input<inputs.istiointernal.IstiointernalGroupNamespaceSelector>;
    /**
     * The parent id for the Group resource.
     */
    parent: pulumi.Input<string>;
}
