// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { IstioSecurityAuthorizationPolicyArgs, IstioSecurityAuthorizationPolicyState } from "./istioSecurityAuthorizationPolicy";
export type IstioSecurityAuthorizationPolicy = import("./istioSecurityAuthorizationPolicy").IstioSecurityAuthorizationPolicy;
export const IstioSecurityAuthorizationPolicy: typeof import("./istioSecurityAuthorizationPolicy").IstioSecurityAuthorizationPolicy = null as any;
utilities.lazyLoad(exports, ["IstioSecurityAuthorizationPolicy"], () => require("./istioSecurityAuthorizationPolicy"));

export { IstioSecurityPeerAuthenticationArgs, IstioSecurityPeerAuthenticationState } from "./istioSecurityPeerAuthentication";
export type IstioSecurityPeerAuthentication = import("./istioSecurityPeerAuthentication").IstioSecurityPeerAuthentication;
export const IstioSecurityPeerAuthentication: typeof import("./istioSecurityPeerAuthentication").IstioSecurityPeerAuthentication = null as any;
utilities.lazyLoad(exports, ["IstioSecurityPeerAuthentication"], () => require("./istioSecurityPeerAuthentication"));

export { IstioSecurityRequestAuthenticationArgs, IstioSecurityRequestAuthenticationState } from "./istioSecurityRequestAuthentication";
export type IstioSecurityRequestAuthentication = import("./istioSecurityRequestAuthentication").IstioSecurityRequestAuthentication;
export const IstioSecurityRequestAuthentication: typeof import("./istioSecurityRequestAuthentication").IstioSecurityRequestAuthentication = null as any;
utilities.lazyLoad(exports, ["IstioSecurityRequestAuthentication"], () => require("./istioSecurityRequestAuthentication"));

export { SecurityGroupArgs, SecurityGroupState } from "./securityGroup";
export type SecurityGroup = import("./securityGroup").SecurityGroup;
export const SecurityGroup: typeof import("./securityGroup").SecurityGroup = null as any;
utilities.lazyLoad(exports, ["SecurityGroup"], () => require("./securityGroup"));

export { SecuritySecuritySettingArgs, SecuritySecuritySettingState } from "./securitySecuritySetting";
export type SecuritySecuritySetting = import("./securitySecuritySetting").SecuritySecuritySetting;
export const SecuritySecuritySetting: typeof import("./securitySecuritySetting").SecuritySecuritySetting = null as any;
utilities.lazyLoad(exports, ["SecuritySecuritySetting"], () => require("./securitySecuritySetting"));

export { SecurityServiceSecuritySettingArgs, SecurityServiceSecuritySettingState } from "./securityServiceSecuritySetting";
export type SecurityServiceSecuritySetting = import("./securityServiceSecuritySetting").SecurityServiceSecuritySetting;
export const SecurityServiceSecuritySetting: typeof import("./securityServiceSecuritySetting").SecurityServiceSecuritySetting = null as any;
utilities.lazyLoad(exports, ["SecurityServiceSecuritySetting"], () => require("./securityServiceSecuritySetting"));


// Export enums:
export * from "../types/enums/security";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tsb:security/istioSecurityAuthorizationPolicy:IstioSecurityAuthorizationPolicy":
                return new IstioSecurityAuthorizationPolicy(name, <any>undefined, { urn })
            case "tsb:security/istioSecurityPeerAuthentication:IstioSecurityPeerAuthentication":
                return new IstioSecurityPeerAuthentication(name, <any>undefined, { urn })
            case "tsb:security/istioSecurityRequestAuthentication:IstioSecurityRequestAuthentication":
                return new IstioSecurityRequestAuthentication(name, <any>undefined, { urn })
            case "tsb:security/securityGroup:SecurityGroup":
                return new SecurityGroup(name, <any>undefined, { urn })
            case "tsb:security/securitySecuritySetting:SecuritySecuritySetting":
                return new SecuritySecuritySetting(name, <any>undefined, { urn })
            case "tsb:security/securityServiceSecuritySetting:SecurityServiceSecuritySetting":
                return new SecurityServiceSecuritySetting(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tsb", "security/istioSecurityAuthorizationPolicy", _module)
pulumi.runtime.registerResourceModule("tsb", "security/istioSecurityPeerAuthentication", _module)
pulumi.runtime.registerResourceModule("tsb", "security/istioSecurityRequestAuthentication", _module)
pulumi.runtime.registerResourceModule("tsb", "security/securityGroup", _module)
pulumi.runtime.registerResourceModule("tsb", "security/securitySecuritySetting", _module)
pulumi.runtime.registerResourceModule("tsb", "security/securityServiceSecuritySetting", _module)
