// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class SecurityServiceSecuritySetting extends pulumi.CustomResource {
    /**
     * Get an existing SecurityServiceSecuritySetting resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecurityServiceSecuritySettingState, opts?: pulumi.CustomResourceOptions): SecurityServiceSecuritySetting {
        return new SecurityServiceSecuritySetting(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:security/securityServiceSecuritySetting:SecurityServiceSecuritySetting';

    /**
     * Returns true if the given object is an instance of SecurityServiceSecuritySetting.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecurityServiceSecuritySetting {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecurityServiceSecuritySetting.__pulumiType;
    }

    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.security.SecurityServiceSecuritySettingConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Short name of the ServiceSecuritySetting resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the ServiceSecuritySetting resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * The service on which the configuration is being applied. Must be in namespace/FQDN format.
     */
    declare public readonly service: pulumi.Output<string>;
    /**
     * Security settings to apply to this service.
     */
    declare public readonly settings: pulumi.Output<outputs.security.SecurityServiceSecuritySettingSettings | undefined>;
    /**
     * Subset specific settings that will replace the service wide settings for the specified service subsets.
     */
    declare public readonly subsets: pulumi.Output<outputs.security.SecurityServiceSecuritySettingSubset[] | undefined>;

    /**
     * Create a SecurityServiceSecuritySetting resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecurityServiceSecuritySettingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecurityServiceSecuritySettingArgs | SecurityServiceSecuritySettingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecurityServiceSecuritySettingState | undefined;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["service"] = state?.service;
            resourceInputs["settings"] = state?.settings;
            resourceInputs["subsets"] = state?.subsets;
        } else {
            const args = argsOrState as SecurityServiceSecuritySettingArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            if (args?.service === undefined && !opts.urn) {
                throw new Error("Missing required property 'service'");
            }
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["service"] = args?.service;
            resourceInputs["settings"] = args?.settings;
            resourceInputs["subsets"] = args?.subsets;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecurityServiceSecuritySetting.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecurityServiceSecuritySetting resources.
 */
export interface SecurityServiceSecuritySettingState {
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.security.SecurityServiceSecuritySettingConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the ServiceSecuritySetting resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the ServiceSecuritySetting resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * The service on which the configuration is being applied. Must be in namespace/FQDN format.
     */
    service?: pulumi.Input<string | undefined>;
    /**
     * Security settings to apply to this service.
     */
    settings?: pulumi.Input<inputs.security.SecurityServiceSecuritySettingSettings | undefined>;
    /**
     * Subset specific settings that will replace the service wide settings for the specified service subsets.
     */
    subsets?: pulumi.Input<pulumi.Input<inputs.security.SecurityServiceSecuritySettingSubset>[] | undefined>;
}

/**
 * The set of arguments for constructing a SecurityServiceSecuritySetting resource.
 */
export interface SecurityServiceSecuritySettingArgs {
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.security.SecurityServiceSecuritySettingConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the ServiceSecuritySetting resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the ServiceSecuritySetting resource.
     */
    parent: pulumi.Input<string>;
    /**
     * The service on which the configuration is being applied. Must be in namespace/FQDN format.
     */
    service: pulumi.Input<string>;
    /**
     * Security settings to apply to this service.
     */
    settings?: pulumi.Input<inputs.security.SecurityServiceSecuritySettingSettings | undefined>;
    /**
     * Subset specific settings that will replace the service wide settings for the specified service subsets.
     */
    subsets?: pulumi.Input<pulumi.Input<inputs.security.SecurityServiceSecuritySettingSubset>[] | undefined>;
}
