// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const EnvValueSource = {
    Inline: "INLINE",
    Host: "HOST",
} as const;

export type EnvValueSource = (typeof EnvValueSource)[keyof typeof EnvValueSource];

export const WasmExtensionPluginPhase = {
    UnspecifiedPhase: "UNSPECIFIED_PHASE",
    Authn: "AUTHN",
    Authz: "AUTHZ",
    Stats: "STATS",
} as const;

export type WasmExtensionPluginPhase = (typeof WasmExtensionPluginPhase)[keyof typeof WasmExtensionPluginPhase];

export const WasmExtensionPullPolicy = {
    UnspecifiedPolicy: "UNSPECIFIED_POLICY",
    Ifnotpresent: "IfNotPresent",
    Always: "Always",
} as const;

export type WasmExtensionPullPolicy = (typeof WasmExtensionPullPolicy)[keyof typeof WasmExtensionPullPolicy];
