// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { IstioTrafficDestinationRuleArgs, IstioTrafficDestinationRuleState } from "./istioTrafficDestinationRule";
export type IstioTrafficDestinationRule = import("./istioTrafficDestinationRule").IstioTrafficDestinationRule;
export const IstioTrafficDestinationRule: typeof import("./istioTrafficDestinationRule").IstioTrafficDestinationRule = null as any;
utilities.lazyLoad(exports, ["IstioTrafficDestinationRule"], () => require("./istioTrafficDestinationRule"));

export { IstioTrafficSidecarArgs, IstioTrafficSidecarState } from "./istioTrafficSidecar";
export type IstioTrafficSidecar = import("./istioTrafficSidecar").IstioTrafficSidecar;
export const IstioTrafficSidecar: typeof import("./istioTrafficSidecar").IstioTrafficSidecar = null as any;
utilities.lazyLoad(exports, ["IstioTrafficSidecar"], () => require("./istioTrafficSidecar"));

export { IstioTrafficVirtualServiceArgs, IstioTrafficVirtualServiceState } from "./istioTrafficVirtualService";
export type IstioTrafficVirtualService = import("./istioTrafficVirtualService").IstioTrafficVirtualService;
export const IstioTrafficVirtualService: typeof import("./istioTrafficVirtualService").IstioTrafficVirtualService = null as any;
utilities.lazyLoad(exports, ["IstioTrafficVirtualService"], () => require("./istioTrafficVirtualService"));

export { TrafficGroupArgs, TrafficGroupState } from "./trafficGroup";
export type TrafficGroup = import("./trafficGroup").TrafficGroup;
export const TrafficGroup: typeof import("./trafficGroup").TrafficGroup = null as any;
utilities.lazyLoad(exports, ["TrafficGroup"], () => require("./trafficGroup"));

export { TrafficServiceRouteArgs, TrafficServiceRouteState } from "./trafficServiceRoute";
export type TrafficServiceRoute = import("./trafficServiceRoute").TrafficServiceRoute;
export const TrafficServiceRoute: typeof import("./trafficServiceRoute").TrafficServiceRoute = null as any;
utilities.lazyLoad(exports, ["TrafficServiceRoute"], () => require("./trafficServiceRoute"));

export { TrafficServiceTrafficSettingArgs, TrafficServiceTrafficSettingState } from "./trafficServiceTrafficSetting";
export type TrafficServiceTrafficSetting = import("./trafficServiceTrafficSetting").TrafficServiceTrafficSetting;
export const TrafficServiceTrafficSetting: typeof import("./trafficServiceTrafficSetting").TrafficServiceTrafficSetting = null as any;
utilities.lazyLoad(exports, ["TrafficServiceTrafficSetting"], () => require("./trafficServiceTrafficSetting"));

export { TrafficTrafficSettingArgs, TrafficTrafficSettingState } from "./trafficTrafficSetting";
export type TrafficTrafficSetting = import("./trafficTrafficSetting").TrafficTrafficSetting;
export const TrafficTrafficSetting: typeof import("./trafficTrafficSetting").TrafficTrafficSetting = null as any;
utilities.lazyLoad(exports, ["TrafficTrafficSetting"], () => require("./trafficTrafficSetting"));


// Export enums:
export * from "../types/enums/traffic";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tsb:traffic/istioTrafficDestinationRule:IstioTrafficDestinationRule":
                return new IstioTrafficDestinationRule(name, <any>undefined, { urn })
            case "tsb:traffic/istioTrafficSidecar:IstioTrafficSidecar":
                return new IstioTrafficSidecar(name, <any>undefined, { urn })
            case "tsb:traffic/istioTrafficVirtualService:IstioTrafficVirtualService":
                return new IstioTrafficVirtualService(name, <any>undefined, { urn })
            case "tsb:traffic/trafficGroup:TrafficGroup":
                return new TrafficGroup(name, <any>undefined, { urn })
            case "tsb:traffic/trafficServiceRoute:TrafficServiceRoute":
                return new TrafficServiceRoute(name, <any>undefined, { urn })
            case "tsb:traffic/trafficServiceTrafficSetting:TrafficServiceTrafficSetting":
                return new TrafficServiceTrafficSetting(name, <any>undefined, { urn })
            case "tsb:traffic/trafficTrafficSetting:TrafficTrafficSetting":
                return new TrafficTrafficSetting(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tsb", "traffic/istioTrafficDestinationRule", _module)
pulumi.runtime.registerResourceModule("tsb", "traffic/istioTrafficSidecar", _module)
pulumi.runtime.registerResourceModule("tsb", "traffic/istioTrafficVirtualService", _module)
pulumi.runtime.registerResourceModule("tsb", "traffic/trafficGroup", _module)
pulumi.runtime.registerResourceModule("tsb", "traffic/trafficServiceRoute", _module)
pulumi.runtime.registerResourceModule("tsb", "traffic/trafficServiceTrafficSetting", _module)
pulumi.runtime.registerResourceModule("tsb", "traffic/trafficTrafficSetting", _module)
