// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class IstioTrafficSidecar extends pulumi.CustomResource {
    /**
     * Get an existing IstioTrafficSidecar resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IstioTrafficSidecarState, opts?: pulumi.CustomResourceOptions): IstioTrafficSidecar {
        return new IstioTrafficSidecar(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:traffic/istioTrafficSidecar:IstioTrafficSidecar';

    /**
     * Returns true if the given object is an instance of IstioTrafficSidecar.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IstioTrafficSidecar {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IstioTrafficSidecar.__pulumiType;
    }

    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Metadata for the Istio object
     */
    declare public readonly metadata: pulumi.Output<outputs.traffic.IstioTrafficSidecarMetadata | undefined>;
    /**
     * Short name of the IstioObject resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the IstioObject resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * The Istio API object
     */
    declare public readonly spec: pulumi.Output<string>;

    /**
     * Create a IstioTrafficSidecar resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IstioTrafficSidecarArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IstioTrafficSidecarArgs | IstioTrafficSidecarState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IstioTrafficSidecarState | undefined;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["spec"] = state?.spec;
        } else {
            const args = argsOrState as IstioTrafficSidecarArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["spec"] = args?.spec;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IstioTrafficSidecar.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IstioTrafficSidecar resources.
 */
export interface IstioTrafficSidecarState {
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Metadata for the Istio object
     */
    metadata?: pulumi.Input<inputs.traffic.IstioTrafficSidecarMetadata | undefined>;
    /**
     * Short name of the IstioObject resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the IstioObject resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * The Istio API object
     */
    spec?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IstioTrafficSidecar resource.
 */
export interface IstioTrafficSidecarArgs {
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Metadata for the Istio object
     */
    metadata?: pulumi.Input<inputs.traffic.IstioTrafficSidecarMetadata | undefined>;
    /**
     * Short name of the IstioObject resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the IstioObject resource.
     */
    parent: pulumi.Input<string>;
    /**
     * The Istio API object
     */
    spec?: pulumi.Input<string | undefined>;
}
