// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class TrafficServiceRoute extends pulumi.CustomResource {
    /**
     * Get an existing TrafficServiceRoute resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TrafficServiceRouteState, opts?: pulumi.CustomResourceOptions): TrafficServiceRoute {
        return new TrafficServiceRoute(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:traffic/trafficServiceRoute:TrafficServiceRoute';

    /**
     * Returns true if the given object is an instance of TrafficServiceRoute.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TrafficServiceRoute {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TrafficServiceRoute.__pulumiType;
    }

    /**
     * ArgoRollout configures this ServiceRoute to be controlled by Argo Rollouts.
     */
    declare public readonly argoRollout: pulumi.Output<outputs.traffic.TrafficServiceRouteArgoRollout | undefined>;
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.traffic.TrafficServiceRouteConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * HTTPRoutes are used when HTTP traffic needs to be matched on uri, headers and port and destination routes need to be set using subset-weight combinations specified within the route. **Note**: If a route is specified, then the global subset-weight combinations (specified under subsets) will be ignored for the matched port, as subsets within route will take effect.
     */
    declare public readonly httpRoutes: pulumi.Output<outputs.traffic.TrafficServiceRouteHttpRoute[] | undefined>;
    /**
     * Short name of the ServiceRoute resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the ServiceRoute resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * In order to support multi-protocol routing, a list of all port/protocol combinations is needed. These port settings are applied to all the subsets
     */
    declare public readonly portLevelSettings: pulumi.Output<outputs.traffic.TrafficServiceRoutePortLevelSetting[] | undefined>;
    /**
     * The service on which the configuration is being applied. Must be in namespace/FQDN format.
     */
    declare public readonly service: pulumi.Output<string>;
    /**
     * StickySession specifies how to forward traffic from a client to the same backend
     */
    declare public readonly stickySession: pulumi.Output<outputs.traffic.TrafficServiceRouteStickySession | undefined>;
    /**
     * The set of versions of a service and the percentage of traffic to send to each version.
     */
    declare public readonly subsets: pulumi.Output<outputs.traffic.TrafficServiceRouteSubset[] | undefined>;
    /**
     * TCPRoutes match TCP traffic based on port number. The subset-weight configuration and priority have the same behaviour as HTTPRoutes.
     */
    declare public readonly tcpRoutes: pulumi.Output<outputs.traffic.TrafficServiceRouteTcpRoute[] | undefined>;

    /**
     * Create a TrafficServiceRoute resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TrafficServiceRouteArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TrafficServiceRouteArgs | TrafficServiceRouteState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TrafficServiceRouteState | undefined;
            resourceInputs["argoRollout"] = state?.argoRollout;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["httpRoutes"] = state?.httpRoutes;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["portLevelSettings"] = state?.portLevelSettings;
            resourceInputs["service"] = state?.service;
            resourceInputs["stickySession"] = state?.stickySession;
            resourceInputs["subsets"] = state?.subsets;
            resourceInputs["tcpRoutes"] = state?.tcpRoutes;
        } else {
            const args = argsOrState as TrafficServiceRouteArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            if (args?.service === undefined && !opts.urn) {
                throw new Error("Missing required property 'service'");
            }
            resourceInputs["argoRollout"] = args?.argoRollout;
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["httpRoutes"] = args?.httpRoutes;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["portLevelSettings"] = args?.portLevelSettings;
            resourceInputs["service"] = args?.service;
            resourceInputs["stickySession"] = args?.stickySession;
            resourceInputs["subsets"] = args?.subsets;
            resourceInputs["tcpRoutes"] = args?.tcpRoutes;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TrafficServiceRoute.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TrafficServiceRoute resources.
 */
export interface TrafficServiceRouteState {
    /**
     * ArgoRollout configures this ServiceRoute to be controlled by Argo Rollouts.
     */
    argoRollout?: pulumi.Input<inputs.traffic.TrafficServiceRouteArgoRollout | undefined>;
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.traffic.TrafficServiceRouteConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * HTTPRoutes are used when HTTP traffic needs to be matched on uri, headers and port and destination routes need to be set using subset-weight combinations specified within the route. **Note**: If a route is specified, then the global subset-weight combinations (specified under subsets) will be ignored for the matched port, as subsets within route will take effect.
     */
    httpRoutes?: pulumi.Input<pulumi.Input<inputs.traffic.TrafficServiceRouteHttpRoute>[] | undefined>;
    /**
     * Short name of the ServiceRoute resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the ServiceRoute resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * In order to support multi-protocol routing, a list of all port/protocol combinations is needed. These port settings are applied to all the subsets
     */
    portLevelSettings?: pulumi.Input<pulumi.Input<inputs.traffic.TrafficServiceRoutePortLevelSetting>[] | undefined>;
    /**
     * The service on which the configuration is being applied. Must be in namespace/FQDN format.
     */
    service?: pulumi.Input<string | undefined>;
    /**
     * StickySession specifies how to forward traffic from a client to the same backend
     */
    stickySession?: pulumi.Input<inputs.traffic.TrafficServiceRouteStickySession | undefined>;
    /**
     * The set of versions of a service and the percentage of traffic to send to each version.
     */
    subsets?: pulumi.Input<pulumi.Input<inputs.traffic.TrafficServiceRouteSubset>[] | undefined>;
    /**
     * TCPRoutes match TCP traffic based on port number. The subset-weight configuration and priority have the same behaviour as HTTPRoutes.
     */
    tcpRoutes?: pulumi.Input<pulumi.Input<inputs.traffic.TrafficServiceRouteTcpRoute>[] | undefined>;
}

/**
 * The set of arguments for constructing a TrafficServiceRoute resource.
 */
export interface TrafficServiceRouteArgs {
    /**
     * ArgoRollout configures this ServiceRoute to be controlled by Argo Rollouts.
     */
    argoRollout?: pulumi.Input<inputs.traffic.TrafficServiceRouteArgoRollout | undefined>;
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.traffic.TrafficServiceRouteConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * HTTPRoutes are used when HTTP traffic needs to be matched on uri, headers and port and destination routes need to be set using subset-weight combinations specified within the route. **Note**: If a route is specified, then the global subset-weight combinations (specified under subsets) will be ignored for the matched port, as subsets within route will take effect.
     */
    httpRoutes?: pulumi.Input<pulumi.Input<inputs.traffic.TrafficServiceRouteHttpRoute>[] | undefined>;
    /**
     * Short name of the ServiceRoute resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the ServiceRoute resource.
     */
    parent: pulumi.Input<string>;
    /**
     * In order to support multi-protocol routing, a list of all port/protocol combinations is needed. These port settings are applied to all the subsets
     */
    portLevelSettings?: pulumi.Input<pulumi.Input<inputs.traffic.TrafficServiceRoutePortLevelSetting>[] | undefined>;
    /**
     * The service on which the configuration is being applied. Must be in namespace/FQDN format.
     */
    service: pulumi.Input<string>;
    /**
     * StickySession specifies how to forward traffic from a client to the same backend
     */
    stickySession?: pulumi.Input<inputs.traffic.TrafficServiceRouteStickySession | undefined>;
    /**
     * The set of versions of a service and the percentage of traffic to send to each version.
     */
    subsets?: pulumi.Input<pulumi.Input<inputs.traffic.TrafficServiceRouteSubset>[] | undefined>;
    /**
     * TCPRoutes match TCP traffic based on port number. The subset-weight configuration and priority have the same behaviour as HTTPRoutes.
     */
    tcpRoutes?: pulumi.Input<pulumi.Input<inputs.traffic.TrafficServiceRouteTcpRoute>[] | undefined>;
}
