// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class TrafficGroup extends pulumi.CustomResource {
    /**
     * Get an existing TrafficGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TrafficGroupState, opts?: pulumi.CustomResourceOptions): TrafficGroup {
        return new TrafficGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:traffic/trafficGroup:TrafficGroup';

    /**
     * Returns true if the given object is an instance of TrafficGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TrafficGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TrafficGroup.__pulumiType;
    }

    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.traffic.TrafficGroupConfigGenerationMetadata | undefined>;
    /**
     * The Configuration types that will be added to this group. `BRIDGED` mode indicates that configurations added to this group will use Tetrate APIs such as `TrafficSetting` and `ServiceRoute`. `DIRECT` mode indicates that configurations added to this group will use Istio Networking APIs such as `VirtualService`, `DestinationRule`, and `Sidecar`. Defaults to `BRIDGED` mode. Possible values: BRIDGED, DIRECT.
     */
    declare public readonly configMode: pulumi.Output<string>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    declare public readonly deletionProtectionEnabled: pulumi.Output<boolean>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Short name of the Group resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Set of namespaces owned exclusively by this group. Use `*&#47;*` to claim all cluster resources under the workspace.
     */
    declare public readonly namespaceSelector: pulumi.Output<outputs.traffic.TrafficGroupNamespaceSelector>;
    /**
     * The parent id for the Group resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * List of profiles attached to the traffic group to be used to propagate default and mandatory configurations down to the children.
     */
    declare public readonly profiles: pulumi.Output<string[]>;

    /**
     * Create a TrafficGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TrafficGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TrafficGroupArgs | TrafficGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TrafficGroupState | undefined;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["configMode"] = state?.configMode;
            resourceInputs["deletionProtectionEnabled"] = state?.deletionProtectionEnabled;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["name"] = state?.name;
            resourceInputs["namespaceSelector"] = state?.namespaceSelector;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["profiles"] = state?.profiles;
        } else {
            const args = argsOrState as TrafficGroupArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.namespaceSelector === undefined && !opts.urn) {
                throw new Error("Missing required property 'namespaceSelector'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["configMode"] = args?.configMode;
            resourceInputs["deletionProtectionEnabled"] = args?.deletionProtectionEnabled;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespaceSelector"] = args?.namespaceSelector;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["profiles"] = args?.profiles;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TrafficGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TrafficGroup resources.
 */
export interface TrafficGroupState {
    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.traffic.TrafficGroupConfigGenerationMetadata | undefined>;
    /**
     * The Configuration types that will be added to this group. `BRIDGED` mode indicates that configurations added to this group will use Tetrate APIs such as `TrafficSetting` and `ServiceRoute`. `DIRECT` mode indicates that configurations added to this group will use Istio Networking APIs such as `VirtualService`, `DestinationRule`, and `Sidecar`. Defaults to `BRIDGED` mode. Possible values: BRIDGED, DIRECT.
     */
    configMode?: pulumi.Input<string | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the Group resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Set of namespaces owned exclusively by this group. Use `*&#47;*` to claim all cluster resources under the workspace.
     */
    namespaceSelector?: pulumi.Input<inputs.traffic.TrafficGroupNamespaceSelector | undefined>;
    /**
     * The parent id for the Group resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * List of profiles attached to the traffic group to be used to propagate default and mandatory configurations down to the children.
     */
    profiles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a TrafficGroup resource.
 */
export interface TrafficGroupArgs {
    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.traffic.TrafficGroupConfigGenerationMetadata | undefined>;
    /**
     * The Configuration types that will be added to this group. `BRIDGED` mode indicates that configurations added to this group will use Tetrate APIs such as `TrafficSetting` and `ServiceRoute`. `DIRECT` mode indicates that configurations added to this group will use Istio Networking APIs such as `VirtualService`, `DestinationRule`, and `Sidecar`. Defaults to `BRIDGED` mode. Possible values: BRIDGED, DIRECT.
     */
    configMode?: pulumi.Input<string | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the Group resource.
     */
    name: pulumi.Input<string>;
    /**
     * Set of namespaces owned exclusively by this group. Use `*&#47;*` to claim all cluster resources under the workspace.
     */
    namespaceSelector: pulumi.Input<inputs.traffic.TrafficGroupNamespaceSelector>;
    /**
     * The parent id for the Group resource.
     */
    parent: pulumi.Input<string>;
    /**
     * List of profiles attached to the traffic group to be used to propagate default and mandatory configurations down to the children.
     */
    profiles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
