// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("tsb");

/**
 * Path to a PEM CA bundle used to verify the TSB server certificate. May also be set via the TSB_CA_FILE environment variable.
 */
export declare const caFile: string | undefined;
Object.defineProperty(exports, "caFile", {
    get() {
        return __config.get("caFile");
    },
    enumerable: true,
});

/**
 * TSB gRPC endpoint (host:port). May also be set via the TSB_ENDPOINT environment variable.
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint");
    },
    enumerable: true,
});

/**
 * TSB organization the resources belong to. May also be set via the TSB_ORG environment variable.
 */
export declare const organization: string | undefined;
Object.defineProperty(exports, "organization", {
    get() {
        return __config.get("organization");
    },
    enumerable: true,
});

/**
 * Password for HTTP Basic authentication, used together with `username`. May also be set via the TSB_PASSWORD environment variable.
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * Disable transport security entirely (plaintext). May also be set via the TSB_TLS_DISABLED environment variable.
 */
export declare const tlsDisabled: boolean | undefined;
Object.defineProperty(exports, "tlsDisabled", {
    get() {
        return __config.getObject<boolean>("tlsDisabled");
    },
    enumerable: true,
});

/**
 * Keep TLS enabled but skip server certificate verification. May also be set via the TSB_TLS_INSECURE environment variable.
 */
export declare const tlsInsecure: boolean | undefined;
Object.defineProperty(exports, "tlsInsecure", {
    get() {
        return __config.getObject<boolean>("tlsInsecure");
    },
    enumerable: true,
});

/**
 * TSB API token sent in the x-tetrate-token header. Takes precedence over username/password. May also be set via the TSB_TOKEN environment variable.
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

/**
 * Username for HTTP Basic authentication, used when `token` is not set. May also be set via the TSB_USERNAME environment variable.
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

