// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

package main

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"google.golang.org/protobuf/reflect/protoreflect"
)

// fieldNode merges many enum sites into one nested SchemaInfo literal per
// resource. Non-leaf nodes carry children; leaves carry a token.
type fieldNode struct {
	children   map[string]*fieldNode
	token      string // non-empty at an enum leaf
	element    bool   // leaf is a collection element, so the token nests one deeper
	collection bool   // non-leaf reached via a List/MapNestedAttribute; see pathSegment.Collection
}

func newFieldNode() *fieldNode {
	return &fieldNode{children: map[string]*fieldNode{}}
}

// buildFieldTrees folds the flat site list into one tree per resource.
func buildFieldTrees(sites []enumSite, tokens map[protoreflect.FullName]string) (map[string]*fieldNode, error) {
	roots := map[string]*fieldNode{}
	for _, s := range sites {
		tok, ok := tokens[s.Enum]
		if !ok {
			return nil, fmt.Errorf("no Pulumi token was computed for enum %q", s.Enum)
		}
		root, ok := roots[s.Resource]
		if !ok {
			root = newFieldNode()
			roots[s.Resource] = root
		}
		n := root
		for _, seg := range s.Path {
			child, ok := n.children[seg.Name]
			if !ok {
				child = newFieldNode()
				n.children[seg.Name] = child
			}
			child.collection = seg.Collection
			n = child
		}
		n.token, n.element = tok, s.Element
	}
	return roots, nil
}

// renderFields writes a map[string]*tfbridge.SchemaInfo literal. Indentation is
// left to format.Source.
func renderFields(b *strings.Builder, children map[string]*fieldNode) {
	b.WriteString("map[string]*tfbridge.SchemaInfo{\n")
	names := make([]string, 0, len(children))
	for n := range children {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(b, "%q: ", name)
		renderNode(b, children[name])
		b.WriteString(",\n")
	}
	b.WriteString("}")
}

// renderNode writes a single *tfbridge.SchemaInfo literal. A nesting level
// costs one .Elem for a SingleNestedAttribute (pf shim: Type=Map/Elem=Resource
// directly) but two for a List/MapNestedAttribute (pf shim: List-or-Map
// wrapping that same Type=Map/Elem=Resource shape one level deeper) — see
// pathSegment.Collection. Getting this wrong doesn't error at generation
// time; tfgen's own structural validator (pkg/tfbridge/info/validate.go)
// rejects the mismatch with ".Fields should be .Elem.Fields" at schema-build
// time instead.
func renderNode(b *strings.Builder, n *fieldNode) {
	switch {
	case n.token != "" && n.element:
		fmt.Fprintf(b, "{Elem: &tfbridge.SchemaInfo{Type: %q}}", n.token)
	case n.token != "":
		fmt.Fprintf(b, "{Type: %q}", n.token)
	case n.collection:
		b.WriteString("{Elem: &tfbridge.SchemaInfo{Elem: &tfbridge.SchemaInfo{Fields: ")
		renderFields(b, n.children)
		b.WriteString("}}}")
	default:
		b.WriteString("{Elem: &tfbridge.SchemaInfo{Fields: ")
		renderFields(b, n.children)
		b.WriteString("}}")
	}
}

// generateSource renders provider/resources_gen.go: the resource token map with
// enum tokens threaded in, plus the enum type definitions fed to
// ProviderInfo.ExtraTypes.
//
// groups maps each resource's type suffix (without the "tsb_" prefix) to its
// TSB API group, per terraform-provider-tsb's pkg/provider.Groups(); a missing
// entry and an explicit "" both fall back to the tsbMod identifier, so
// hand-written resources (e.g. "access_binding", absent from Groups()) and real
// core resources (group "") are handled identically with no special-casing.
func generateSource(
	types []string,
	groups map[string]string,
	sites []enumSite,
	enums []enumInfo,
) ([]byte, error) {
	tokens := make(map[protoreflect.FullName]string, len(enums))
	byToken := make(map[string]enumInfo, len(enums))
	for _, e := range enums {
		tok, err := enumToken(e)
		if err != nil {
			return nil, err
		}
		if prev, clash := byToken[tok]; clash {
			return nil, fmt.Errorf(
				"enums %q and %q both derive Pulumi token %q", prev.FullName, e.FullName, tok)
		}
		tokens[e.FullName] = tok
		byToken[tok] = e
	}

	trees, err := buildFieldTrees(sites, tokens)
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	b.WriteString("// Code generated by gen-resources-tsb. DO NOT EDIT.\n\n")
	b.WriteString("package tsb\n\n")
	b.WriteString("import (\n")
	b.WriteString("\tpschema \"github.com/pulumi/pulumi/pkg/v3/codegen/schema\"\n")
	b.WriteString("\t\"github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge\"\n")
	b.WriteString(")\n\n")

	b.WriteString("var generatedResources = map[string]*tfbridge.ResourceInfo{\n")
	for _, t := range types {
		suffix := strings.TrimPrefix(t, providerTypeName+"_")
		mod := "tsbMod"
		if g := groups[suffix]; g != "" {
			mod = strconv.Quote(g)
		}
		fmt.Fprintf(&b, "%q: {Tok: tsbResourceTok(%s, %q)", t, mod, pascalCase(suffix))
		if tree, ok := trees[t]; ok {
			b.WriteString(", Fields: ")
			renderFields(&b, tree.children)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("var generatedEnums = map[string]pschema.ComplexTypeSpec{\n")
	tokenNames := make([]string, 0, len(byToken))
	for tok := range byToken {
		tokenNames = append(tokenNames, tok)
	}
	sort.Strings(tokenNames)
	for _, tok := range tokenNames {
		fmt.Fprintf(&b, "%q: {\n", tok)
		b.WriteString("ObjectTypeSpec: pschema.ObjectTypeSpec{Type: \"string\"},\n")
		b.WriteString("Enum: []pschema.EnumValueSpec{\n")
		// Two proto values mangling to one member name would emit a duplicate
		// TypeScript enum member, so catch it here rather than in tsc.
		seen := map[string]string{}
		for _, v := range byToken[tok].Values {
			name, err := enumMemberName(v)
			if err != nil {
				return nil, fmt.Errorf("enum %q: %w", byToken[tok].FullName, err)
			}
			if prev, clash := seen[name]; clash {
				return nil, fmt.Errorf(
					"enum %q: values %q and %q both yield member name %q",
					byToken[tok].FullName, prev, v, name)
			}
			seen[name] = v
			fmt.Fprintf(&b, "{Name: %q, Value: %q},\n", name, v)
		}
		b.WriteString("},\n},\n")
	}
	b.WriteString("}\n")

	return format.Source([]byte(b.String()))
}
