// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { ProfileProfileArgs, ProfileProfileState } from "./profileProfile";
export type ProfileProfile = import("./profileProfile").ProfileProfile;
export const ProfileProfile: typeof import("./profileProfile").ProfileProfile = null as any;
utilities.lazyLoad(exports, ["ProfileProfile"], () => require("./profileProfile"));


// Export enums:
export * from "../types/enums/profile";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tsb:profile/profileProfile:ProfileProfile":
                return new ProfileProfile(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tsb", "profile/profileProfile", _module)
