// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class ProfileProfile extends pulumi.CustomResource {
    /**
     * Get an existing ProfileProfile resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProfileProfileState, opts?: pulumi.CustomResourceOptions): ProfileProfile {
        return new ProfileProfile(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:profile/profileProfile:ProfileProfile';

    /**
     * Returns true if the given object is an instance of ProfileProfile.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProfileProfile {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProfileProfile.__pulumiType;
    }

    /**
     * Defaults section of the profile is meant for configurations which are allowed to be overwritten by subsequent profiles or by user defined configurations in the attached resources.
     */
    declare public readonly defaults: pulumi.Output<outputs.profile.ProfileProfileDefaults | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    declare public readonly deletionProtectionEnabled: pulumi.Output<boolean>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Mandates section of the profile is meant for configurations which can't be relaxed.
     */
    declare public readonly mandates: pulumi.Output<outputs.profile.ProfileProfileMandates | undefined>;
    /**
     * Short name of the Profile resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the Profile resource.
     */
    declare public readonly parent: pulumi.Output<string>;

    /**
     * Create a ProfileProfile resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProfileProfileArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProfileProfileArgs | ProfileProfileState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProfileProfileState | undefined;
            resourceInputs["defaults"] = state?.defaults;
            resourceInputs["deletionProtectionEnabled"] = state?.deletionProtectionEnabled;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["mandates"] = state?.mandates;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
        } else {
            const args = argsOrState as ProfileProfileArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["defaults"] = args?.defaults;
            resourceInputs["deletionProtectionEnabled"] = args?.deletionProtectionEnabled;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["mandates"] = args?.mandates;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProfileProfile.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProfileProfile resources.
 */
export interface ProfileProfileState {
    /**
     * Defaults section of the profile is meant for configurations which are allowed to be overwritten by subsequent profiles or by user defined configurations in the attached resources.
     */
    defaults?: pulumi.Input<inputs.profile.ProfileProfileDefaults | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Mandates section of the profile is meant for configurations which can't be relaxed.
     */
    mandates?: pulumi.Input<inputs.profile.ProfileProfileMandates | undefined>;
    /**
     * Short name of the Profile resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the Profile resource.
     */
    parent?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ProfileProfile resource.
 */
export interface ProfileProfileArgs {
    /**
     * Defaults section of the profile is meant for configurations which are allowed to be overwritten by subsequent profiles or by user defined configurations in the attached resources.
     */
    defaults?: pulumi.Input<inputs.profile.ProfileProfileDefaults | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Mandates section of the profile is meant for configurations which can't be relaxed.
     */
    mandates?: pulumi.Input<inputs.profile.ProfileProfileMandates | undefined>;
    /**
     * Short name of the Profile resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the Profile resource.
     */
    parent: pulumi.Input<string>;
}
