// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Cluster extends pulumi.CustomResource {
    /**
     * Get an existing Cluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClusterState, opts?: pulumi.CustomResourceOptions): Cluster {
        return new Cluster(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:index/cluster:Cluster';

    /**
     * Returns true if the given object is an instance of Cluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Cluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Cluster.__pulumiType;
    }

    /**
     * Default metadata values that can be used for configuring segmentation membership When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.ClusterConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Template to be used to install this TSB cluster in the k8s cluster
     */
    declare public readonly installTemplate: pulumi.Output<outputs.ClusterInstallTemplate | undefined>;
    /**
     * FIXME: this is super clunky to copy each and every metadata field into objects used for multicluster.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string}>;
    /**
     * Deprecated. For backward compatibility, still honoured but will be ignored in future releases, so better not to set it. Locality of the service endpoints will be dynamically discovered by the xcp-edge Location information about the cluster which can be used for routing.
     */
    declare public readonly locality: pulumi.Output<outputs.ClusterLocality | undefined>;
    /**
     * Short name of the Cluster resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Configure the default scoping of namespaces in this cluster.
     */
    declare public readonly namespaceScope: pulumi.Output<outputs.ClusterNamespaceScope | undefined>;
    /**
     * TODO(vikas): move this inside cluster state Read-only data for informational purposes. Any user provided value will be ignored. The data here may be stale depending on the update frequency from the Bridge agents in the cluster.
     */
    declare public readonly namespaces: pulumi.Output<outputs.ClusterNamespace[] | undefined>;
    /**
     * The network (e.g., VPC) where this cluster is present. All clusters within the same network will be assumed to be reachable for the purposes of multi-cluster routing. In addition, networks marked as reachable from one another in SystemSettings will also be used for multi-cluster routing.
     */
    declare public readonly network: pulumi.Output<string>;
    /**
     * The parent id for the Cluster resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * The service account created with permissions to manage the current cluster. The service account is not stored and it is only returned in the `ClusterCreate` response.
     */
    declare public /*out*/ readonly serviceAccount: pulumi.Output<string>;
    declare public readonly state: pulumi.Output<outputs.ClusterState | undefined>;
    /**
     * Deprecated: This flag is still honored for backward compatibility but will be ignored in future releases. It is advisable not to set it, as all clusters can now host both Tier1 and IngressGateways. Indicates whether this cluster is hosting a tier1 gateway or not. Tier1 clusters cannot host other gateways or workloads. Defaults to false if not specified.
     */
    declare public readonly tier1Cluster: pulumi.Output<outputs.ClusterTier1Cluster | undefined>;
    /**
     * Lifetime of the tokens. Defaults to 1hr.
     */
    declare public readonly tokenTtl: pulumi.Output<outputs.ClusterTokenTtl | undefined>;
    /**
     * Trust domain for this cluster, used for multi-cluster routing. It must be unique for every cluster and should match the one configured in the local control plane. This value is optional, and will be updated by the local control plane agents. However, it is recommended to set it, if known, so that multi-cluster routing works without having to wait for the local control planes to update it.
     */
    declare public readonly trustDomain: pulumi.Output<string>;

    /**
     * Create a Cluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClusterArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClusterArgs | ClusterState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClusterState | undefined;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["installTemplate"] = state?.installTemplate;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["locality"] = state?.locality;
            resourceInputs["name"] = state?.name;
            resourceInputs["namespaceScope"] = state?.namespaceScope;
            resourceInputs["namespaces"] = state?.namespaces;
            resourceInputs["network"] = state?.network;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["serviceAccount"] = state?.serviceAccount;
            resourceInputs["state"] = state?.state;
            resourceInputs["tier1Cluster"] = state?.tier1Cluster;
            resourceInputs["tokenTtl"] = state?.tokenTtl;
            resourceInputs["trustDomain"] = state?.trustDomain;
        } else {
            const args = argsOrState as ClusterArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["installTemplate"] = args?.installTemplate;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["locality"] = args?.locality;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespaceScope"] = args?.namespaceScope;
            resourceInputs["namespaces"] = args?.namespaces;
            resourceInputs["network"] = args?.network;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["state"] = args?.state;
            resourceInputs["tier1Cluster"] = args?.tier1Cluster;
            resourceInputs["tokenTtl"] = args?.tokenTtl;
            resourceInputs["trustDomain"] = args?.trustDomain;
            resourceInputs["serviceAccount"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Cluster.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Cluster resources.
 */
export interface ClusterState {
    /**
     * Default metadata values that can be used for configuring segmentation membership When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.ClusterConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Template to be used to install this TSB cluster in the k8s cluster
     */
    installTemplate?: pulumi.Input<inputs.ClusterInstallTemplate | undefined>;
    /**
     * FIXME: this is super clunky to copy each and every metadata field into objects used for multicluster.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Deprecated. For backward compatibility, still honoured but will be ignored in future releases, so better not to set it. Locality of the service endpoints will be dynamically discovered by the xcp-edge Location information about the cluster which can be used for routing.
     */
    locality?: pulumi.Input<inputs.ClusterLocality | undefined>;
    /**
     * Short name of the Cluster resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Configure the default scoping of namespaces in this cluster.
     */
    namespaceScope?: pulumi.Input<inputs.ClusterNamespaceScope | undefined>;
    /**
     * TODO(vikas): move this inside cluster state Read-only data for informational purposes. Any user provided value will be ignored. The data here may be stale depending on the update frequency from the Bridge agents in the cluster.
     */
    namespaces?: pulumi.Input<pulumi.Input<inputs.ClusterNamespace>[] | undefined>;
    /**
     * The network (e.g., VPC) where this cluster is present. All clusters within the same network will be assumed to be reachable for the purposes of multi-cluster routing. In addition, networks marked as reachable from one another in SystemSettings will also be used for multi-cluster routing.
     */
    network?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the Cluster resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * The service account created with permissions to manage the current cluster. The service account is not stored and it is only returned in the `ClusterCreate` response.
     */
    serviceAccount?: pulumi.Input<string | undefined>;
    state?: pulumi.Input<inputs.ClusterState | undefined>;
    /**
     * Deprecated: This flag is still honored for backward compatibility but will be ignored in future releases. It is advisable not to set it, as all clusters can now host both Tier1 and IngressGateways. Indicates whether this cluster is hosting a tier1 gateway or not. Tier1 clusters cannot host other gateways or workloads. Defaults to false if not specified.
     */
    tier1Cluster?: pulumi.Input<inputs.ClusterTier1Cluster | undefined>;
    /**
     * Lifetime of the tokens. Defaults to 1hr.
     */
    tokenTtl?: pulumi.Input<inputs.ClusterTokenTtl | undefined>;
    /**
     * Trust domain for this cluster, used for multi-cluster routing. It must be unique for every cluster and should match the one configured in the local control plane. This value is optional, and will be updated by the local control plane agents. However, it is recommended to set it, if known, so that multi-cluster routing works without having to wait for the local control planes to update it.
     */
    trustDomain?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Cluster resource.
 */
export interface ClusterArgs {
    /**
     * Default metadata values that can be used for configuring segmentation membership When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.ClusterConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Template to be used to install this TSB cluster in the k8s cluster
     */
    installTemplate?: pulumi.Input<inputs.ClusterInstallTemplate | undefined>;
    /**
     * FIXME: this is super clunky to copy each and every metadata field into objects used for multicluster.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Deprecated. For backward compatibility, still honoured but will be ignored in future releases, so better not to set it. Locality of the service endpoints will be dynamically discovered by the xcp-edge Location information about the cluster which can be used for routing.
     */
    locality?: pulumi.Input<inputs.ClusterLocality | undefined>;
    /**
     * Short name of the Cluster resource.
     */
    name: pulumi.Input<string>;
    /**
     * Configure the default scoping of namespaces in this cluster.
     */
    namespaceScope?: pulumi.Input<inputs.ClusterNamespaceScope | undefined>;
    /**
     * TODO(vikas): move this inside cluster state Read-only data for informational purposes. Any user provided value will be ignored. The data here may be stale depending on the update frequency from the Bridge agents in the cluster.
     */
    namespaces?: pulumi.Input<pulumi.Input<inputs.ClusterNamespace>[] | undefined>;
    /**
     * The network (e.g., VPC) where this cluster is present. All clusters within the same network will be assumed to be reachable for the purposes of multi-cluster routing. In addition, networks marked as reachable from one another in SystemSettings will also be used for multi-cluster routing.
     */
    network?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the Cluster resource.
     */
    parent: pulumi.Input<string>;
    state?: pulumi.Input<inputs.ClusterState | undefined>;
    /**
     * Deprecated: This flag is still honored for backward compatibility but will be ignored in future releases. It is advisable not to set it, as all clusters can now host both Tier1 and IngressGateways. Indicates whether this cluster is hosting a tier1 gateway or not. Tier1 clusters cannot host other gateways or workloads. Defaults to false if not specified.
     */
    tier1Cluster?: pulumi.Input<inputs.ClusterTier1Cluster | undefined>;
    /**
     * Lifetime of the tokens. Defaults to 1hr.
     */
    tokenTtl?: pulumi.Input<inputs.ClusterTokenTtl | undefined>;
    /**
     * Trust domain for this cluster, used for multi-cluster routing. It must be unique for every cluster and should match the one configured in the local control plane. This value is optional, and will be updated by the local control plane agents. However, it is recommended to set it, if known, so that multi-cluster routing works without having to wait for the local control planes to update it.
     */
    trustDomain?: pulumi.Input<string | undefined>;
}
