// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class GatewayTier1Gateway extends pulumi.CustomResource {
    /**
     * Get an existing GatewayTier1Gateway resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GatewayTier1GatewayState, opts?: pulumi.CustomResourceOptions): GatewayTier1Gateway {
        return new GatewayTier1Gateway(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:index/gatewayTier1Gateway:GatewayTier1Gateway';

    /**
     * Returns true if the given object is an instance of GatewayTier1Gateway.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GatewayTier1Gateway {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GatewayTier1Gateway.__pulumiType;
    }

    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.GatewayTier1GatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Extensions specifies all the WasmExtensions assigned to this Tier1Gateway with the specific configuration for each extension. This custom configuration will override the one configured globally to the extension. Each extension has a global configuration including enablement and priority that will condition the execution of the assigned extensions.
     */
    declare public readonly extensions: pulumi.Output<outputs.GatewayTier1GatewayExtension[] | undefined>;
    /**
     * One or more servers exposed by the gateway externally.
     */
    declare public readonly externalServers: pulumi.Output<outputs.GatewayTier1GatewayExternalServer[] | undefined>;
    /**
     * One or more servers exposed by the gateway internally for cross cluster forwarding.
     */
    declare public readonly internalServers: pulumi.Output<outputs.GatewayTier1GatewayInternalServer[] | undefined>;
    /**
     * Short name of the Tier1Gateway resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the Tier1Gateway resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * One or more tls passthrough servers exposed by the gateway externally.
     */
    declare public readonly passthroughServers: pulumi.Output<outputs.GatewayTier1GatewayPassthroughServer[] | undefined>;
    /**
     * One or more tcp servers exposed by the gateway externally.
     */
    declare public readonly tcpExternalServers: pulumi.Output<outputs.GatewayTier1GatewayTcpExternalServer[] | undefined>;
    /**
     * One or more tcp servers exposed by the gateway for mesh internal traffic.
     */
    declare public readonly tcpInternalServers: pulumi.Output<outputs.GatewayTier1GatewayTcpInternalServer[] | undefined>;
    /**
     * WAF settings to be enabled for traffic passing through this Tier1 gateway.
     */
    declare public readonly waf: pulumi.Output<outputs.GatewayTier1GatewayWaf | undefined>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    declare public readonly workloadSelector: pulumi.Output<outputs.GatewayTier1GatewayWorkloadSelector>;

    /**
     * Create a GatewayTier1Gateway resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GatewayTier1GatewayArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GatewayTier1GatewayArgs | GatewayTier1GatewayState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GatewayTier1GatewayState | undefined;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["extensions"] = state?.extensions;
            resourceInputs["externalServers"] = state?.externalServers;
            resourceInputs["internalServers"] = state?.internalServers;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["passthroughServers"] = state?.passthroughServers;
            resourceInputs["tcpExternalServers"] = state?.tcpExternalServers;
            resourceInputs["tcpInternalServers"] = state?.tcpInternalServers;
            resourceInputs["waf"] = state?.waf;
            resourceInputs["workloadSelector"] = state?.workloadSelector;
        } else {
            const args = argsOrState as GatewayTier1GatewayArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            if (args?.workloadSelector === undefined && !opts.urn) {
                throw new Error("Missing required property 'workloadSelector'");
            }
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["extensions"] = args?.extensions;
            resourceInputs["externalServers"] = args?.externalServers;
            resourceInputs["internalServers"] = args?.internalServers;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["passthroughServers"] = args?.passthroughServers;
            resourceInputs["tcpExternalServers"] = args?.tcpExternalServers;
            resourceInputs["tcpInternalServers"] = args?.tcpInternalServers;
            resourceInputs["waf"] = args?.waf;
            resourceInputs["workloadSelector"] = args?.workloadSelector;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GatewayTier1Gateway.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GatewayTier1Gateway resources.
 */
export interface GatewayTier1GatewayState {
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.GatewayTier1GatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Extensions specifies all the WasmExtensions assigned to this Tier1Gateway with the specific configuration for each extension. This custom configuration will override the one configured globally to the extension. Each extension has a global configuration including enablement and priority that will condition the execution of the assigned extensions.
     */
    extensions?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayExtension>[] | undefined>;
    /**
     * One or more servers exposed by the gateway externally.
     */
    externalServers?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayExternalServer>[] | undefined>;
    /**
     * One or more servers exposed by the gateway internally for cross cluster forwarding.
     */
    internalServers?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayInternalServer>[] | undefined>;
    /**
     * Short name of the Tier1Gateway resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the Tier1Gateway resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * One or more tls passthrough servers exposed by the gateway externally.
     */
    passthroughServers?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayPassthroughServer>[] | undefined>;
    /**
     * One or more tcp servers exposed by the gateway externally.
     */
    tcpExternalServers?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayTcpExternalServer>[] | undefined>;
    /**
     * One or more tcp servers exposed by the gateway for mesh internal traffic.
     */
    tcpInternalServers?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayTcpInternalServer>[] | undefined>;
    /**
     * WAF settings to be enabled for traffic passing through this Tier1 gateway.
     */
    waf?: pulumi.Input<inputs.GatewayTier1GatewayWaf | undefined>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    workloadSelector?: pulumi.Input<inputs.GatewayTier1GatewayWorkloadSelector | undefined>;
}

/**
 * The set of arguments for constructing a GatewayTier1Gateway resource.
 */
export interface GatewayTier1GatewayArgs {
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.GatewayTier1GatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Extensions specifies all the WasmExtensions assigned to this Tier1Gateway with the specific configuration for each extension. This custom configuration will override the one configured globally to the extension. Each extension has a global configuration including enablement and priority that will condition the execution of the assigned extensions.
     */
    extensions?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayExtension>[] | undefined>;
    /**
     * One or more servers exposed by the gateway externally.
     */
    externalServers?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayExternalServer>[] | undefined>;
    /**
     * One or more servers exposed by the gateway internally for cross cluster forwarding.
     */
    internalServers?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayInternalServer>[] | undefined>;
    /**
     * Short name of the Tier1Gateway resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the Tier1Gateway resource.
     */
    parent: pulumi.Input<string>;
    /**
     * One or more tls passthrough servers exposed by the gateway externally.
     */
    passthroughServers?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayPassthroughServer>[] | undefined>;
    /**
     * One or more tcp servers exposed by the gateway externally.
     */
    tcpExternalServers?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayTcpExternalServer>[] | undefined>;
    /**
     * One or more tcp servers exposed by the gateway for mesh internal traffic.
     */
    tcpInternalServers?: pulumi.Input<pulumi.Input<inputs.GatewayTier1GatewayTcpInternalServer>[] | undefined>;
    /**
     * WAF settings to be enabled for traffic passing through this Tier1 gateway.
     */
    waf?: pulumi.Input<inputs.GatewayTier1GatewayWaf | undefined>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    workloadSelector: pulumi.Input<inputs.GatewayTier1GatewayWorkloadSelector>;
}
