// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class GatewayIngressGateway extends pulumi.CustomResource {
    /**
     * Get an existing GatewayIngressGateway resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GatewayIngressGatewayState, opts?: pulumi.CustomResourceOptions): GatewayIngressGateway {
        return new GatewayIngressGateway(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:index/gatewayIngressGateway:GatewayIngressGateway';

    /**
     * Returns true if the given object is an instance of GatewayIngressGateway.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GatewayIngressGateway {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GatewayIngressGateway.__pulumiType;
    }

    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.GatewayIngressGatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Extensions specifies all the WasmExtensions assigned to this IngressGateway with the specific configuration for each extension. This custom configuration will override the one configured globally to the extension. Each extension has a global configuration including enablement and priority that will condition the execution of the assigned extensions.
     */
    declare public readonly extensions: pulumi.Output<outputs.GatewayIngressGatewayExtension[] | undefined>;
    /**
     * One or more HTTP or HTTPS servers exposed by the gateway. The server exposes configuration for TLS termination, request authentication/authorization, HTTP routing, etc.
     */
    declare public readonly https: pulumi.Output<outputs.GatewayIngressGatewayHttp[] | undefined>;
    /**
     * Short name of the IngressGateway resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the IngressGateway resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * One or more non-HTTP and non-passthrough servers which use TCP based protocols. This server also exposes configuration for terminating TLS
     */
    declare public readonly tcps: pulumi.Output<outputs.GatewayIngressGatewayTcp[] | undefined>;
    /**
     * One or more TLS servers exposed by the gateway. The server does not terminate TLS and exposes config for SNI based routing.
     */
    declare public readonly tlsPassthroughs: pulumi.Output<outputs.GatewayIngressGatewayTlsPassthrough[] | undefined>;
    /**
     * WAF settings to be enabled for traffic passing through the HttpServer.
     */
    declare public readonly waf: pulumi.Output<outputs.GatewayIngressGatewayWaf | undefined>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    declare public readonly workloadSelector: pulumi.Output<outputs.GatewayIngressGatewayWorkloadSelector>;

    /**
     * Create a GatewayIngressGateway resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GatewayIngressGatewayArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GatewayIngressGatewayArgs | GatewayIngressGatewayState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GatewayIngressGatewayState | undefined;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["extensions"] = state?.extensions;
            resourceInputs["https"] = state?.https;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["tcps"] = state?.tcps;
            resourceInputs["tlsPassthroughs"] = state?.tlsPassthroughs;
            resourceInputs["waf"] = state?.waf;
            resourceInputs["workloadSelector"] = state?.workloadSelector;
        } else {
            const args = argsOrState as GatewayIngressGatewayArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            if (args?.workloadSelector === undefined && !opts.urn) {
                throw new Error("Missing required property 'workloadSelector'");
            }
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["extensions"] = args?.extensions;
            resourceInputs["https"] = args?.https;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["tcps"] = args?.tcps;
            resourceInputs["tlsPassthroughs"] = args?.tlsPassthroughs;
            resourceInputs["waf"] = args?.waf;
            resourceInputs["workloadSelector"] = args?.workloadSelector;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GatewayIngressGateway.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GatewayIngressGateway resources.
 */
export interface GatewayIngressGatewayState {
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.GatewayIngressGatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Extensions specifies all the WasmExtensions assigned to this IngressGateway with the specific configuration for each extension. This custom configuration will override the one configured globally to the extension. Each extension has a global configuration including enablement and priority that will condition the execution of the assigned extensions.
     */
    extensions?: pulumi.Input<pulumi.Input<inputs.GatewayIngressGatewayExtension>[] | undefined>;
    /**
     * One or more HTTP or HTTPS servers exposed by the gateway. The server exposes configuration for TLS termination, request authentication/authorization, HTTP routing, etc.
     */
    https?: pulumi.Input<pulumi.Input<inputs.GatewayIngressGatewayHttp>[] | undefined>;
    /**
     * Short name of the IngressGateway resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the IngressGateway resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * One or more non-HTTP and non-passthrough servers which use TCP based protocols. This server also exposes configuration for terminating TLS
     */
    tcps?: pulumi.Input<pulumi.Input<inputs.GatewayIngressGatewayTcp>[] | undefined>;
    /**
     * One or more TLS servers exposed by the gateway. The server does not terminate TLS and exposes config for SNI based routing.
     */
    tlsPassthroughs?: pulumi.Input<pulumi.Input<inputs.GatewayIngressGatewayTlsPassthrough>[] | undefined>;
    /**
     * WAF settings to be enabled for traffic passing through the HttpServer.
     */
    waf?: pulumi.Input<inputs.GatewayIngressGatewayWaf | undefined>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    workloadSelector?: pulumi.Input<inputs.GatewayIngressGatewayWorkloadSelector | undefined>;
}

/**
 * The set of arguments for constructing a GatewayIngressGateway resource.
 */
export interface GatewayIngressGatewayArgs {
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.GatewayIngressGatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Extensions specifies all the WasmExtensions assigned to this IngressGateway with the specific configuration for each extension. This custom configuration will override the one configured globally to the extension. Each extension has a global configuration including enablement and priority that will condition the execution of the assigned extensions.
     */
    extensions?: pulumi.Input<pulumi.Input<inputs.GatewayIngressGatewayExtension>[] | undefined>;
    /**
     * One or more HTTP or HTTPS servers exposed by the gateway. The server exposes configuration for TLS termination, request authentication/authorization, HTTP routing, etc.
     */
    https?: pulumi.Input<pulumi.Input<inputs.GatewayIngressGatewayHttp>[] | undefined>;
    /**
     * Short name of the IngressGateway resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the IngressGateway resource.
     */
    parent: pulumi.Input<string>;
    /**
     * One or more non-HTTP and non-passthrough servers which use TCP based protocols. This server also exposes configuration for terminating TLS
     */
    tcps?: pulumi.Input<pulumi.Input<inputs.GatewayIngressGatewayTcp>[] | undefined>;
    /**
     * One or more TLS servers exposed by the gateway. The server does not terminate TLS and exposes config for SNI based routing.
     */
    tlsPassthroughs?: pulumi.Input<pulumi.Input<inputs.GatewayIngressGatewayTlsPassthrough>[] | undefined>;
    /**
     * WAF settings to be enabled for traffic passing through the HttpServer.
     */
    waf?: pulumi.Input<inputs.GatewayIngressGatewayWaf | undefined>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    workloadSelector: pulumi.Input<inputs.GatewayIngressGatewayWorkloadSelector>;
}
