// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class GatewaySharedGatewayReferenceGrant extends pulumi.CustomResource {
    /**
     * Get an existing GatewaySharedGatewayReferenceGrant resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GatewaySharedGatewayReferenceGrantState, opts?: pulumi.CustomResourceOptions): GatewaySharedGatewayReferenceGrant {
        return new GatewaySharedGatewayReferenceGrant(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:index/gatewaySharedGatewayReferenceGrant:GatewaySharedGatewayReferenceGrant';

    /**
     * Returns true if the given object is an instance of GatewaySharedGatewayReferenceGrant.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GatewaySharedGatewayReferenceGrant {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GatewaySharedGatewayReferenceGrant.__pulumiType;
    }

    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * The fully-qualified name of the resource that is being granted access to the shared Gateway. This can be a Tenant, Workspace or a Gateway Group.
     */
    declare public readonly from: pulumi.Output<outputs.GatewaySharedGatewayReferenceGrantFrom>;
    /**
     * A list of Gateway Selectors that specify which Gateways are being shared.
     */
    declare public readonly gatewaySelectors: pulumi.Output<outputs.GatewaySharedGatewayReferenceGrantGatewaySelector[]>;
    /**
     * Short name of the SharedGatewayReferenceGrant resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the SharedGatewayReferenceGrant resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * When set, prevents the resource from being deleted or updated. In order to delete or update the resource this property needs to be set to `false` first.
     */
    declare public readonly updateProtectionEnabled: pulumi.Output<boolean>;

    /**
     * Create a GatewaySharedGatewayReferenceGrant resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GatewaySharedGatewayReferenceGrantArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GatewaySharedGatewayReferenceGrantArgs | GatewaySharedGatewayReferenceGrantState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GatewaySharedGatewayReferenceGrantState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["from"] = state?.from;
            resourceInputs["gatewaySelectors"] = state?.gatewaySelectors;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["updateProtectionEnabled"] = state?.updateProtectionEnabled;
        } else {
            const args = argsOrState as GatewaySharedGatewayReferenceGrantArgs | undefined;
            if (args?.from === undefined && !opts.urn) {
                throw new Error("Missing required property 'from'");
            }
            if (args?.gatewaySelectors === undefined && !opts.urn) {
                throw new Error("Missing required property 'gatewaySelectors'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["from"] = args?.from;
            resourceInputs["gatewaySelectors"] = args?.gatewaySelectors;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["updateProtectionEnabled"] = args?.updateProtectionEnabled;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GatewaySharedGatewayReferenceGrant.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GatewaySharedGatewayReferenceGrant resources.
 */
export interface GatewaySharedGatewayReferenceGrantState {
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * The fully-qualified name of the resource that is being granted access to the shared Gateway. This can be a Tenant, Workspace or a Gateway Group.
     */
    from?: pulumi.Input<inputs.GatewaySharedGatewayReferenceGrantFrom | undefined>;
    /**
     * A list of Gateway Selectors that specify which Gateways are being shared.
     */
    gatewaySelectors?: pulumi.Input<pulumi.Input<inputs.GatewaySharedGatewayReferenceGrantGatewaySelector>[] | undefined>;
    /**
     * Short name of the SharedGatewayReferenceGrant resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the SharedGatewayReferenceGrant resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * When set, prevents the resource from being deleted or updated. In order to delete or update the resource this property needs to be set to `false` first.
     */
    updateProtectionEnabled?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a GatewaySharedGatewayReferenceGrant resource.
 */
export interface GatewaySharedGatewayReferenceGrantArgs {
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * The fully-qualified name of the resource that is being granted access to the shared Gateway. This can be a Tenant, Workspace or a Gateway Group.
     */
    from: pulumi.Input<inputs.GatewaySharedGatewayReferenceGrantFrom>;
    /**
     * A list of Gateway Selectors that specify which Gateways are being shared.
     */
    gatewaySelectors: pulumi.Input<pulumi.Input<inputs.GatewaySharedGatewayReferenceGrantGatewaySelector>[]>;
    /**
     * Short name of the SharedGatewayReferenceGrant resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the SharedGatewayReferenceGrant resource.
     */
    parent: pulumi.Input<string>;
    /**
     * When set, prevents the resource from being deleted or updated. In order to delete or update the resource this property needs to be set to `false` first.
     */
    updateProtectionEnabled?: pulumi.Input<boolean | undefined>;
}
