// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AccessBindingArgs, AccessBindingState } from "./accessBinding";
export type AccessBinding = import("./accessBinding").AccessBinding;
export const AccessBinding: typeof import("./accessBinding").AccessBinding = null as any;
utilities.lazyLoad(exports, ["AccessBinding"], () => require("./accessBinding"));

export { ApiArgs, ApiState } from "./api";
export type Api = import("./api").Api;
export const Api: typeof import("./api").Api = null as any;
utilities.lazyLoad(exports, ["Api"], () => require("./api"));

export { ClusterArgs, ClusterState } from "./cluster";
export type Cluster = import("./cluster").Cluster;
export const Cluster: typeof import("./cluster").Cluster = null as any;
utilities.lazyLoad(exports, ["Cluster"], () => require("./cluster"));

export { ClusterOnboardingConfigArgs, ClusterOnboardingConfigState } from "./clusterOnboardingConfig";
export type ClusterOnboardingConfig = import("./clusterOnboardingConfig").ClusterOnboardingConfig;
export const ClusterOnboardingConfig: typeof import("./clusterOnboardingConfig").ClusterOnboardingConfig = null as any;
utilities.lazyLoad(exports, ["ClusterOnboardingConfig"], () => require("./clusterOnboardingConfig"));

export { OidcArgs, OidcState } from "./oidc";
export type Oidc = import("./oidc").Oidc;
export const Oidc: typeof import("./oidc").Oidc = null as any;
utilities.lazyLoad(exports, ["Oidc"], () => require("./oidc"));

export { OrganizationArgs, OrganizationState } from "./organization";
export type Organization = import("./organization").Organization;
export const Organization: typeof import("./organization").Organization = null as any;
utilities.lazyLoad(exports, ["Organization"], () => require("./organization"));

export { OrganizationSettingArgs, OrganizationSettingState } from "./organizationSetting";
export type OrganizationSetting = import("./organizationSetting").OrganizationSetting;
export const OrganizationSetting: typeof import("./organizationSetting").OrganizationSetting = null as any;
utilities.lazyLoad(exports, ["OrganizationSetting"], () => require("./organizationSetting"));

export * from "./provider";
import { Provider } from "./provider";

export { ServiceAccountArgs, ServiceAccountState } from "./serviceAccount";
export type ServiceAccount = import("./serviceAccount").ServiceAccount;
export const ServiceAccount: typeof import("./serviceAccount").ServiceAccount = null as any;
utilities.lazyLoad(exports, ["ServiceAccount"], () => require("./serviceAccount"));

export { TeamArgs, TeamState } from "./team";
export type Team = import("./team").Team;
export const Team: typeof import("./team").Team = null as any;
utilities.lazyLoad(exports, ["Team"], () => require("./team"));

export { TenantArgs, TenantState } from "./tenant";
export type Tenant = import("./tenant").Tenant;
export const Tenant: typeof import("./tenant").Tenant = null as any;
utilities.lazyLoad(exports, ["Tenant"], () => require("./tenant"));

export { TenantSettingArgs, TenantSettingState } from "./tenantSetting";
export type TenantSetting = import("./tenantSetting").TenantSetting;
export const TenantSetting: typeof import("./tenantSetting").TenantSetting = null as any;
utilities.lazyLoad(exports, ["TenantSetting"], () => require("./tenantSetting"));

export { UserArgs, UserState } from "./user";
export type User = import("./user").User;
export const User: typeof import("./user").User = null as any;
utilities.lazyLoad(exports, ["User"], () => require("./user"));

export { WorkspaceArgs, WorkspaceState } from "./workspace";
export type Workspace = import("./workspace").Workspace;
export const Workspace: typeof import("./workspace").Workspace = null as any;
utilities.lazyLoad(exports, ["Workspace"], () => require("./workspace"));

export { WorkspaceSettingArgs, WorkspaceSettingState } from "./workspaceSetting";
export type WorkspaceSetting = import("./workspaceSetting").WorkspaceSetting;
export const WorkspaceSetting: typeof import("./workspaceSetting").WorkspaceSetting = null as any;
utilities.lazyLoad(exports, ["WorkspaceSetting"], () => require("./workspaceSetting"));


// Export sub-modules:
import * as application from "./application";
import * as config from "./config";
import * as extension from "./extension";
import * as gateway from "./gateway";
import * as istiointernal from "./istiointernal";
import * as profile from "./profile";
import * as rbac from "./rbac";
import * as security from "./security";
import * as traffic from "./traffic";
import * as types from "./types";

export {
    application,
    config,
    extension,
    gateway,
    istiointernal,
    profile,
    rbac,
    security,
    traffic,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tsb:index/accessBinding:AccessBinding":
                return new AccessBinding(name, <any>undefined, { urn })
            case "tsb:index/api:Api":
                return new Api(name, <any>undefined, { urn })
            case "tsb:index/cluster:Cluster":
                return new Cluster(name, <any>undefined, { urn })
            case "tsb:index/clusterOnboardingConfig:ClusterOnboardingConfig":
                return new ClusterOnboardingConfig(name, <any>undefined, { urn })
            case "tsb:index/oidc:Oidc":
                return new Oidc(name, <any>undefined, { urn })
            case "tsb:index/organization:Organization":
                return new Organization(name, <any>undefined, { urn })
            case "tsb:index/organizationSetting:OrganizationSetting":
                return new OrganizationSetting(name, <any>undefined, { urn })
            case "tsb:index/serviceAccount:ServiceAccount":
                return new ServiceAccount(name, <any>undefined, { urn })
            case "tsb:index/team:Team":
                return new Team(name, <any>undefined, { urn })
            case "tsb:index/tenant:Tenant":
                return new Tenant(name, <any>undefined, { urn })
            case "tsb:index/tenantSetting:TenantSetting":
                return new TenantSetting(name, <any>undefined, { urn })
            case "tsb:index/user:User":
                return new User(name, <any>undefined, { urn })
            case "tsb:index/workspace:Workspace":
                return new Workspace(name, <any>undefined, { urn })
            case "tsb:index/workspaceSetting:WorkspaceSetting":
                return new WorkspaceSetting(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tsb", "index/accessBinding", _module)
pulumi.runtime.registerResourceModule("tsb", "index/api", _module)
pulumi.runtime.registerResourceModule("tsb", "index/cluster", _module)
pulumi.runtime.registerResourceModule("tsb", "index/clusterOnboardingConfig", _module)
pulumi.runtime.registerResourceModule("tsb", "index/oidc", _module)
pulumi.runtime.registerResourceModule("tsb", "index/organization", _module)
pulumi.runtime.registerResourceModule("tsb", "index/organizationSetting", _module)
pulumi.runtime.registerResourceModule("tsb", "index/serviceAccount", _module)
pulumi.runtime.registerResourceModule("tsb", "index/team", _module)
pulumi.runtime.registerResourceModule("tsb", "index/tenant", _module)
pulumi.runtime.registerResourceModule("tsb", "index/tenantSetting", _module)
pulumi.runtime.registerResourceModule("tsb", "index/user", _module)
pulumi.runtime.registerResourceModule("tsb", "index/workspace", _module)
pulumi.runtime.registerResourceModule("tsb", "index/workspaceSetting", _module)
pulumi.runtime.registerResourcePackage("tsb", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:tsb") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
