// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AccessBindingArgs, AccessBindingState } from "./accessBinding";
export type AccessBinding = import("./accessBinding").AccessBinding;
export const AccessBinding: typeof import("./accessBinding").AccessBinding = null as any;
utilities.lazyLoad(exports, ["AccessBinding"], () => require("./accessBinding"));

export { ApiArgs, ApiState } from "./api";
export type Api = import("./api").Api;
export const Api: typeof import("./api").Api = null as any;
utilities.lazyLoad(exports, ["Api"], () => require("./api"));

export { ApplicationApiArgs, ApplicationApiState } from "./applicationApi";
export type ApplicationApi = import("./applicationApi").ApplicationApi;
export const ApplicationApi: typeof import("./applicationApi").ApplicationApi = null as any;
utilities.lazyLoad(exports, ["ApplicationApi"], () => require("./applicationApi"));

export { ApplicationApplicationArgs, ApplicationApplicationState } from "./applicationApplication";
export type ApplicationApplication = import("./applicationApplication").ApplicationApplication;
export const ApplicationApplication: typeof import("./applicationApplication").ApplicationApplication = null as any;
utilities.lazyLoad(exports, ["ApplicationApplication"], () => require("./applicationApplication"));

export { ClusterArgs, ClusterState } from "./cluster";
export type Cluster = import("./cluster").Cluster;
export const Cluster: typeof import("./cluster").Cluster = null as any;
utilities.lazyLoad(exports, ["Cluster"], () => require("./cluster"));

export { ClusterOnboardingConfigArgs, ClusterOnboardingConfigState } from "./clusterOnboardingConfig";
export type ClusterOnboardingConfig = import("./clusterOnboardingConfig").ClusterOnboardingConfig;
export const ClusterOnboardingConfig: typeof import("./clusterOnboardingConfig").ClusterOnboardingConfig = null as any;
utilities.lazyLoad(exports, ["ClusterOnboardingConfig"], () => require("./clusterOnboardingConfig"));

export { ExtensionWasmExtensionArgs, ExtensionWasmExtensionState } from "./extensionWasmExtension";
export type ExtensionWasmExtension = import("./extensionWasmExtension").ExtensionWasmExtension;
export const ExtensionWasmExtension: typeof import("./extensionWasmExtension").ExtensionWasmExtension = null as any;
utilities.lazyLoad(exports, ["ExtensionWasmExtension"], () => require("./extensionWasmExtension"));

export { GatewayEgressGatewayArgs, GatewayEgressGatewayState } from "./gatewayEgressGateway";
export type GatewayEgressGateway = import("./gatewayEgressGateway").GatewayEgressGateway;
export const GatewayEgressGateway: typeof import("./gatewayEgressGateway").GatewayEgressGateway = null as any;
utilities.lazyLoad(exports, ["GatewayEgressGateway"], () => require("./gatewayEgressGateway"));

export { GatewayGatewayArgs, GatewayGatewayState } from "./gatewayGateway";
export type GatewayGateway = import("./gatewayGateway").GatewayGateway;
export const GatewayGateway: typeof import("./gatewayGateway").GatewayGateway = null as any;
utilities.lazyLoad(exports, ["GatewayGateway"], () => require("./gatewayGateway"));

export { GatewayGroupArgs, GatewayGroupState } from "./gatewayGroup";
export type GatewayGroup = import("./gatewayGroup").GatewayGroup;
export const GatewayGroup: typeof import("./gatewayGroup").GatewayGroup = null as any;
utilities.lazyLoad(exports, ["GatewayGroup"], () => require("./gatewayGroup"));

export { GatewayIngressGatewayArgs, GatewayIngressGatewayState } from "./gatewayIngressGateway";
export type GatewayIngressGateway = import("./gatewayIngressGateway").GatewayIngressGateway;
export const GatewayIngressGateway: typeof import("./gatewayIngressGateway").GatewayIngressGateway = null as any;
utilities.lazyLoad(exports, ["GatewayIngressGateway"], () => require("./gatewayIngressGateway"));

export { GatewayInstallGatewayArgs, GatewayInstallGatewayState } from "./gatewayInstallGateway";
export type GatewayInstallGateway = import("./gatewayInstallGateway").GatewayInstallGateway;
export const GatewayInstallGateway: typeof import("./gatewayInstallGateway").GatewayInstallGateway = null as any;
utilities.lazyLoad(exports, ["GatewayInstallGateway"], () => require("./gatewayInstallGateway"));

export { GatewayInstallGatewayTemplateArgs, GatewayInstallGatewayTemplateState } from "./gatewayInstallGatewayTemplate";
export type GatewayInstallGatewayTemplate = import("./gatewayInstallGatewayTemplate").GatewayInstallGatewayTemplate;
export const GatewayInstallGatewayTemplate: typeof import("./gatewayInstallGatewayTemplate").GatewayInstallGatewayTemplate = null as any;
utilities.lazyLoad(exports, ["GatewayInstallGatewayTemplate"], () => require("./gatewayInstallGatewayTemplate"));

export { GatewaySharedGatewayReferenceGrantArgs, GatewaySharedGatewayReferenceGrantState } from "./gatewaySharedGatewayReferenceGrant";
export type GatewaySharedGatewayReferenceGrant = import("./gatewaySharedGatewayReferenceGrant").GatewaySharedGatewayReferenceGrant;
export const GatewaySharedGatewayReferenceGrant: typeof import("./gatewaySharedGatewayReferenceGrant").GatewaySharedGatewayReferenceGrant = null as any;
utilities.lazyLoad(exports, ["GatewaySharedGatewayReferenceGrant"], () => require("./gatewaySharedGatewayReferenceGrant"));

export { GatewayTier1GatewayArgs, GatewayTier1GatewayState } from "./gatewayTier1Gateway";
export type GatewayTier1Gateway = import("./gatewayTier1Gateway").GatewayTier1Gateway;
export const GatewayTier1Gateway: typeof import("./gatewayTier1Gateway").GatewayTier1Gateway = null as any;
utilities.lazyLoad(exports, ["GatewayTier1Gateway"], () => require("./gatewayTier1Gateway"));

export { IstioGatewayAuthorizationPolicyArgs, IstioGatewayAuthorizationPolicyState } from "./istioGatewayAuthorizationPolicy";
export type IstioGatewayAuthorizationPolicy = import("./istioGatewayAuthorizationPolicy").IstioGatewayAuthorizationPolicy;
export const IstioGatewayAuthorizationPolicy: typeof import("./istioGatewayAuthorizationPolicy").IstioGatewayAuthorizationPolicy = null as any;
utilities.lazyLoad(exports, ["IstioGatewayAuthorizationPolicy"], () => require("./istioGatewayAuthorizationPolicy"));

export { IstioGatewayGatewayArgs, IstioGatewayGatewayState } from "./istioGatewayGateway";
export type IstioGatewayGateway = import("./istioGatewayGateway").IstioGatewayGateway;
export const IstioGatewayGateway: typeof import("./istioGatewayGateway").IstioGatewayGateway = null as any;
utilities.lazyLoad(exports, ["IstioGatewayGateway"], () => require("./istioGatewayGateway"));

export { IstioGatewayRequestAuthenticationArgs, IstioGatewayRequestAuthenticationState } from "./istioGatewayRequestAuthentication";
export type IstioGatewayRequestAuthentication = import("./istioGatewayRequestAuthentication").IstioGatewayRequestAuthentication;
export const IstioGatewayRequestAuthentication: typeof import("./istioGatewayRequestAuthentication").IstioGatewayRequestAuthentication = null as any;
utilities.lazyLoad(exports, ["IstioGatewayRequestAuthentication"], () => require("./istioGatewayRequestAuthentication"));

export { IstioGatewayVirtualServiceArgs, IstioGatewayVirtualServiceState } from "./istioGatewayVirtualService";
export type IstioGatewayVirtualService = import("./istioGatewayVirtualService").IstioGatewayVirtualService;
export const IstioGatewayVirtualService: typeof import("./istioGatewayVirtualService").IstioGatewayVirtualService = null as any;
utilities.lazyLoad(exports, ["IstioGatewayVirtualService"], () => require("./istioGatewayVirtualService"));

export { IstioInternalDirectEnvoyFilterArgs, IstioInternalDirectEnvoyFilterState } from "./istioInternalDirectEnvoyFilter";
export type IstioInternalDirectEnvoyFilter = import("./istioInternalDirectEnvoyFilter").IstioInternalDirectEnvoyFilter;
export const IstioInternalDirectEnvoyFilter: typeof import("./istioInternalDirectEnvoyFilter").IstioInternalDirectEnvoyFilter = null as any;
utilities.lazyLoad(exports, ["IstioInternalDirectEnvoyFilter"], () => require("./istioInternalDirectEnvoyFilter"));

export { IstioInternalDirectServiceEntryArgs, IstioInternalDirectServiceEntryState } from "./istioInternalDirectServiceEntry";
export type IstioInternalDirectServiceEntry = import("./istioInternalDirectServiceEntry").IstioInternalDirectServiceEntry;
export const IstioInternalDirectServiceEntry: typeof import("./istioInternalDirectServiceEntry").IstioInternalDirectServiceEntry = null as any;
utilities.lazyLoad(exports, ["IstioInternalDirectServiceEntry"], () => require("./istioInternalDirectServiceEntry"));

export { IstioInternalDirectWasmPluginArgs, IstioInternalDirectWasmPluginState } from "./istioInternalDirectWasmPlugin";
export type IstioInternalDirectWasmPlugin = import("./istioInternalDirectWasmPlugin").IstioInternalDirectWasmPlugin;
export const IstioInternalDirectWasmPlugin: typeof import("./istioInternalDirectWasmPlugin").IstioInternalDirectWasmPlugin = null as any;
utilities.lazyLoad(exports, ["IstioInternalDirectWasmPlugin"], () => require("./istioInternalDirectWasmPlugin"));

export { IstioSecurityAuthorizationPolicyArgs, IstioSecurityAuthorizationPolicyState } from "./istioSecurityAuthorizationPolicy";
export type IstioSecurityAuthorizationPolicy = import("./istioSecurityAuthorizationPolicy").IstioSecurityAuthorizationPolicy;
export const IstioSecurityAuthorizationPolicy: typeof import("./istioSecurityAuthorizationPolicy").IstioSecurityAuthorizationPolicy = null as any;
utilities.lazyLoad(exports, ["IstioSecurityAuthorizationPolicy"], () => require("./istioSecurityAuthorizationPolicy"));

export { IstioSecurityPeerAuthenticationArgs, IstioSecurityPeerAuthenticationState } from "./istioSecurityPeerAuthentication";
export type IstioSecurityPeerAuthentication = import("./istioSecurityPeerAuthentication").IstioSecurityPeerAuthentication;
export const IstioSecurityPeerAuthentication: typeof import("./istioSecurityPeerAuthentication").IstioSecurityPeerAuthentication = null as any;
utilities.lazyLoad(exports, ["IstioSecurityPeerAuthentication"], () => require("./istioSecurityPeerAuthentication"));

export { IstioSecurityRequestAuthenticationArgs, IstioSecurityRequestAuthenticationState } from "./istioSecurityRequestAuthentication";
export type IstioSecurityRequestAuthentication = import("./istioSecurityRequestAuthentication").IstioSecurityRequestAuthentication;
export const IstioSecurityRequestAuthentication: typeof import("./istioSecurityRequestAuthentication").IstioSecurityRequestAuthentication = null as any;
utilities.lazyLoad(exports, ["IstioSecurityRequestAuthentication"], () => require("./istioSecurityRequestAuthentication"));

export { IstioTrafficDestinationRuleArgs, IstioTrafficDestinationRuleState } from "./istioTrafficDestinationRule";
export type IstioTrafficDestinationRule = import("./istioTrafficDestinationRule").IstioTrafficDestinationRule;
export const IstioTrafficDestinationRule: typeof import("./istioTrafficDestinationRule").IstioTrafficDestinationRule = null as any;
utilities.lazyLoad(exports, ["IstioTrafficDestinationRule"], () => require("./istioTrafficDestinationRule"));

export { IstioTrafficSidecarArgs, IstioTrafficSidecarState } from "./istioTrafficSidecar";
export type IstioTrafficSidecar = import("./istioTrafficSidecar").IstioTrafficSidecar;
export const IstioTrafficSidecar: typeof import("./istioTrafficSidecar").IstioTrafficSidecar = null as any;
utilities.lazyLoad(exports, ["IstioTrafficSidecar"], () => require("./istioTrafficSidecar"));

export { IstioTrafficVirtualServiceArgs, IstioTrafficVirtualServiceState } from "./istioTrafficVirtualService";
export type IstioTrafficVirtualService = import("./istioTrafficVirtualService").IstioTrafficVirtualService;
export const IstioTrafficVirtualService: typeof import("./istioTrafficVirtualService").IstioTrafficVirtualService = null as any;
utilities.lazyLoad(exports, ["IstioTrafficVirtualService"], () => require("./istioTrafficVirtualService"));

export { IstiointernalGroupArgs, IstiointernalGroupState } from "./istiointernalGroup";
export type IstiointernalGroup = import("./istiointernalGroup").IstiointernalGroup;
export const IstiointernalGroup: typeof import("./istiointernalGroup").IstiointernalGroup = null as any;
utilities.lazyLoad(exports, ["IstiointernalGroup"], () => require("./istiointernalGroup"));

export { OidcArgs, OidcState } from "./oidc";
export type Oidc = import("./oidc").Oidc;
export const Oidc: typeof import("./oidc").Oidc = null as any;
utilities.lazyLoad(exports, ["Oidc"], () => require("./oidc"));

export { OrganizationArgs, OrganizationState } from "./organization";
export type Organization = import("./organization").Organization;
export const Organization: typeof import("./organization").Organization = null as any;
utilities.lazyLoad(exports, ["Organization"], () => require("./organization"));

export { OrganizationSettingArgs, OrganizationSettingState } from "./organizationSetting";
export type OrganizationSetting = import("./organizationSetting").OrganizationSetting;
export const OrganizationSetting: typeof import("./organizationSetting").OrganizationSetting = null as any;
utilities.lazyLoad(exports, ["OrganizationSetting"], () => require("./organizationSetting"));

export { ProfileProfileArgs, ProfileProfileState } from "./profileProfile";
export type ProfileProfile = import("./profileProfile").ProfileProfile;
export const ProfileProfile: typeof import("./profileProfile").ProfileProfile = null as any;
utilities.lazyLoad(exports, ["ProfileProfile"], () => require("./profileProfile"));

export * from "./provider";
import { Provider } from "./provider";

export { RbacRoleArgs, RbacRoleState } from "./rbacRole";
export type RbacRole = import("./rbacRole").RbacRole;
export const RbacRole: typeof import("./rbacRole").RbacRole = null as any;
utilities.lazyLoad(exports, ["RbacRole"], () => require("./rbacRole"));

export { SecurityGroupArgs, SecurityGroupState } from "./securityGroup";
export type SecurityGroup = import("./securityGroup").SecurityGroup;
export const SecurityGroup: typeof import("./securityGroup").SecurityGroup = null as any;
utilities.lazyLoad(exports, ["SecurityGroup"], () => require("./securityGroup"));

export { SecuritySecuritySettingArgs, SecuritySecuritySettingState } from "./securitySecuritySetting";
export type SecuritySecuritySetting = import("./securitySecuritySetting").SecuritySecuritySetting;
export const SecuritySecuritySetting: typeof import("./securitySecuritySetting").SecuritySecuritySetting = null as any;
utilities.lazyLoad(exports, ["SecuritySecuritySetting"], () => require("./securitySecuritySetting"));

export { SecurityServiceSecuritySettingArgs, SecurityServiceSecuritySettingState } from "./securityServiceSecuritySetting";
export type SecurityServiceSecuritySetting = import("./securityServiceSecuritySetting").SecurityServiceSecuritySetting;
export const SecurityServiceSecuritySetting: typeof import("./securityServiceSecuritySetting").SecurityServiceSecuritySetting = null as any;
utilities.lazyLoad(exports, ["SecurityServiceSecuritySetting"], () => require("./securityServiceSecuritySetting"));

export { ServiceAccountArgs, ServiceAccountState } from "./serviceAccount";
export type ServiceAccount = import("./serviceAccount").ServiceAccount;
export const ServiceAccount: typeof import("./serviceAccount").ServiceAccount = null as any;
utilities.lazyLoad(exports, ["ServiceAccount"], () => require("./serviceAccount"));

export { TeamArgs, TeamState } from "./team";
export type Team = import("./team").Team;
export const Team: typeof import("./team").Team = null as any;
utilities.lazyLoad(exports, ["Team"], () => require("./team"));

export { TenantArgs, TenantState } from "./tenant";
export type Tenant = import("./tenant").Tenant;
export const Tenant: typeof import("./tenant").Tenant = null as any;
utilities.lazyLoad(exports, ["Tenant"], () => require("./tenant"));

export { TenantSettingArgs, TenantSettingState } from "./tenantSetting";
export type TenantSetting = import("./tenantSetting").TenantSetting;
export const TenantSetting: typeof import("./tenantSetting").TenantSetting = null as any;
utilities.lazyLoad(exports, ["TenantSetting"], () => require("./tenantSetting"));

export { TrafficGroupArgs, TrafficGroupState } from "./trafficGroup";
export type TrafficGroup = import("./trafficGroup").TrafficGroup;
export const TrafficGroup: typeof import("./trafficGroup").TrafficGroup = null as any;
utilities.lazyLoad(exports, ["TrafficGroup"], () => require("./trafficGroup"));

export { TrafficServiceRouteArgs, TrafficServiceRouteState } from "./trafficServiceRoute";
export type TrafficServiceRoute = import("./trafficServiceRoute").TrafficServiceRoute;
export const TrafficServiceRoute: typeof import("./trafficServiceRoute").TrafficServiceRoute = null as any;
utilities.lazyLoad(exports, ["TrafficServiceRoute"], () => require("./trafficServiceRoute"));

export { TrafficServiceTrafficSettingArgs, TrafficServiceTrafficSettingState } from "./trafficServiceTrafficSetting";
export type TrafficServiceTrafficSetting = import("./trafficServiceTrafficSetting").TrafficServiceTrafficSetting;
export const TrafficServiceTrafficSetting: typeof import("./trafficServiceTrafficSetting").TrafficServiceTrafficSetting = null as any;
utilities.lazyLoad(exports, ["TrafficServiceTrafficSetting"], () => require("./trafficServiceTrafficSetting"));

export { TrafficTrafficSettingArgs, TrafficTrafficSettingState } from "./trafficTrafficSetting";
export type TrafficTrafficSetting = import("./trafficTrafficSetting").TrafficTrafficSetting;
export const TrafficTrafficSetting: typeof import("./trafficTrafficSetting").TrafficTrafficSetting = null as any;
utilities.lazyLoad(exports, ["TrafficTrafficSetting"], () => require("./trafficTrafficSetting"));

export { UserArgs, UserState } from "./user";
export type User = import("./user").User;
export const User: typeof import("./user").User = null as any;
utilities.lazyLoad(exports, ["User"], () => require("./user"));

export { WorkspaceArgs, WorkspaceState } from "./workspace";
export type Workspace = import("./workspace").Workspace;
export const Workspace: typeof import("./workspace").Workspace = null as any;
utilities.lazyLoad(exports, ["Workspace"], () => require("./workspace"));

export { WorkspaceSettingArgs, WorkspaceSettingState } from "./workspaceSetting";
export type WorkspaceSetting = import("./workspaceSetting").WorkspaceSetting;
export const WorkspaceSetting: typeof import("./workspaceSetting").WorkspaceSetting = null as any;
utilities.lazyLoad(exports, ["WorkspaceSetting"], () => require("./workspaceSetting"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tsb:index/accessBinding:AccessBinding":
                return new AccessBinding(name, <any>undefined, { urn })
            case "tsb:index/api:Api":
                return new Api(name, <any>undefined, { urn })
            case "tsb:index/applicationApi:ApplicationApi":
                return new ApplicationApi(name, <any>undefined, { urn })
            case "tsb:index/applicationApplication:ApplicationApplication":
                return new ApplicationApplication(name, <any>undefined, { urn })
            case "tsb:index/cluster:Cluster":
                return new Cluster(name, <any>undefined, { urn })
            case "tsb:index/clusterOnboardingConfig:ClusterOnboardingConfig":
                return new ClusterOnboardingConfig(name, <any>undefined, { urn })
            case "tsb:index/extensionWasmExtension:ExtensionWasmExtension":
                return new ExtensionWasmExtension(name, <any>undefined, { urn })
            case "tsb:index/gatewayEgressGateway:GatewayEgressGateway":
                return new GatewayEgressGateway(name, <any>undefined, { urn })
            case "tsb:index/gatewayGateway:GatewayGateway":
                return new GatewayGateway(name, <any>undefined, { urn })
            case "tsb:index/gatewayGroup:GatewayGroup":
                return new GatewayGroup(name, <any>undefined, { urn })
            case "tsb:index/gatewayIngressGateway:GatewayIngressGateway":
                return new GatewayIngressGateway(name, <any>undefined, { urn })
            case "tsb:index/gatewayInstallGateway:GatewayInstallGateway":
                return new GatewayInstallGateway(name, <any>undefined, { urn })
            case "tsb:index/gatewayInstallGatewayTemplate:GatewayInstallGatewayTemplate":
                return new GatewayInstallGatewayTemplate(name, <any>undefined, { urn })
            case "tsb:index/gatewaySharedGatewayReferenceGrant:GatewaySharedGatewayReferenceGrant":
                return new GatewaySharedGatewayReferenceGrant(name, <any>undefined, { urn })
            case "tsb:index/gatewayTier1Gateway:GatewayTier1Gateway":
                return new GatewayTier1Gateway(name, <any>undefined, { urn })
            case "tsb:index/istioGatewayAuthorizationPolicy:IstioGatewayAuthorizationPolicy":
                return new IstioGatewayAuthorizationPolicy(name, <any>undefined, { urn })
            case "tsb:index/istioGatewayGateway:IstioGatewayGateway":
                return new IstioGatewayGateway(name, <any>undefined, { urn })
            case "tsb:index/istioGatewayRequestAuthentication:IstioGatewayRequestAuthentication":
                return new IstioGatewayRequestAuthentication(name, <any>undefined, { urn })
            case "tsb:index/istioGatewayVirtualService:IstioGatewayVirtualService":
                return new IstioGatewayVirtualService(name, <any>undefined, { urn })
            case "tsb:index/istioInternalDirectEnvoyFilter:IstioInternalDirectEnvoyFilter":
                return new IstioInternalDirectEnvoyFilter(name, <any>undefined, { urn })
            case "tsb:index/istioInternalDirectServiceEntry:IstioInternalDirectServiceEntry":
                return new IstioInternalDirectServiceEntry(name, <any>undefined, { urn })
            case "tsb:index/istioInternalDirectWasmPlugin:IstioInternalDirectWasmPlugin":
                return new IstioInternalDirectWasmPlugin(name, <any>undefined, { urn })
            case "tsb:index/istioSecurityAuthorizationPolicy:IstioSecurityAuthorizationPolicy":
                return new IstioSecurityAuthorizationPolicy(name, <any>undefined, { urn })
            case "tsb:index/istioSecurityPeerAuthentication:IstioSecurityPeerAuthentication":
                return new IstioSecurityPeerAuthentication(name, <any>undefined, { urn })
            case "tsb:index/istioSecurityRequestAuthentication:IstioSecurityRequestAuthentication":
                return new IstioSecurityRequestAuthentication(name, <any>undefined, { urn })
            case "tsb:index/istioTrafficDestinationRule:IstioTrafficDestinationRule":
                return new IstioTrafficDestinationRule(name, <any>undefined, { urn })
            case "tsb:index/istioTrafficSidecar:IstioTrafficSidecar":
                return new IstioTrafficSidecar(name, <any>undefined, { urn })
            case "tsb:index/istioTrafficVirtualService:IstioTrafficVirtualService":
                return new IstioTrafficVirtualService(name, <any>undefined, { urn })
            case "tsb:index/istiointernalGroup:IstiointernalGroup":
                return new IstiointernalGroup(name, <any>undefined, { urn })
            case "tsb:index/oidc:Oidc":
                return new Oidc(name, <any>undefined, { urn })
            case "tsb:index/organization:Organization":
                return new Organization(name, <any>undefined, { urn })
            case "tsb:index/organizationSetting:OrganizationSetting":
                return new OrganizationSetting(name, <any>undefined, { urn })
            case "tsb:index/profileProfile:ProfileProfile":
                return new ProfileProfile(name, <any>undefined, { urn })
            case "tsb:index/rbacRole:RbacRole":
                return new RbacRole(name, <any>undefined, { urn })
            case "tsb:index/securityGroup:SecurityGroup":
                return new SecurityGroup(name, <any>undefined, { urn })
            case "tsb:index/securitySecuritySetting:SecuritySecuritySetting":
                return new SecuritySecuritySetting(name, <any>undefined, { urn })
            case "tsb:index/securityServiceSecuritySetting:SecurityServiceSecuritySetting":
                return new SecurityServiceSecuritySetting(name, <any>undefined, { urn })
            case "tsb:index/serviceAccount:ServiceAccount":
                return new ServiceAccount(name, <any>undefined, { urn })
            case "tsb:index/team:Team":
                return new Team(name, <any>undefined, { urn })
            case "tsb:index/tenant:Tenant":
                return new Tenant(name, <any>undefined, { urn })
            case "tsb:index/tenantSetting:TenantSetting":
                return new TenantSetting(name, <any>undefined, { urn })
            case "tsb:index/trafficGroup:TrafficGroup":
                return new TrafficGroup(name, <any>undefined, { urn })
            case "tsb:index/trafficServiceRoute:TrafficServiceRoute":
                return new TrafficServiceRoute(name, <any>undefined, { urn })
            case "tsb:index/trafficServiceTrafficSetting:TrafficServiceTrafficSetting":
                return new TrafficServiceTrafficSetting(name, <any>undefined, { urn })
            case "tsb:index/trafficTrafficSetting:TrafficTrafficSetting":
                return new TrafficTrafficSetting(name, <any>undefined, { urn })
            case "tsb:index/user:User":
                return new User(name, <any>undefined, { urn })
            case "tsb:index/workspace:Workspace":
                return new Workspace(name, <any>undefined, { urn })
            case "tsb:index/workspaceSetting:WorkspaceSetting":
                return new WorkspaceSetting(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tsb", "index/accessBinding", _module)
pulumi.runtime.registerResourceModule("tsb", "index/api", _module)
pulumi.runtime.registerResourceModule("tsb", "index/applicationApi", _module)
pulumi.runtime.registerResourceModule("tsb", "index/applicationApplication", _module)
pulumi.runtime.registerResourceModule("tsb", "index/cluster", _module)
pulumi.runtime.registerResourceModule("tsb", "index/clusterOnboardingConfig", _module)
pulumi.runtime.registerResourceModule("tsb", "index/extensionWasmExtension", _module)
pulumi.runtime.registerResourceModule("tsb", "index/gatewayEgressGateway", _module)
pulumi.runtime.registerResourceModule("tsb", "index/gatewayGateway", _module)
pulumi.runtime.registerResourceModule("tsb", "index/gatewayGroup", _module)
pulumi.runtime.registerResourceModule("tsb", "index/gatewayIngressGateway", _module)
pulumi.runtime.registerResourceModule("tsb", "index/gatewayInstallGateway", _module)
pulumi.runtime.registerResourceModule("tsb", "index/gatewayInstallGatewayTemplate", _module)
pulumi.runtime.registerResourceModule("tsb", "index/gatewaySharedGatewayReferenceGrant", _module)
pulumi.runtime.registerResourceModule("tsb", "index/gatewayTier1Gateway", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioGatewayAuthorizationPolicy", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioGatewayGateway", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioGatewayRequestAuthentication", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioGatewayVirtualService", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioInternalDirectEnvoyFilter", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioInternalDirectServiceEntry", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioInternalDirectWasmPlugin", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioSecurityAuthorizationPolicy", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioSecurityPeerAuthentication", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioSecurityRequestAuthentication", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioTrafficDestinationRule", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioTrafficSidecar", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istioTrafficVirtualService", _module)
pulumi.runtime.registerResourceModule("tsb", "index/istiointernalGroup", _module)
pulumi.runtime.registerResourceModule("tsb", "index/oidc", _module)
pulumi.runtime.registerResourceModule("tsb", "index/organization", _module)
pulumi.runtime.registerResourceModule("tsb", "index/organizationSetting", _module)
pulumi.runtime.registerResourceModule("tsb", "index/profileProfile", _module)
pulumi.runtime.registerResourceModule("tsb", "index/rbacRole", _module)
pulumi.runtime.registerResourceModule("tsb", "index/securityGroup", _module)
pulumi.runtime.registerResourceModule("tsb", "index/securitySecuritySetting", _module)
pulumi.runtime.registerResourceModule("tsb", "index/securityServiceSecuritySetting", _module)
pulumi.runtime.registerResourceModule("tsb", "index/serviceAccount", _module)
pulumi.runtime.registerResourceModule("tsb", "index/team", _module)
pulumi.runtime.registerResourceModule("tsb", "index/tenant", _module)
pulumi.runtime.registerResourceModule("tsb", "index/tenantSetting", _module)
pulumi.runtime.registerResourceModule("tsb", "index/trafficGroup", _module)
pulumi.runtime.registerResourceModule("tsb", "index/trafficServiceRoute", _module)
pulumi.runtime.registerResourceModule("tsb", "index/trafficServiceTrafficSetting", _module)
pulumi.runtime.registerResourceModule("tsb", "index/trafficTrafficSetting", _module)
pulumi.runtime.registerResourceModule("tsb", "index/user", _module)
pulumi.runtime.registerResourceModule("tsb", "index/workspace", _module)
pulumi.runtime.registerResourceModule("tsb", "index/workspaceSetting", _module)
pulumi.runtime.registerResourcePackage("tsb", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:tsb") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
