// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

export class OrganizationSetting extends pulumi.CustomResource {
    /**
     * Get an existing OrganizationSetting resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrganizationSettingState, opts?: pulumi.CustomResourceOptions): OrganizationSetting {
        return new OrganizationSetting(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:index/organizationSetting:OrganizationSetting';

    /**
     * Returns true if the given object is an instance of OrganizationSetting.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrganizationSetting {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrganizationSetting.__pulumiType;
    }

    /**
     * Security settings for all proxy workloads in this organization. This can be overridden at TenantSettings, WorkspaceSettings, or security group's SecuritySetting for specific cases. The override strategy used will be driven by the SecuritySetting propagation strategy. The default propagation strategy is `REPLACE`, in which a lower level SecuritySetting in the configuration hierarchy replaces a higher level SecuritySetting defined in the configuration hierarchy. For instance, a WorkspaceSettings defined SecuritySetting will replace any tenant or organization defined SecuritySetting. Proxy workloads without a specific security group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will accept connections from clients using Istio Mutual TLS as well as legacy clients using plaintext (i.e. any traffic not using Istio Mutual TLS authentication), i.e. authentication mode defaults to `OPTIONAL`. 2. No authorization will be performed, i.e., authorization mode defaults to `DISABLED`.
     */
    declare public readonly defaultSecuritySetting: pulumi.Output<outputs.OrganizationSettingDefaultSecuritySetting | undefined>;
    /**
     * Traffic settings for all proxy workloads in this organization. This can be overridden at TenantSettings or WorkspaceSettings for specific cases. Proxy workloads without a specific traffic group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will be able to reach any service in the cluster, i.e. reachability mode defaults to `CLUSTER`. 2. Traffic to unknown destinations will be directly routed from the sidecar to the destination.
     */
    declare public readonly defaultTrafficSetting: pulumi.Output<outputs.OrganizationSettingDefaultTrafficSetting | undefined>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Failover settings for all proxies connecting to a host exposed in this organization. Note that this is a server side setting.
     */
    declare public readonly failoverSettings: pulumi.Output<outputs.OrganizationSettingFailoverSettings | undefined>;
    /**
     * Short name of the OrganizationSetting resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Reachability between clusters on various networks.
     */
    declare public readonly networkSettings: pulumi.Output<outputs.OrganizationSettingNetworkSettings | undefined>;
    /**
     * The parent id for the OrganizationSetting resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * Default locality routing settings for all gateways. Please use FailoverSettings instead. If FailoverSettings is set, it takes precedence over this field. Explicitly specify the region traffic will land on when endpoints in local region becomes unhealthy. Should be used together with OutlierDetection to detect unhealthy endpoints. Note: if no OutlierDetection specified, this will not take effect.
     */
    declare public readonly regionalFailovers: pulumi.Output<outputs.OrganizationSettingRegionalFailover[] | undefined>;

    /**
     * Create a OrganizationSetting resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrganizationSettingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrganizationSettingArgs | OrganizationSettingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrganizationSettingState | undefined;
            resourceInputs["defaultSecuritySetting"] = state?.defaultSecuritySetting;
            resourceInputs["defaultTrafficSetting"] = state?.defaultTrafficSetting;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["failoverSettings"] = state?.failoverSettings;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkSettings"] = state?.networkSettings;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["regionalFailovers"] = state?.regionalFailovers;
        } else {
            const args = argsOrState as OrganizationSettingArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["defaultSecuritySetting"] = args?.defaultSecuritySetting;
            resourceInputs["defaultTrafficSetting"] = args?.defaultTrafficSetting;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["failoverSettings"] = args?.failoverSettings;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkSettings"] = args?.networkSettings;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["regionalFailovers"] = args?.regionalFailovers;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OrganizationSetting.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering OrganizationSetting resources.
 */
export interface OrganizationSettingState {
    /**
     * Security settings for all proxy workloads in this organization. This can be overridden at TenantSettings, WorkspaceSettings, or security group's SecuritySetting for specific cases. The override strategy used will be driven by the SecuritySetting propagation strategy. The default propagation strategy is `REPLACE`, in which a lower level SecuritySetting in the configuration hierarchy replaces a higher level SecuritySetting defined in the configuration hierarchy. For instance, a WorkspaceSettings defined SecuritySetting will replace any tenant or organization defined SecuritySetting. Proxy workloads without a specific security group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will accept connections from clients using Istio Mutual TLS as well as legacy clients using plaintext (i.e. any traffic not using Istio Mutual TLS authentication), i.e. authentication mode defaults to `OPTIONAL`. 2. No authorization will be performed, i.e., authorization mode defaults to `DISABLED`.
     */
    defaultSecuritySetting?: pulumi.Input<inputs.OrganizationSettingDefaultSecuritySetting | undefined>;
    /**
     * Traffic settings for all proxy workloads in this organization. This can be overridden at TenantSettings or WorkspaceSettings for specific cases. Proxy workloads without a specific traffic group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will be able to reach any service in the cluster, i.e. reachability mode defaults to `CLUSTER`. 2. Traffic to unknown destinations will be directly routed from the sidecar to the destination.
     */
    defaultTrafficSetting?: pulumi.Input<inputs.OrganizationSettingDefaultTrafficSetting | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Failover settings for all proxies connecting to a host exposed in this organization. Note that this is a server side setting.
     */
    failoverSettings?: pulumi.Input<inputs.OrganizationSettingFailoverSettings | undefined>;
    /**
     * Short name of the OrganizationSetting resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Reachability between clusters on various networks.
     */
    networkSettings?: pulumi.Input<inputs.OrganizationSettingNetworkSettings | undefined>;
    /**
     * The parent id for the OrganizationSetting resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * Default locality routing settings for all gateways. Please use FailoverSettings instead. If FailoverSettings is set, it takes precedence over this field. Explicitly specify the region traffic will land on when endpoints in local region becomes unhealthy. Should be used together with OutlierDetection to detect unhealthy endpoints. Note: if no OutlierDetection specified, this will not take effect.
     */
    regionalFailovers?: pulumi.Input<pulumi.Input<inputs.OrganizationSettingRegionalFailover>[] | undefined>;
}

/**
 * The set of arguments for constructing a OrganizationSetting resource.
 */
export interface OrganizationSettingArgs {
    /**
     * Security settings for all proxy workloads in this organization. This can be overridden at TenantSettings, WorkspaceSettings, or security group's SecuritySetting for specific cases. The override strategy used will be driven by the SecuritySetting propagation strategy. The default propagation strategy is `REPLACE`, in which a lower level SecuritySetting in the configuration hierarchy replaces a higher level SecuritySetting defined in the configuration hierarchy. For instance, a WorkspaceSettings defined SecuritySetting will replace any tenant or organization defined SecuritySetting. Proxy workloads without a specific security group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will accept connections from clients using Istio Mutual TLS as well as legacy clients using plaintext (i.e. any traffic not using Istio Mutual TLS authentication), i.e. authentication mode defaults to `OPTIONAL`. 2. No authorization will be performed, i.e., authorization mode defaults to `DISABLED`.
     */
    defaultSecuritySetting?: pulumi.Input<inputs.OrganizationSettingDefaultSecuritySetting | undefined>;
    /**
     * Traffic settings for all proxy workloads in this organization. This can be overridden at TenantSettings or WorkspaceSettings for specific cases. Proxy workloads without a specific traffic group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will be able to reach any service in the cluster, i.e. reachability mode defaults to `CLUSTER`. 2. Traffic to unknown destinations will be directly routed from the sidecar to the destination.
     */
    defaultTrafficSetting?: pulumi.Input<inputs.OrganizationSettingDefaultTrafficSetting | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Failover settings for all proxies connecting to a host exposed in this organization. Note that this is a server side setting.
     */
    failoverSettings?: pulumi.Input<inputs.OrganizationSettingFailoverSettings | undefined>;
    /**
     * Short name of the OrganizationSetting resource.
     */
    name: pulumi.Input<string>;
    /**
     * Reachability between clusters on various networks.
     */
    networkSettings?: pulumi.Input<inputs.OrganizationSettingNetworkSettings | undefined>;
    /**
     * The parent id for the OrganizationSetting resource.
     */
    parent: pulumi.Input<string>;
    /**
     * Default locality routing settings for all gateways. Please use FailoverSettings instead. If FailoverSettings is set, it takes precedence over this field. Explicitly specify the region traffic will land on when endpoints in local region becomes unhealthy. Should be used together with OutlierDetection to detect unhealthy endpoints. Note: if no OutlierDetection specified, this will not take effect.
     */
    regionalFailovers?: pulumi.Input<pulumi.Input<inputs.OrganizationSettingRegionalFailover>[] | undefined>;
}
