// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the tsb package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'tsb';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Path to a PEM CA bundle used to verify the TSB server certificate. May also be set via the TSB_CA_FILE environment variable.
     */
    declare public readonly caFile: pulumi.Output<string | undefined>;
    /**
     * TSB gRPC endpoint (host:port). May also be set via the TSB_ENDPOINT environment variable.
     */
    declare public readonly endpoint: pulumi.Output<string | undefined>;
    /**
     * TSB organization the resources belong to. May also be set via the TSB_ORG environment variable.
     */
    declare public readonly organization: pulumi.Output<string | undefined>;
    /**
     * Password for HTTP Basic authentication, used together with `username`. May also be set via the TSB_PASSWORD environment variable.
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * TSB API token sent in the x-tetrate-token header. Takes precedence over username/password. May also be set via the TSB_TOKEN environment variable.
     */
    declare public readonly token: pulumi.Output<string | undefined>;
    /**
     * Username for HTTP Basic authentication, used when `token` is not set. May also be set via the TSB_USERNAME environment variable.
     */
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["caFile"] = args?.caFile;
            resourceInputs["endpoint"] = args?.endpoint;
            resourceInputs["organization"] = args?.organization;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["tlsDisabled"] = pulumi.output(args?.tlsDisabled).apply(JSON.stringify);
            resourceInputs["tlsInsecure"] = pulumi.output(args?.tlsInsecure).apply(JSON.stringify);
            resourceInputs["token"] = args?.token ? pulumi.secret(args.token) : undefined;
            resourceInputs["username"] = args?.username;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password", "token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }

    /**
     * This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
     */
    terraformConfig(): pulumi.Output<Provider.TerraformConfigResult> {
        return pulumi.runtime.call("pulumi:providers:tsb/terraformConfig", {
            "__self__": this,
        }, this);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Path to a PEM CA bundle used to verify the TSB server certificate. May also be set via the TSB_CA_FILE environment variable.
     */
    caFile?: pulumi.Input<string | undefined>;
    /**
     * TSB gRPC endpoint (host:port). May also be set via the TSB_ENDPOINT environment variable.
     */
    endpoint?: pulumi.Input<string | undefined>;
    /**
     * TSB organization the resources belong to. May also be set via the TSB_ORG environment variable.
     */
    organization?: pulumi.Input<string | undefined>;
    /**
     * Password for HTTP Basic authentication, used together with `username`. May also be set via the TSB_PASSWORD environment variable.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * Disable transport security entirely (plaintext). May also be set via the TSB_TLS_DISABLED environment variable.
     */
    tlsDisabled?: pulumi.Input<boolean | undefined>;
    /**
     * Keep TLS enabled but skip server certificate verification. May also be set via the TSB_TLS_INSECURE environment variable.
     */
    tlsInsecure?: pulumi.Input<boolean | undefined>;
    /**
     * TSB API token sent in the x-tetrate-token header. Takes precedence over username/password. May also be set via the TSB_TOKEN environment variable.
     */
    token?: pulumi.Input<string | undefined>;
    /**
     * Username for HTTP Basic authentication, used when `token` is not set. May also be set via the TSB_USERNAME environment variable.
     */
    username?: pulumi.Input<string | undefined>;
}

export namespace Provider {
    /**
     * The results of the Provider.terraformConfig method.
     */
    export interface TerraformConfigResult {
        readonly result: {[key: string]: any};
    }

}
