// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class SecurityGroup extends pulumi.CustomResource {
    /**
     * Get an existing SecurityGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecurityGroupState, opts?: pulumi.CustomResourceOptions): SecurityGroup {
        return new SecurityGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:index/securityGroup:SecurityGroup';

    /**
     * Returns true if the given object is an instance of SecurityGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecurityGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecurityGroup.__pulumiType;
    }

    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.SecurityGroupConfigGenerationMetadata | undefined>;
    /**
     * The Configuration types that will be added to this group. `BRIDGED` mode indicates that configurations added to this group will use Tetrate APIs such as `SecuritySetting`. `DIRECT` mode indicates that configurations added to this group will use Istio Security v2beta1 APIs such as `PeerAuthentication`, and `AuthorizationPolicy`. Defaults to `BRIDGED` mode.
     */
    declare public readonly configMode: pulumi.Output<string>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    declare public readonly deletionProtectionEnabled: pulumi.Output<boolean>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Short name of the Group resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Set of namespaces owned exclusively by this group. Use `*&#47;*` to claim all cluster resources under the workspace.
     */
    declare public readonly namespaceSelector: pulumi.Output<outputs.SecurityGroupNamespaceSelector>;
    /**
     * The parent id for the Group resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * List of profiles attached to the security group to be used to propagate default and mandatory configurations down to the children.
     */
    declare public readonly profiles: pulumi.Output<string[]>;
    /**
     * Security domains can be used to group different resources under the same security domain. Although security domain is not resource itself currently, it follows a fqn format `organizations/myorg/securitydomains/mysecuritydomain`, and a child cannot override any ancestor's security domain. Once a security domain is assigned to a _Security group_, all the children resources will belong to that security domain in the same way a _Security setting_ belongs to a _Security group_, a _Security setting_ will also belong to the security domain assigned to the _Security group_. Security domains can also be used to define _Security settings Authorization rules_ in which you can allow or deny request from or to a security domain.
     */
    declare public readonly securityDomain: pulumi.Output<string>;

    /**
     * Create a SecurityGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecurityGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecurityGroupArgs | SecurityGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecurityGroupState | undefined;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["configMode"] = state?.configMode;
            resourceInputs["deletionProtectionEnabled"] = state?.deletionProtectionEnabled;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["name"] = state?.name;
            resourceInputs["namespaceSelector"] = state?.namespaceSelector;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["profiles"] = state?.profiles;
            resourceInputs["securityDomain"] = state?.securityDomain;
        } else {
            const args = argsOrState as SecurityGroupArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.namespaceSelector === undefined && !opts.urn) {
                throw new Error("Missing required property 'namespaceSelector'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["configMode"] = args?.configMode;
            resourceInputs["deletionProtectionEnabled"] = args?.deletionProtectionEnabled;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespaceSelector"] = args?.namespaceSelector;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["profiles"] = args?.profiles;
            resourceInputs["securityDomain"] = args?.securityDomain;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecurityGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecurityGroup resources.
 */
export interface SecurityGroupState {
    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.SecurityGroupConfigGenerationMetadata | undefined>;
    /**
     * The Configuration types that will be added to this group. `BRIDGED` mode indicates that configurations added to this group will use Tetrate APIs such as `SecuritySetting`. `DIRECT` mode indicates that configurations added to this group will use Istio Security v2beta1 APIs such as `PeerAuthentication`, and `AuthorizationPolicy`. Defaults to `BRIDGED` mode.
     */
    configMode?: pulumi.Input<string | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the Group resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Set of namespaces owned exclusively by this group. Use `*&#47;*` to claim all cluster resources under the workspace.
     */
    namespaceSelector?: pulumi.Input<inputs.SecurityGroupNamespaceSelector | undefined>;
    /**
     * The parent id for the Group resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * List of profiles attached to the security group to be used to propagate default and mandatory configurations down to the children.
     */
    profiles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Security domains can be used to group different resources under the same security domain. Although security domain is not resource itself currently, it follows a fqn format `organizations/myorg/securitydomains/mysecuritydomain`, and a child cannot override any ancestor's security domain. Once a security domain is assigned to a _Security group_, all the children resources will belong to that security domain in the same way a _Security setting_ belongs to a _Security group_, a _Security setting_ will also belong to the security domain assigned to the _Security group_. Security domains can also be used to define _Security settings Authorization rules_ in which you can allow or deny request from or to a security domain.
     */
    securityDomain?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SecurityGroup resource.
 */
export interface SecurityGroupArgs {
    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.SecurityGroupConfigGenerationMetadata | undefined>;
    /**
     * The Configuration types that will be added to this group. `BRIDGED` mode indicates that configurations added to this group will use Tetrate APIs such as `SecuritySetting`. `DIRECT` mode indicates that configurations added to this group will use Istio Security v2beta1 APIs such as `PeerAuthentication`, and `AuthorizationPolicy`. Defaults to `BRIDGED` mode.
     */
    configMode?: pulumi.Input<string | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the Group resource.
     */
    name: pulumi.Input<string>;
    /**
     * Set of namespaces owned exclusively by this group. Use `*&#47;*` to claim all cluster resources under the workspace.
     */
    namespaceSelector: pulumi.Input<inputs.SecurityGroupNamespaceSelector>;
    /**
     * The parent id for the Group resource.
     */
    parent: pulumi.Input<string>;
    /**
     * List of profiles attached to the security group to be used to propagate default and mandatory configurations down to the children.
     */
    profiles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Security domains can be used to group different resources under the same security domain. Although security domain is not resource itself currently, it follows a fqn format `organizations/myorg/securitydomains/mysecuritydomain`, and a child cannot override any ancestor's security domain. Once a security domain is assigned to a _Security group_, all the children resources will belong to that security domain in the same way a _Security setting_ belongs to a _Security group_, a _Security setting_ will also belong to the security domain assigned to the _Security group_. Security domains can also be used to define _Security settings Authorization rules_ in which you can allow or deny request from or to a security domain.
     */
    securityDomain?: pulumi.Input<string | undefined>;
}
