// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Team extends pulumi.CustomResource {
    /**
     * Get an existing Team resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TeamState, opts?: pulumi.CustomResourceOptions): Team {
        return new Team(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:index/team:Team';

    /**
     * Returns true if the given object is an instance of Team.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Team {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Team.__pulumiType;
    }

    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * exclude_from_jit_reconcile, when set to true, makes OIDC JIT group reconciliation never add or remove memberships on this team. Use it for admin-curated teams (for example incident-response, break-glass, or administrator teams) that are governed outside the OIDC flow. Defaults to false.
     */
    declare public readonly excludeFromJitReconcile: pulumi.Output<boolean>;
    /**
     * external_members are the team members bound by external group-claim (OIDC JIT) reconciliation, projected from the access graph on read. This field is disjoint from `members`, which remains the manually curated source of truth: a user that is both manually and externally assigned appears only in `members`. Union `members` with `externalMembers` to get the effective roster. This field is read-only -- it is ignored on create and update, is never persisted, and is excluded from `etag`.
     */
    declare public readonly externalMembers: pulumi.Output<string[]>;
    /**
     * List of members under the team. The elements of this list are the FQNs of the team members. Team members can be users, service accounts or other teams.
     */
    declare public readonly members: pulumi.Output<string[]>;
    /**
     * Short name of the Team resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * oidc_groups are the OIDC group-claim values that bind users to this team during just-in-time (JIT) membership reconciliation. Claim values are matched exactly (case-sensitive, no whitespace normalization). This is a flat list; a value from any provider's group claim can match. Has no effect unless OIDC JIT group synchronization is enabled on the management plane.
     */
    declare public readonly oidcGroups: pulumi.Output<string[]>;
    /**
     * The parent id for the Team resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * Where the team comes from. It can be a local team that exists only in TSB (type LOCAL) or it can be a team that has been synchronized from the Identity Provider (for example: type LDAP). Possible values: INVALID, LDAP, LOCAL, AZURE, MANUAL, PINGAM, OIDC_PROVISIONED.
     */
    declare public /*out*/ readonly sourceType: pulumi.Output<string>;

    /**
     * Create a Team resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TeamArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TeamArgs | TeamState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TeamState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["excludeFromJitReconcile"] = state?.excludeFromJitReconcile;
            resourceInputs["externalMembers"] = state?.externalMembers;
            resourceInputs["members"] = state?.members;
            resourceInputs["name"] = state?.name;
            resourceInputs["oidcGroups"] = state?.oidcGroups;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["sourceType"] = state?.sourceType;
        } else {
            const args = argsOrState as TeamArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["excludeFromJitReconcile"] = args?.excludeFromJitReconcile;
            resourceInputs["externalMembers"] = args?.externalMembers;
            resourceInputs["members"] = args?.members;
            resourceInputs["name"] = args?.name;
            resourceInputs["oidcGroups"] = args?.oidcGroups;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["sourceType"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Team.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Team resources.
 */
export interface TeamState {
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * exclude_from_jit_reconcile, when set to true, makes OIDC JIT group reconciliation never add or remove memberships on this team. Use it for admin-curated teams (for example incident-response, break-glass, or administrator teams) that are governed outside the OIDC flow. Defaults to false.
     */
    excludeFromJitReconcile?: pulumi.Input<boolean | undefined>;
    /**
     * external_members are the team members bound by external group-claim (OIDC JIT) reconciliation, projected from the access graph on read. This field is disjoint from `members`, which remains the manually curated source of truth: a user that is both manually and externally assigned appears only in `members`. Union `members` with `externalMembers` to get the effective roster. This field is read-only -- it is ignored on create and update, is never persisted, and is excluded from `etag`.
     */
    externalMembers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * List of members under the team. The elements of this list are the FQNs of the team members. Team members can be users, service accounts or other teams.
     */
    members?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Short name of the Team resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * oidc_groups are the OIDC group-claim values that bind users to this team during just-in-time (JIT) membership reconciliation. Claim values are matched exactly (case-sensitive, no whitespace normalization). This is a flat list; a value from any provider's group claim can match. Has no effect unless OIDC JIT group synchronization is enabled on the management plane.
     */
    oidcGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The parent id for the Team resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * Where the team comes from. It can be a local team that exists only in TSB (type LOCAL) or it can be a team that has been synchronized from the Identity Provider (for example: type LDAP). Possible values: INVALID, LDAP, LOCAL, AZURE, MANUAL, PINGAM, OIDC_PROVISIONED.
     */
    sourceType?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Team resource.
 */
export interface TeamArgs {
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * exclude_from_jit_reconcile, when set to true, makes OIDC JIT group reconciliation never add or remove memberships on this team. Use it for admin-curated teams (for example incident-response, break-glass, or administrator teams) that are governed outside the OIDC flow. Defaults to false.
     */
    excludeFromJitReconcile?: pulumi.Input<boolean | undefined>;
    /**
     * external_members are the team members bound by external group-claim (OIDC JIT) reconciliation, projected from the access graph on read. This field is disjoint from `members`, which remains the manually curated source of truth: a user that is both manually and externally assigned appears only in `members`. Union `members` with `externalMembers` to get the effective roster. This field is read-only -- it is ignored on create and update, is never persisted, and is excluded from `etag`.
     */
    externalMembers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * List of members under the team. The elements of this list are the FQNs of the team members. Team members can be users, service accounts or other teams.
     */
    members?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Short name of the Team resource.
     */
    name: pulumi.Input<string>;
    /**
     * oidc_groups are the OIDC group-claim values that bind users to this team during just-in-time (JIT) membership reconciliation. Claim values are matched exactly (case-sensitive, no whitespace normalization). This is a flat list; a value from any provider's group claim can match. Has no effect unless OIDC JIT group synchronization is enabled on the management plane.
     */
    oidcGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The parent id for the Team resource.
     */
    parent: pulumi.Input<string>;
}
