// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

export class Tenant extends pulumi.CustomResource {
    /**
     * Get an existing Tenant resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TenantState, opts?: pulumi.CustomResourceOptions): Tenant {
        return new Tenant(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:index/tenant:Tenant';

    /**
     * Returns true if the given object is an instance of Tenant.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Tenant {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Tenant.__pulumiType;
    }

    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.TenantConfigGenerationMetadata | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    declare public readonly deletionProtectionEnabled: pulumi.Output<boolean>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Short name of the Tenant resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the Tenant resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * List of profiles attached to the tenant to be used to propagate default and mandatory configurations down to the children.
     */
    declare public readonly profiles: pulumi.Output<string[]>;
    /**
     * Security domains can be used to group different resources under the same security domain. Although security domain is not resource itself currently, it follows a fqn format `organizations/myorg/securitydomains/mysecuritydomain`, and a child cannot override any ancestor's security domain. Once a security domain is assigned to a _Tenant_, all the children resources will belong to that security domain in the same way a _Workspace_ belongs to a _Tenant_, a _Workspace_ will also belong to the security domain assigned to the _Tenant_. Security domains can also be used to define _Security settings Authorization rules_ in which you can allow or deny request from or to a security domain.
     */
    declare public readonly securityDomain: pulumi.Output<string>;

    /**
     * Create a Tenant resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TenantArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TenantArgs | TenantState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TenantState | undefined;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["deletionProtectionEnabled"] = state?.deletionProtectionEnabled;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["profiles"] = state?.profiles;
            resourceInputs["securityDomain"] = state?.securityDomain;
        } else {
            const args = argsOrState as TenantArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["deletionProtectionEnabled"] = args?.deletionProtectionEnabled;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["profiles"] = args?.profiles;
            resourceInputs["securityDomain"] = args?.securityDomain;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Tenant.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Tenant resources.
 */
export interface TenantState {
    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.TenantConfigGenerationMetadata | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the Tenant resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the Tenant resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * List of profiles attached to the tenant to be used to propagate default and mandatory configurations down to the children.
     */
    profiles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Security domains can be used to group different resources under the same security domain. Although security domain is not resource itself currently, it follows a fqn format `organizations/myorg/securitydomains/mysecuritydomain`, and a child cannot override any ancestor's security domain. Once a security domain is assigned to a _Tenant_, all the children resources will belong to that security domain in the same way a _Workspace_ belongs to a _Tenant_, a _Workspace_ will also belong to the security domain assigned to the _Tenant_. Security domains can also be used to define _Security settings Authorization rules_ in which you can allow or deny request from or to a security domain.
     */
    securityDomain?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Tenant resource.
 */
export interface TenantArgs {
    /**
     * Default metadata values that will be propagated to the children Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.TenantConfigGenerationMetadata | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the Tenant resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the Tenant resource.
     */
    parent: pulumi.Input<string>;
    /**
     * List of profiles attached to the tenant to be used to propagate default and mandatory configurations down to the children.
     */
    profiles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Security domains can be used to group different resources under the same security domain. Although security domain is not resource itself currently, it follows a fqn format `organizations/myorg/securitydomains/mysecuritydomain`, and a child cannot override any ancestor's security domain. Once a security domain is assigned to a _Tenant_, all the children resources will belong to that security domain in the same way a _Workspace_ belongs to a _Tenant_, a _Workspace_ will also belong to the security domain assigned to the _Tenant_. Security domains can also be used to define _Security settings Authorization rules_ in which you can allow or deny request from or to a security domain.
     */
    securityDomain?: pulumi.Input<string | undefined>;
}
