// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Email for the user where alerts and other notifications will be sent.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * The first name of the user.
     */
    declare public readonly firstName: pulumi.Output<string>;
    /**
     * The last name of the user, if any.
     */
    declare public readonly lastName: pulumi.Output<string>;
    /**
     * The hash of the OIDC group claims as of this user's most recent just-in-time reconciliation. The reconciler uses it to skip work when the claims are unchanged since the last login. Server-managed; not authored by clients. (Field 9 is assigned to `providerName` in a companion Epic 1 API change.)
     */
    declare public readonly lastReconciledGroupsHash: pulumi.Output<string>;
    /**
     * The username used in the login credentials.
     */
    declare public readonly loginName: pulumi.Output<string>;
    /**
     * Short name of the User resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the User resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * The name of the configured identity provider this user originated from (for example, the OIDC provider that just-in-time provisioned them). Distinguishes users that share a `sourceType` but come from different providers (such as multiple OIDC issuers). Empty for users that are not associated with a named provider.
     */
    declare public readonly providerName: pulumi.Output<string>;
    /**
     * Where the user comes from. It can be a local user that exists only in TSB (type LOCAL) or it can be a user that has been synchronized from the Identity Provider (for example: type LDAP). Possible values: INVALID, LDAP, LOCAL, AZURE, MANUAL, PINGAM, OIDC_PROVISIONED.
     */
    declare public /*out*/ readonly sourceType: pulumi.Output<string>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserState | undefined;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["email"] = state?.email;
            resourceInputs["firstName"] = state?.firstName;
            resourceInputs["lastName"] = state?.lastName;
            resourceInputs["lastReconciledGroupsHash"] = state?.lastReconciledGroupsHash;
            resourceInputs["loginName"] = state?.loginName;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["providerName"] = state?.providerName;
            resourceInputs["sourceType"] = state?.sourceType;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if (args?.loginName === undefined && !opts.urn) {
                throw new Error("Missing required property 'loginName'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["email"] = args?.email;
            resourceInputs["firstName"] = args?.firstName;
            resourceInputs["lastName"] = args?.lastName;
            resourceInputs["lastReconciledGroupsHash"] = args?.lastReconciledGroupsHash;
            resourceInputs["loginName"] = args?.loginName;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["providerName"] = args?.providerName;
            resourceInputs["sourceType"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(User.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Email for the user where alerts and other notifications will be sent.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * The first name of the user.
     */
    firstName?: pulumi.Input<string | undefined>;
    /**
     * The last name of the user, if any.
     */
    lastName?: pulumi.Input<string | undefined>;
    /**
     * The hash of the OIDC group claims as of this user's most recent just-in-time reconciliation. The reconciler uses it to skip work when the claims are unchanged since the last login. Server-managed; not authored by clients. (Field 9 is assigned to `providerName` in a companion Epic 1 API change.)
     */
    lastReconciledGroupsHash?: pulumi.Input<string | undefined>;
    /**
     * The username used in the login credentials.
     */
    loginName?: pulumi.Input<string | undefined>;
    /**
     * Short name of the User resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the User resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * The name of the configured identity provider this user originated from (for example, the OIDC provider that just-in-time provisioned them). Distinguishes users that share a `sourceType` but come from different providers (such as multiple OIDC issuers). Empty for users that are not associated with a named provider.
     */
    providerName?: pulumi.Input<string | undefined>;
    /**
     * Where the user comes from. It can be a local user that exists only in TSB (type LOCAL) or it can be a user that has been synchronized from the Identity Provider (for example: type LDAP). Possible values: INVALID, LDAP, LOCAL, AZURE, MANUAL, PINGAM, OIDC_PROVISIONED.
     */
    sourceType?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Email for the user where alerts and other notifications will be sent.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * The first name of the user.
     */
    firstName?: pulumi.Input<string | undefined>;
    /**
     * The last name of the user, if any.
     */
    lastName?: pulumi.Input<string | undefined>;
    /**
     * The hash of the OIDC group claims as of this user's most recent just-in-time reconciliation. The reconciler uses it to skip work when the claims are unchanged since the last login. Server-managed; not authored by clients. (Field 9 is assigned to `providerName` in a companion Epic 1 API change.)
     */
    lastReconciledGroupsHash?: pulumi.Input<string | undefined>;
    /**
     * The username used in the login credentials.
     */
    loginName: pulumi.Input<string>;
    /**
     * Short name of the User resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the User resource.
     */
    parent: pulumi.Input<string>;
    /**
     * The name of the configured identity provider this user originated from (for example, the OIDC provider that just-in-time provisioned them). Distinguishes users that share a `sourceType` but come from different providers (such as multiple OIDC issuers). Empty for users that are not associated with a named provider.
     */
    providerName?: pulumi.Input<string | undefined>;
}
