// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class WorkspaceSetting extends pulumi.CustomResource {
    /**
     * Get an existing WorkspaceSetting resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WorkspaceSettingState, opts?: pulumi.CustomResourceOptions): WorkspaceSetting {
        return new WorkspaceSetting(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:index/workspaceSetting:WorkspaceSetting';

    /**
     * Returns true if the given object is an instance of WorkspaceSetting.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkspaceSetting {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkspaceSetting.__pulumiType;
    }

    /**
     * Default east west gateway settings specifies workspace-wide east-west gateway configuration. This is used to configure east-west routing (required for fail-over) for the services that are not exposed on the gateways. All the services matching the specified criteria is picked up for exposing on the east-west gateway workload selected by the workload selector. In case, a service matches selectors in multiple items, the one which comes first is picked up.
     */
    declare public readonly defaultEastWestGatewaySettings: pulumi.Output<outputs.WorkspaceSettingDefaultEastWestGatewaySetting[] | undefined>;
    /**
     * Security settings for all proxy workloads in this workspace. This can be overridden at security group's SecuritySetting for specific cases. The override strategy used will be driven by the SecuritySetting propagation strategy. The default propagation strategy is `REPLACE`, in which a lower level SecuritySetting in the configuration hierarchy replaces a higher level SecuritySetting defined in the configuration hierarchy. Proxy workloads without a specific security group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will accept connections from clients using Istio Mutual TLS as well as legacy clients using plaintext (i.e. any traffic not using Istio Mutual TLS authentication), i.e. authentication mode defaults to `OPTIONAL`. 2. No authorization will be performed, i.e., authorization mode defaults to `DISABLED`.
     */
    declare public readonly defaultSecuritySetting: pulumi.Output<outputs.WorkspaceSettingDefaultSecuritySetting | undefined>;
    /**
     * Traffic settings for all proxy workloads in this workspace. Proxy workloads without a specific traffic group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will be able to reach any service in the cluster, i.e. reachability mode defaults to `CLUSTER`. 2. Traffic to unknown destinations will be directly routed from the sidecar to the destination.
     */
    declare public readonly defaultTrafficSetting: pulumi.Output<outputs.WorkspaceSettingDefaultTrafficSetting | undefined>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Failover settings for all proxies connecting to a host exposed in this workspace. Overrides any global settings. Note that this is a server side setting.
     */
    declare public readonly failoverSettings: pulumi.Output<outputs.WorkspaceSettingFailoverSettings | undefined>;
    /**
     * Hosts reachability defines the list of hostnames that this workspace can reach. In multicluster deployments, hostnames are reachable to all namespaces(`*`) by default. However, this may not always be necessary, as clients may only be present in a few namespaces. By configuring this, a list of namespaces can be limited to the namespaces configured in the workspace. A hostname can be reachable from multiple workspaces. If more than one workspace is configured for the same hostname, the hostname is exported to the union of all namespaces configured in each workspace. Workspaces with no hosts reachability configuration are considered to have reachable to all hosts. Workspaces with explicitly empty hostnames are considered to not want to see any hosts. Namespaces that are not part of any workspaces are also considered to have reachable to all hosts.
     */
    declare public readonly hostsReachability: pulumi.Output<outputs.WorkspaceSettingHostsReachability | undefined>;
    /**
     * Short name of the WorkspaceSetting resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the WorkspaceSetting resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * Locality routing settings for all gateways in the workspace. Overrides any global settings. Please use FailoverSettings instead. If FailoverSettings is set, it takes precedence over this field. Explicitly specify the region traffic will land on when endpoints in local region becomes unhealthy. Should be used together with OutlierDetection to detect unhealthy endpoints. Note: if no OutlierDetection specified, this will not take effect.
     */
    declare public readonly regionalFailovers: pulumi.Output<outputs.WorkspaceSettingRegionalFailover[] | undefined>;

    /**
     * Create a WorkspaceSetting resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WorkspaceSettingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WorkspaceSettingArgs | WorkspaceSettingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WorkspaceSettingState | undefined;
            resourceInputs["defaultEastWestGatewaySettings"] = state?.defaultEastWestGatewaySettings;
            resourceInputs["defaultSecuritySetting"] = state?.defaultSecuritySetting;
            resourceInputs["defaultTrafficSetting"] = state?.defaultTrafficSetting;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["failoverSettings"] = state?.failoverSettings;
            resourceInputs["hostsReachability"] = state?.hostsReachability;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["regionalFailovers"] = state?.regionalFailovers;
        } else {
            const args = argsOrState as WorkspaceSettingArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["defaultEastWestGatewaySettings"] = args?.defaultEastWestGatewaySettings;
            resourceInputs["defaultSecuritySetting"] = args?.defaultSecuritySetting;
            resourceInputs["defaultTrafficSetting"] = args?.defaultTrafficSetting;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["failoverSettings"] = args?.failoverSettings;
            resourceInputs["hostsReachability"] = args?.hostsReachability;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["regionalFailovers"] = args?.regionalFailovers;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WorkspaceSetting.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering WorkspaceSetting resources.
 */
export interface WorkspaceSettingState {
    /**
     * Default east west gateway settings specifies workspace-wide east-west gateway configuration. This is used to configure east-west routing (required for fail-over) for the services that are not exposed on the gateways. All the services matching the specified criteria is picked up for exposing on the east-west gateway workload selected by the workload selector. In case, a service matches selectors in multiple items, the one which comes first is picked up.
     */
    defaultEastWestGatewaySettings?: pulumi.Input<pulumi.Input<inputs.WorkspaceSettingDefaultEastWestGatewaySetting>[] | undefined>;
    /**
     * Security settings for all proxy workloads in this workspace. This can be overridden at security group's SecuritySetting for specific cases. The override strategy used will be driven by the SecuritySetting propagation strategy. The default propagation strategy is `REPLACE`, in which a lower level SecuritySetting in the configuration hierarchy replaces a higher level SecuritySetting defined in the configuration hierarchy. Proxy workloads without a specific security group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will accept connections from clients using Istio Mutual TLS as well as legacy clients using plaintext (i.e. any traffic not using Istio Mutual TLS authentication), i.e. authentication mode defaults to `OPTIONAL`. 2. No authorization will be performed, i.e., authorization mode defaults to `DISABLED`.
     */
    defaultSecuritySetting?: pulumi.Input<inputs.WorkspaceSettingDefaultSecuritySetting | undefined>;
    /**
     * Traffic settings for all proxy workloads in this workspace. Proxy workloads without a specific traffic group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will be able to reach any service in the cluster, i.e. reachability mode defaults to `CLUSTER`. 2. Traffic to unknown destinations will be directly routed from the sidecar to the destination.
     */
    defaultTrafficSetting?: pulumi.Input<inputs.WorkspaceSettingDefaultTrafficSetting | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Failover settings for all proxies connecting to a host exposed in this workspace. Overrides any global settings. Note that this is a server side setting.
     */
    failoverSettings?: pulumi.Input<inputs.WorkspaceSettingFailoverSettings | undefined>;
    /**
     * Hosts reachability defines the list of hostnames that this workspace can reach. In multicluster deployments, hostnames are reachable to all namespaces(`*`) by default. However, this may not always be necessary, as clients may only be present in a few namespaces. By configuring this, a list of namespaces can be limited to the namespaces configured in the workspace. A hostname can be reachable from multiple workspaces. If more than one workspace is configured for the same hostname, the hostname is exported to the union of all namespaces configured in each workspace. Workspaces with no hosts reachability configuration are considered to have reachable to all hosts. Workspaces with explicitly empty hostnames are considered to not want to see any hosts. Namespaces that are not part of any workspaces are also considered to have reachable to all hosts.
     */
    hostsReachability?: pulumi.Input<inputs.WorkspaceSettingHostsReachability | undefined>;
    /**
     * Short name of the WorkspaceSetting resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the WorkspaceSetting resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * Locality routing settings for all gateways in the workspace. Overrides any global settings. Please use FailoverSettings instead. If FailoverSettings is set, it takes precedence over this field. Explicitly specify the region traffic will land on when endpoints in local region becomes unhealthy. Should be used together with OutlierDetection to detect unhealthy endpoints. Note: if no OutlierDetection specified, this will not take effect.
     */
    regionalFailovers?: pulumi.Input<pulumi.Input<inputs.WorkspaceSettingRegionalFailover>[] | undefined>;
}

/**
 * The set of arguments for constructing a WorkspaceSetting resource.
 */
export interface WorkspaceSettingArgs {
    /**
     * Default east west gateway settings specifies workspace-wide east-west gateway configuration. This is used to configure east-west routing (required for fail-over) for the services that are not exposed on the gateways. All the services matching the specified criteria is picked up for exposing on the east-west gateway workload selected by the workload selector. In case, a service matches selectors in multiple items, the one which comes first is picked up.
     */
    defaultEastWestGatewaySettings?: pulumi.Input<pulumi.Input<inputs.WorkspaceSettingDefaultEastWestGatewaySetting>[] | undefined>;
    /**
     * Security settings for all proxy workloads in this workspace. This can be overridden at security group's SecuritySetting for specific cases. The override strategy used will be driven by the SecuritySetting propagation strategy. The default propagation strategy is `REPLACE`, in which a lower level SecuritySetting in the configuration hierarchy replaces a higher level SecuritySetting defined in the configuration hierarchy. Proxy workloads without a specific security group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will accept connections from clients using Istio Mutual TLS as well as legacy clients using plaintext (i.e. any traffic not using Istio Mutual TLS authentication), i.e. authentication mode defaults to `OPTIONAL`. 2. No authorization will be performed, i.e., authorization mode defaults to `DISABLED`.
     */
    defaultSecuritySetting?: pulumi.Input<inputs.WorkspaceSettingDefaultSecuritySetting | undefined>;
    /**
     * Traffic settings for all proxy workloads in this workspace. Proxy workloads without a specific traffic group will inherit these settings. If omitted, the following semantics apply: 1. Sidecars will be able to reach any service in the cluster, i.e. reachability mode defaults to `CLUSTER`. 2. Traffic to unknown destinations will be directly routed from the sidecar to the destination.
     */
    defaultTrafficSetting?: pulumi.Input<inputs.WorkspaceSettingDefaultTrafficSetting | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Failover settings for all proxies connecting to a host exposed in this workspace. Overrides any global settings. Note that this is a server side setting.
     */
    failoverSettings?: pulumi.Input<inputs.WorkspaceSettingFailoverSettings | undefined>;
    /**
     * Hosts reachability defines the list of hostnames that this workspace can reach. In multicluster deployments, hostnames are reachable to all namespaces(`*`) by default. However, this may not always be necessary, as clients may only be present in a few namespaces. By configuring this, a list of namespaces can be limited to the namespaces configured in the workspace. A hostname can be reachable from multiple workspaces. If more than one workspace is configured for the same hostname, the hostname is exported to the union of all namespaces configured in each workspace. Workspaces with no hosts reachability configuration are considered to have reachable to all hosts. Workspaces with explicitly empty hostnames are considered to not want to see any hosts. Namespaces that are not part of any workspaces are also considered to have reachable to all hosts.
     */
    hostsReachability?: pulumi.Input<inputs.WorkspaceSettingHostsReachability | undefined>;
    /**
     * Short name of the WorkspaceSetting resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the WorkspaceSetting resource.
     */
    parent: pulumi.Input<string>;
    /**
     * Locality routing settings for all gateways in the workspace. Overrides any global settings. Please use FailoverSettings instead. If FailoverSettings is set, it takes precedence over this field. Explicitly specify the region traffic will land on when endpoints in local region becomes unhealthy. Should be used together with OutlierDetection to detect unhealthy endpoints. Note: if no OutlierDetection specified, this will not take effect.
     */
    regionalFailovers?: pulumi.Input<pulumi.Input<inputs.WorkspaceSettingRegionalFailover>[] | undefined>;
}
