// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class ApplicationApi extends pulumi.CustomResource {
    /**
     * Get an existing ApplicationApi resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApplicationApiState, opts?: pulumi.CustomResourceOptions): ApplicationApi {
        return new ApplicationApi(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:application/applicationApi:ApplicationApi';

    /**
     * Returns true if the given object is an instance of ApplicationApi.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApplicationApi {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApplicationApi.__pulumiType;
    }

    /**
     * The configuration resources that are related to this API object.
     */
    declare public readonly configResources: pulumi.Output<outputs.application.ApplicationApiConfigResource[] | undefined>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * List of endpoints exposed by this API. This field is read-only and generated from the configured OpenAPI spec.
     */
    declare public readonly endpoints: pulumi.Output<outputs.application.ApplicationApiEndpoint[] | undefined>;
    /**
     * List of gateways servers that expose the API. Server hostnames must be unique in the system, and only one API can expose a specific hostname.
     */
    declare public readonly httpServers: pulumi.Output<outputs.application.ApplicationApiHttpServer[] | undefined>;
    /**
     * Short name of the API resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The raw OpenAPI spec for this API.
     */
    declare public readonly openapi: pulumi.Output<string>;
    /**
     * The parent id for the API resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * DEPRECATED: For new created APIs, the exposed servers will be available at httpServers. For APIs created before version 1.7, will still be available in this field. List of ingress gateways servers that expose the API. Server hostnames must be unique in the system, and only one API can expose a specific hostname.
     */
    declare public readonly servers: pulumi.Output<outputs.application.ApplicationApiServer[] | undefined>;
    /**
     * {{% examples %}}
     * Optional selector to specify the gateway workloads (pod labels and Kubernetes namespace) under the application gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace. If the selector is omitted, then the following default workload selector will be applied, based on the name of the Application and the API objects. ``` yaml workloadSelector:   namespace: exampleapp   labels:     app: application-name     api: api-name  ```
     * {{% /examples %}}
     */
    declare public readonly workloadSelector: pulumi.Output<outputs.application.ApplicationApiWorkloadSelector | undefined>;

    /**
     * Create a ApplicationApi resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApplicationApiArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApplicationApiArgs | ApplicationApiState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApplicationApiState | undefined;
            resourceInputs["configResources"] = state?.configResources;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["endpoints"] = state?.endpoints;
            resourceInputs["httpServers"] = state?.httpServers;
            resourceInputs["name"] = state?.name;
            resourceInputs["openapi"] = state?.openapi;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["servers"] = state?.servers;
            resourceInputs["workloadSelector"] = state?.workloadSelector;
        } else {
            const args = argsOrState as ApplicationApiArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.openapi === undefined && !opts.urn) {
                throw new Error("Missing required property 'openapi'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["configResources"] = args?.configResources;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["endpoints"] = args?.endpoints;
            resourceInputs["httpServers"] = args?.httpServers;
            resourceInputs["name"] = args?.name;
            resourceInputs["openapi"] = args?.openapi;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["servers"] = args?.servers;
            resourceInputs["workloadSelector"] = args?.workloadSelector;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApplicationApi.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ApplicationApi resources.
 */
export interface ApplicationApiState {
    /**
     * The configuration resources that are related to this API object.
     */
    configResources?: pulumi.Input<pulumi.Input<inputs.application.ApplicationApiConfigResource>[] | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * List of endpoints exposed by this API. This field is read-only and generated from the configured OpenAPI spec.
     */
    endpoints?: pulumi.Input<pulumi.Input<inputs.application.ApplicationApiEndpoint>[] | undefined>;
    /**
     * List of gateways servers that expose the API. Server hostnames must be unique in the system, and only one API can expose a specific hostname.
     */
    httpServers?: pulumi.Input<pulumi.Input<inputs.application.ApplicationApiHttpServer>[] | undefined>;
    /**
     * Short name of the API resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The raw OpenAPI spec for this API.
     */
    openapi?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the API resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * DEPRECATED: For new created APIs, the exposed servers will be available at httpServers. For APIs created before version 1.7, will still be available in this field. List of ingress gateways servers that expose the API. Server hostnames must be unique in the system, and only one API can expose a specific hostname.
     */
    servers?: pulumi.Input<pulumi.Input<inputs.application.ApplicationApiServer>[] | undefined>;
    /**
     * {{% examples %}}
     * Optional selector to specify the gateway workloads (pod labels and Kubernetes namespace) under the application gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace. If the selector is omitted, then the following default workload selector will be applied, based on the name of the Application and the API objects. ``` yaml workloadSelector:   namespace: exampleapp   labels:     app: application-name     api: api-name  ```
     * {{% /examples %}}
     */
    workloadSelector?: pulumi.Input<inputs.application.ApplicationApiWorkloadSelector | undefined>;
}

/**
 * The set of arguments for constructing a ApplicationApi resource.
 */
export interface ApplicationApiArgs {
    /**
     * The configuration resources that are related to this API object.
     */
    configResources?: pulumi.Input<pulumi.Input<inputs.application.ApplicationApiConfigResource>[] | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * List of endpoints exposed by this API. This field is read-only and generated from the configured OpenAPI spec.
     */
    endpoints?: pulumi.Input<pulumi.Input<inputs.application.ApplicationApiEndpoint>[] | undefined>;
    /**
     * List of gateways servers that expose the API. Server hostnames must be unique in the system, and only one API can expose a specific hostname.
     */
    httpServers?: pulumi.Input<pulumi.Input<inputs.application.ApplicationApiHttpServer>[] | undefined>;
    /**
     * Short name of the API resource.
     */
    name: pulumi.Input<string>;
    /**
     * The raw OpenAPI spec for this API.
     */
    openapi: pulumi.Input<string>;
    /**
     * The parent id for the API resource.
     */
    parent: pulumi.Input<string>;
    /**
     * DEPRECATED: For new created APIs, the exposed servers will be available at httpServers. For APIs created before version 1.7, will still be available in this field. List of ingress gateways servers that expose the API. Server hostnames must be unique in the system, and only one API can expose a specific hostname.
     */
    servers?: pulumi.Input<pulumi.Input<inputs.application.ApplicationApiServer>[] | undefined>;
    /**
     * {{% examples %}}
     * Optional selector to specify the gateway workloads (pod labels and Kubernetes namespace) under the application gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace. If the selector is omitted, then the following default workload selector will be applied, based on the name of the Application and the API objects. ``` yaml workloadSelector:   namespace: exampleapp   labels:     app: application-name     api: api-name  ```
     * {{% /examples %}}
     */
    workloadSelector?: pulumi.Input<inputs.application.ApplicationApiWorkloadSelector | undefined>;
}
