// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { ApplicationApiArgs, ApplicationApiState } from "./applicationApi";
export type ApplicationApi = import("./applicationApi").ApplicationApi;
export const ApplicationApi: typeof import("./applicationApi").ApplicationApi = null as any;
utilities.lazyLoad(exports, ["ApplicationApi"], () => require("./applicationApi"));

export { ApplicationApplicationArgs, ApplicationApplicationState } from "./applicationApplication";
export type ApplicationApplication = import("./applicationApplication").ApplicationApplication;
export const ApplicationApplication: typeof import("./applicationApplication").ApplicationApplication = null as any;
utilities.lazyLoad(exports, ["ApplicationApplication"], () => require("./applicationApplication"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tsb:application/applicationApi:ApplicationApi":
                return new ApplicationApi(name, <any>undefined, { urn })
            case "tsb:application/applicationApplication:ApplicationApplication":
                return new ApplicationApplication(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tsb", "application/applicationApi", _module)
pulumi.runtime.registerResourceModule("tsb", "application/applicationApplication", _module)
