// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class GatewayEgressGateway extends pulumi.CustomResource {
    /**
     * Get an existing GatewayEgressGateway resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GatewayEgressGatewayState, opts?: pulumi.CustomResourceOptions): GatewayEgressGateway {
        return new GatewayEgressGateway(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:gateway/gatewayEgressGateway:GatewayEgressGateway';

    /**
     * Returns true if the given object is an instance of GatewayEgressGateway.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GatewayEgressGateway {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GatewayEgressGateway.__pulumiType;
    }

    /**
     * The description of which service accounts can access which hosts. If the list of authorization rules is empty, this egress gateway will deny all traffic.
     */
    declare public readonly authorizations: pulumi.Output<outputs.gateway.GatewayEgressGatewayAuthorization[] | undefined>;
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.gateway.GatewayEgressGatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Extensions specifies all the WasmExtensions assigned to this EgressGateway with the specific configuration for each extension. This custom configuration will override the one configured globally to the extension. Each extension has a global configuration including enablement and priority that will condition the execution of the assigned extensions.
     */
    declare public readonly extensions: pulumi.Output<outputs.gateway.GatewayEgressGatewayExtension[] | undefined>;
    /**
     * Short name of the EgressGateway resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the EgressGateway resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    declare public readonly workloadSelector: pulumi.Output<outputs.gateway.GatewayEgressGatewayWorkloadSelector>;

    /**
     * Create a GatewayEgressGateway resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GatewayEgressGatewayArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GatewayEgressGatewayArgs | GatewayEgressGatewayState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GatewayEgressGatewayState | undefined;
            resourceInputs["authorizations"] = state?.authorizations;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["extensions"] = state?.extensions;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["workloadSelector"] = state?.workloadSelector;
        } else {
            const args = argsOrState as GatewayEgressGatewayArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            if (args?.workloadSelector === undefined && !opts.urn) {
                throw new Error("Missing required property 'workloadSelector'");
            }
            resourceInputs["authorizations"] = args?.authorizations;
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["extensions"] = args?.extensions;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["workloadSelector"] = args?.workloadSelector;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GatewayEgressGateway.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GatewayEgressGateway resources.
 */
export interface GatewayEgressGatewayState {
    /**
     * The description of which service accounts can access which hosts. If the list of authorization rules is empty, this egress gateway will deny all traffic.
     */
    authorizations?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayEgressGatewayAuthorization>[] | undefined>;
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.gateway.GatewayEgressGatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Extensions specifies all the WasmExtensions assigned to this EgressGateway with the specific configuration for each extension. This custom configuration will override the one configured globally to the extension. Each extension has a global configuration including enablement and priority that will condition the execution of the assigned extensions.
     */
    extensions?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayEgressGatewayExtension>[] | undefined>;
    /**
     * Short name of the EgressGateway resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the EgressGateway resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    workloadSelector?: pulumi.Input<inputs.gateway.GatewayEgressGatewayWorkloadSelector | undefined>;
}

/**
 * The set of arguments for constructing a GatewayEgressGateway resource.
 */
export interface GatewayEgressGatewayArgs {
    /**
     * The description of which service accounts can access which hosts. If the list of authorization rules is empty, this egress gateway will deny all traffic.
     */
    authorizations?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayEgressGatewayAuthorization>[] | undefined>;
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.gateway.GatewayEgressGatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Extensions specifies all the WasmExtensions assigned to this EgressGateway with the specific configuration for each extension. This custom configuration will override the one configured globally to the extension. Each extension has a global configuration including enablement and priority that will condition the execution of the assigned extensions.
     */
    extensions?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayEgressGatewayExtension>[] | undefined>;
    /**
     * Short name of the EgressGateway resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the EgressGateway resource.
     */
    parent: pulumi.Input<string>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    workloadSelector: pulumi.Input<inputs.gateway.GatewayEgressGatewayWorkloadSelector>;
}
