// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class GatewayInstallGateway extends pulumi.CustomResource {
    /**
     * Get an existing GatewayInstallGateway resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GatewayInstallGatewayState, opts?: pulumi.CustomResourceOptions): GatewayInstallGateway {
        return new GatewayInstallGateway(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:gateway/gatewayInstallGateway:GatewayInstallGateway';

    /**
     * Returns true if the given object is an instance of GatewayInstallGateway.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GatewayInstallGateway {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GatewayInstallGateway.__pulumiType;
    }

    /**
     * Number of Envoy worker threads to run. By default it will be set automatically based on the gateway's CPU resource limits. Set to `-1` to use the legacy behavior of all cores on the machine.
     */
    declare public readonly concurrency: pulumi.Output<number>;
    /**
     * Extra metadata (labels and annotations) to set on the generated GatewayDeployment object. Useful for label-gated behaviors such as OpenAPI validation, composer, and gateway upgrade control.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.gateway.GatewayInstallGatewayConfigGenerationMetadata | undefined>;
    /**
     * The amount of time the gateway will wait on shutdown for connections to complete before terminating the gateway. During this drain period, no new connections can be created but existing ones are allowed complete.
     */
    declare public readonly connectionDrainDuration: pulumi.Output<outputs.gateway.GatewayInstallGatewayConnectionDrainDuration | undefined>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Configure Kubernetes specific settings.
     */
    declare public readonly kubeSpec: pulumi.Output<outputs.gateway.GatewayInstallGatewayKubeSpec | undefined>;
    /**
     * Short name of the GatewaySpec resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the GatewaySpec resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * Optional merge overlay for the Istio gateway proxy configuration (proxy.istio.io/config). This merges with the default configuration generated by the operator overriding any fields specified in the overlay.
     */
    declare public readonly proxyConfigOverride: pulumi.Output<string>;
    /**
     * Specifies the istio revision to reconcile with. If specified, TSB control plane operator will reconcile this gateway only if operator's revision matches with it. TSB data plane operator, which would be running only when TSB control plane operator is not configured a revision, will ignore revision field and will reconcile gateway as usual. Internally, this revision will guide to pick matching istio control plane for the gateway deployment https://istio.io/latest/docs/setup/upgrade/canary/
     */
    declare public readonly revision: pulumi.Output<string>;
    /**
     * Cluster where the gateway will be deployed. Required when using TSB MP and TSB GitOps to deploy the gateway. Ignored when using as a pure kubernetes resource.
     */
    declare public readonly targetCluster: pulumi.Output<string>;
    /**
     * Namespace where the gateway will be deployed. Required when using TSB MP and TSB GitOps to deploy the gateway. Ignored when using as a pure kubernetes resource.
     */
    declare public readonly targetNamespace: pulumi.Output<string>;
    /**
     * The pod-level termination grace period, in seconds, for the gateway Deployment. This is the hard limit Kubernetes waits after sending SIGTERM before force-killing the pod. It SHOULD be greater than or equal to `connectionDrainDuration` so that in-flight connections can finish draining before the pod is killed. If unset, it defaults to `connectionDrainDuration + 5s`. https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination
     */
    declare public readonly terminationGracePeriodSeconds: pulumi.Output<number>;
    /**
     * Type defines the type of gateway deployment created as part of this gateway install object. Possible values are UNIFIED, INGRESS, EGRESS and EASTWEST. Possible values: UNIFIED, INGRESS, EGRESS, EASTWEST.
     */
    declare public readonly type: pulumi.Output<enums.installDataplane.GatewaySpecType>;

    /**
     * Create a GatewayInstallGateway resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GatewayInstallGatewayArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GatewayInstallGatewayArgs | GatewayInstallGatewayState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GatewayInstallGatewayState | undefined;
            resourceInputs["concurrency"] = state?.concurrency;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["connectionDrainDuration"] = state?.connectionDrainDuration;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["kubeSpec"] = state?.kubeSpec;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["proxyConfigOverride"] = state?.proxyConfigOverride;
            resourceInputs["revision"] = state?.revision;
            resourceInputs["targetCluster"] = state?.targetCluster;
            resourceInputs["targetNamespace"] = state?.targetNamespace;
            resourceInputs["terminationGracePeriodSeconds"] = state?.terminationGracePeriodSeconds;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as GatewayInstallGatewayArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["concurrency"] = args?.concurrency;
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["connectionDrainDuration"] = args?.connectionDrainDuration;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["kubeSpec"] = args?.kubeSpec;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["proxyConfigOverride"] = args?.proxyConfigOverride;
            resourceInputs["revision"] = args?.revision;
            resourceInputs["targetCluster"] = args?.targetCluster;
            resourceInputs["targetNamespace"] = args?.targetNamespace;
            resourceInputs["terminationGracePeriodSeconds"] = args?.terminationGracePeriodSeconds;
            resourceInputs["type"] = args?.type;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GatewayInstallGateway.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GatewayInstallGateway resources.
 */
export interface GatewayInstallGatewayState {
    /**
     * Number of Envoy worker threads to run. By default it will be set automatically based on the gateway's CPU resource limits. Set to `-1` to use the legacy behavior of all cores on the machine.
     */
    concurrency?: pulumi.Input<number | undefined>;
    /**
     * Extra metadata (labels and annotations) to set on the generated GatewayDeployment object. Useful for label-gated behaviors such as OpenAPI validation, composer, and gateway upgrade control.
     */
    configGenerationMetadata?: pulumi.Input<inputs.gateway.GatewayInstallGatewayConfigGenerationMetadata | undefined>;
    /**
     * The amount of time the gateway will wait on shutdown for connections to complete before terminating the gateway. During this drain period, no new connections can be created but existing ones are allowed complete.
     */
    connectionDrainDuration?: pulumi.Input<inputs.gateway.GatewayInstallGatewayConnectionDrainDuration | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Configure Kubernetes specific settings.
     */
    kubeSpec?: pulumi.Input<inputs.gateway.GatewayInstallGatewayKubeSpec | undefined>;
    /**
     * Short name of the GatewaySpec resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the GatewaySpec resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * Optional merge overlay for the Istio gateway proxy configuration (proxy.istio.io/config). This merges with the default configuration generated by the operator overriding any fields specified in the overlay.
     */
    proxyConfigOverride?: pulumi.Input<string | undefined>;
    /**
     * Specifies the istio revision to reconcile with. If specified, TSB control plane operator will reconcile this gateway only if operator's revision matches with it. TSB data plane operator, which would be running only when TSB control plane operator is not configured a revision, will ignore revision field and will reconcile gateway as usual. Internally, this revision will guide to pick matching istio control plane for the gateway deployment https://istio.io/latest/docs/setup/upgrade/canary/
     */
    revision?: pulumi.Input<string | undefined>;
    /**
     * Cluster where the gateway will be deployed. Required when using TSB MP and TSB GitOps to deploy the gateway. Ignored when using as a pure kubernetes resource.
     */
    targetCluster?: pulumi.Input<string | undefined>;
    /**
     * Namespace where the gateway will be deployed. Required when using TSB MP and TSB GitOps to deploy the gateway. Ignored when using as a pure kubernetes resource.
     */
    targetNamespace?: pulumi.Input<string | undefined>;
    /**
     * The pod-level termination grace period, in seconds, for the gateway Deployment. This is the hard limit Kubernetes waits after sending SIGTERM before force-killing the pod. It SHOULD be greater than or equal to `connectionDrainDuration` so that in-flight connections can finish draining before the pod is killed. If unset, it defaults to `connectionDrainDuration + 5s`. https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination
     */
    terminationGracePeriodSeconds?: pulumi.Input<number | undefined>;
    /**
     * Type defines the type of gateway deployment created as part of this gateway install object. Possible values are UNIFIED, INGRESS, EGRESS and EASTWEST. Possible values: UNIFIED, INGRESS, EGRESS, EASTWEST.
     */
    type?: pulumi.Input<enums.installDataplane.GatewaySpecType | undefined>;
}

/**
 * The set of arguments for constructing a GatewayInstallGateway resource.
 */
export interface GatewayInstallGatewayArgs {
    /**
     * Number of Envoy worker threads to run. By default it will be set automatically based on the gateway's CPU resource limits. Set to `-1` to use the legacy behavior of all cores on the machine.
     */
    concurrency?: pulumi.Input<number | undefined>;
    /**
     * Extra metadata (labels and annotations) to set on the generated GatewayDeployment object. Useful for label-gated behaviors such as OpenAPI validation, composer, and gateway upgrade control.
     */
    configGenerationMetadata?: pulumi.Input<inputs.gateway.GatewayInstallGatewayConfigGenerationMetadata | undefined>;
    /**
     * The amount of time the gateway will wait on shutdown for connections to complete before terminating the gateway. During this drain period, no new connections can be created but existing ones are allowed complete.
     */
    connectionDrainDuration?: pulumi.Input<inputs.gateway.GatewayInstallGatewayConnectionDrainDuration | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Configure Kubernetes specific settings.
     */
    kubeSpec?: pulumi.Input<inputs.gateway.GatewayInstallGatewayKubeSpec | undefined>;
    /**
     * Short name of the GatewaySpec resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the GatewaySpec resource.
     */
    parent: pulumi.Input<string>;
    /**
     * Optional merge overlay for the Istio gateway proxy configuration (proxy.istio.io/config). This merges with the default configuration generated by the operator overriding any fields specified in the overlay.
     */
    proxyConfigOverride?: pulumi.Input<string | undefined>;
    /**
     * Specifies the istio revision to reconcile with. If specified, TSB control plane operator will reconcile this gateway only if operator's revision matches with it. TSB data plane operator, which would be running only when TSB control plane operator is not configured a revision, will ignore revision field and will reconcile gateway as usual. Internally, this revision will guide to pick matching istio control plane for the gateway deployment https://istio.io/latest/docs/setup/upgrade/canary/
     */
    revision?: pulumi.Input<string | undefined>;
    /**
     * Cluster where the gateway will be deployed. Required when using TSB MP and TSB GitOps to deploy the gateway. Ignored when using as a pure kubernetes resource.
     */
    targetCluster?: pulumi.Input<string | undefined>;
    /**
     * Namespace where the gateway will be deployed. Required when using TSB MP and TSB GitOps to deploy the gateway. Ignored when using as a pure kubernetes resource.
     */
    targetNamespace?: pulumi.Input<string | undefined>;
    /**
     * The pod-level termination grace period, in seconds, for the gateway Deployment. This is the hard limit Kubernetes waits after sending SIGTERM before force-killing the pod. It SHOULD be greater than or equal to `connectionDrainDuration` so that in-flight connections can finish draining before the pod is killed. If unset, it defaults to `connectionDrainDuration + 5s`. https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination
     */
    terminationGracePeriodSeconds?: pulumi.Input<number | undefined>;
    /**
     * Type defines the type of gateway deployment created as part of this gateway install object. Possible values are UNIFIED, INGRESS, EGRESS and EASTWEST. Possible values: UNIFIED, INGRESS, EGRESS, EASTWEST.
     */
    type?: pulumi.Input<enums.installDataplane.GatewaySpecType | undefined>;
}
