// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class GatewayInstallGatewayTemplate extends pulumi.CustomResource {
    /**
     * Get an existing GatewayInstallGatewayTemplate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GatewayInstallGatewayTemplateState, opts?: pulumi.CustomResourceOptions): GatewayInstallGatewayTemplate {
        return new GatewayInstallGatewayTemplate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:gateway/gatewayInstallGatewayTemplate:GatewayInstallGatewayTemplate';

    /**
     * Returns true if the given object is an instance of GatewayInstallGatewayTemplate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GatewayInstallGatewayTemplate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GatewayInstallGatewayTemplate.__pulumiType;
    }

    /**
     * Selects all the onboarded clusters on TSB.
     */
    declare public readonly allClustersSelector: pulumi.Output<boolean>;
    /**
     * Selects the gateways targeting the clusters based on cluster specific details (e.g. cluster name or labels).
     */
    declare public readonly clusterSelector: pulumi.Output<outputs.gateway.GatewayInstallGatewayTemplateClusterSelector | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    declare public readonly deletionProtectionEnabled: pulumi.Output<boolean>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Selects the gateways targeting the clusters based on environment details, such as the provider.
     */
    declare public readonly environmentSelector: pulumi.Output<outputs.gateway.GatewayInstallGatewayTemplateEnvironmentSelector | undefined>;
    /**
     * The gateway spec to apply to the created gateway.
     */
    declare public readonly gatewaySpec: pulumi.Output<outputs.gateway.GatewayInstallGatewayTemplateGatewaySpec>;
    /**
     * Matches the workload selector defined by a Gateway configuration. Optional.
     */
    declare public readonly gatewayWorkloadSelector: pulumi.Output<outputs.gateway.GatewayInstallGatewayTemplateGatewayWorkloadSelector | undefined>;
    /**
     * Short name of the InstallGatewayTemplate resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the InstallGatewayTemplate resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * Indicates when a template must be chosen in case of multiple selectors of the same type matching a single gateway configuration. Defaults to 0, the highest priority. When two templates have the same priority, they are sorted alphabetically by their names. Templates with different selector types will be resolved in the following order, regardless of the priority value: 1. environment selectors 2. cluster selectors with no namespace selectors 3. cluster selectors with namespace selector matching labels 4. cluster selectors with namespace selector matching name 5. specific InstallGateway TSB resources
     */
    declare public readonly priority: pulumi.Output<number>;

    /**
     * Create a GatewayInstallGatewayTemplate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GatewayInstallGatewayTemplateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GatewayInstallGatewayTemplateArgs | GatewayInstallGatewayTemplateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GatewayInstallGatewayTemplateState | undefined;
            resourceInputs["allClustersSelector"] = state?.allClustersSelector;
            resourceInputs["clusterSelector"] = state?.clusterSelector;
            resourceInputs["deletionProtectionEnabled"] = state?.deletionProtectionEnabled;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["environmentSelector"] = state?.environmentSelector;
            resourceInputs["gatewaySpec"] = state?.gatewaySpec;
            resourceInputs["gatewayWorkloadSelector"] = state?.gatewayWorkloadSelector;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["priority"] = state?.priority;
        } else {
            const args = argsOrState as GatewayInstallGatewayTemplateArgs | undefined;
            if (args?.gatewaySpec === undefined && !opts.urn) {
                throw new Error("Missing required property 'gatewaySpec'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            resourceInputs["allClustersSelector"] = args?.allClustersSelector;
            resourceInputs["clusterSelector"] = args?.clusterSelector;
            resourceInputs["deletionProtectionEnabled"] = args?.deletionProtectionEnabled;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["environmentSelector"] = args?.environmentSelector;
            resourceInputs["gatewaySpec"] = args?.gatewaySpec;
            resourceInputs["gatewayWorkloadSelector"] = args?.gatewayWorkloadSelector;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["priority"] = args?.priority;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GatewayInstallGatewayTemplate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GatewayInstallGatewayTemplate resources.
 */
export interface GatewayInstallGatewayTemplateState {
    /**
     * Selects all the onboarded clusters on TSB.
     */
    allClustersSelector?: pulumi.Input<boolean | undefined>;
    /**
     * Selects the gateways targeting the clusters based on cluster specific details (e.g. cluster name or labels).
     */
    clusterSelector?: pulumi.Input<inputs.gateway.GatewayInstallGatewayTemplateClusterSelector | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Selects the gateways targeting the clusters based on environment details, such as the provider.
     */
    environmentSelector?: pulumi.Input<inputs.gateway.GatewayInstallGatewayTemplateEnvironmentSelector | undefined>;
    /**
     * The gateway spec to apply to the created gateway.
     */
    gatewaySpec?: pulumi.Input<inputs.gateway.GatewayInstallGatewayTemplateGatewaySpec | undefined>;
    /**
     * Matches the workload selector defined by a Gateway configuration. Optional.
     */
    gatewayWorkloadSelector?: pulumi.Input<inputs.gateway.GatewayInstallGatewayTemplateGatewayWorkloadSelector | undefined>;
    /**
     * Short name of the InstallGatewayTemplate resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the InstallGatewayTemplate resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * Indicates when a template must be chosen in case of multiple selectors of the same type matching a single gateway configuration. Defaults to 0, the highest priority. When two templates have the same priority, they are sorted alphabetically by their names. Templates with different selector types will be resolved in the following order, regardless of the priority value: 1. environment selectors 2. cluster selectors with no namespace selectors 3. cluster selectors with namespace selector matching labels 4. cluster selectors with namespace selector matching name 5. specific InstallGateway TSB resources
     */
    priority?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a GatewayInstallGatewayTemplate resource.
 */
export interface GatewayInstallGatewayTemplateArgs {
    /**
     * Selects all the onboarded clusters on TSB.
     */
    allClustersSelector?: pulumi.Input<boolean | undefined>;
    /**
     * Selects the gateways targeting the clusters based on cluster specific details (e.g. cluster name or labels).
     */
    clusterSelector?: pulumi.Input<inputs.gateway.GatewayInstallGatewayTemplateClusterSelector | undefined>;
    /**
     * When set, prevents the resource from being deleted. In order to delete the resource this property needs to be set to `false` first.
     */
    deletionProtectionEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Selects the gateways targeting the clusters based on environment details, such as the provider.
     */
    environmentSelector?: pulumi.Input<inputs.gateway.GatewayInstallGatewayTemplateEnvironmentSelector | undefined>;
    /**
     * The gateway spec to apply to the created gateway.
     */
    gatewaySpec: pulumi.Input<inputs.gateway.GatewayInstallGatewayTemplateGatewaySpec>;
    /**
     * Matches the workload selector defined by a Gateway configuration. Optional.
     */
    gatewayWorkloadSelector?: pulumi.Input<inputs.gateway.GatewayInstallGatewayTemplateGatewayWorkloadSelector | undefined>;
    /**
     * Short name of the InstallGatewayTemplate resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the InstallGatewayTemplate resource.
     */
    parent: pulumi.Input<string>;
    /**
     * Indicates when a template must be chosen in case of multiple selectors of the same type matching a single gateway configuration. Defaults to 0, the highest priority. When two templates have the same priority, they are sorted alphabetically by their names. Templates with different selector types will be resolved in the following order, regardless of the priority value: 1. environment selectors 2. cluster selectors with no namespace selectors 3. cluster selectors with namespace selector matching labels 4. cluster selectors with namespace selector matching name 5. specific InstallGateway TSB resources
     */
    priority?: pulumi.Input<number | undefined>;
}
