// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class GatewayGateway extends pulumi.CustomResource {
    /**
     * Get an existing GatewayGateway resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GatewayGatewayState, opts?: pulumi.CustomResourceOptions): GatewayGateway {
        return new GatewayGateway(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tsb:gateway/gatewayGateway:GatewayGateway';

    /**
     * Returns true if the given object is an instance of GatewayGateway.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GatewayGateway {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GatewayGateway.__pulumiType;
    }

    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    declare public readonly configGenerationMetadata: pulumi.Output<outputs.gateway.GatewayGatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * User friendly name for the resource.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * External services are onboarded into the mesh via service entry, and these services are exposed on the Gateway for egress access. By default, access is denied for these hosts. Users can configure EgressAuthorizationSettings to specify which service accounts are allowed.
     */
    declare public readonly egressAuthorizations: pulumi.Output<outputs.gateway.GatewayGatewayEgressAuthorization[] | undefined>;
    /**
     * One or more HTTP or HTTPS servers exposed by the gateway. The server exposes configuration for TLS termination, request authentication/authorization, HTTP routing, rate limiting, etc.
     */
    declare public readonly https: pulumi.Output<outputs.gateway.GatewayGatewayHttp[] | undefined>;
    /**
     * Short name of the Gateway resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parent id for the Gateway resource.
     */
    declare public readonly parent: pulumi.Output<string>;
    /**
     * One or more non-HTTP and non-passthrough servers which use TCP based protocols. This server also exposes configuration for terminating TLS.
     */
    declare public readonly tcps: pulumi.Output<outputs.gateway.GatewayGatewayTcp[] | undefined>;
    /**
     * One or more TLS servers exposed by the gateway. The server does not terminate TLS and exposes config for SNI based routing.
     */
    declare public readonly tls: pulumi.Output<outputs.gateway.GatewayGatewayTl[] | undefined>;
    /**
     * WAF settings to be enabled for traffic passing through the HttpServer.
     */
    declare public readonly waf: pulumi.Output<outputs.gateway.GatewayGatewayWaf | undefined>;
    /**
     * WasmPlugins specifies all the WasmExtensionAttachment assigned to this Gateway with the specific configuration for each plugin. This custom configuration will override the one configured globally to the plugin. Each plugin has a global configuration including priority that will condition the execution of the assigned plugins.
     */
    declare public readonly wasmPlugins: pulumi.Output<outputs.gateway.GatewayGatewayWasmPlugin[] | undefined>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    declare public readonly workloadSelector: pulumi.Output<outputs.gateway.GatewayGatewayWorkloadSelector>;

    /**
     * Create a GatewayGateway resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GatewayGatewayArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GatewayGatewayArgs | GatewayGatewayState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GatewayGatewayState | undefined;
            resourceInputs["configGenerationMetadata"] = state?.configGenerationMetadata;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["egressAuthorizations"] = state?.egressAuthorizations;
            resourceInputs["https"] = state?.https;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["tcps"] = state?.tcps;
            resourceInputs["tls"] = state?.tls;
            resourceInputs["waf"] = state?.waf;
            resourceInputs["wasmPlugins"] = state?.wasmPlugins;
            resourceInputs["workloadSelector"] = state?.workloadSelector;
        } else {
            const args = argsOrState as GatewayGatewayArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.parent === undefined && !opts.urn) {
                throw new Error("Missing required property 'parent'");
            }
            if (args?.workloadSelector === undefined && !opts.urn) {
                throw new Error("Missing required property 'workloadSelector'");
            }
            resourceInputs["configGenerationMetadata"] = args?.configGenerationMetadata;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["egressAuthorizations"] = args?.egressAuthorizations;
            resourceInputs["https"] = args?.https;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["tcps"] = args?.tcps;
            resourceInputs["tls"] = args?.tls;
            resourceInputs["waf"] = args?.waf;
            resourceInputs["wasmPlugins"] = args?.wasmPlugins;
            resourceInputs["workloadSelector"] = args?.workloadSelector;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GatewayGateway.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GatewayGateway resources.
 */
export interface GatewayGatewayState {
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.gateway.GatewayGatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * External services are onboarded into the mesh via service entry, and these services are exposed on the Gateway for egress access. By default, access is denied for these hosts. Users can configure EgressAuthorizationSettings to specify which service accounts are allowed.
     */
    egressAuthorizations?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayGatewayEgressAuthorization>[] | undefined>;
    /**
     * One or more HTTP or HTTPS servers exposed by the gateway. The server exposes configuration for TLS termination, request authentication/authorization, HTTP routing, rate limiting, etc.
     */
    https?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayGatewayHttp>[] | undefined>;
    /**
     * Short name of the Gateway resource.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The parent id for the Gateway resource.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * One or more non-HTTP and non-passthrough servers which use TCP based protocols. This server also exposes configuration for terminating TLS.
     */
    tcps?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayGatewayTcp>[] | undefined>;
    /**
     * One or more TLS servers exposed by the gateway. The server does not terminate TLS and exposes config for SNI based routing.
     */
    tls?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayGatewayTl>[] | undefined>;
    /**
     * WAF settings to be enabled for traffic passing through the HttpServer.
     */
    waf?: pulumi.Input<inputs.gateway.GatewayGatewayWaf | undefined>;
    /**
     * WasmPlugins specifies all the WasmExtensionAttachment assigned to this Gateway with the specific configuration for each plugin. This custom configuration will override the one configured globally to the plugin. Each plugin has a global configuration including priority that will condition the execution of the assigned plugins.
     */
    wasmPlugins?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayGatewayWasmPlugin>[] | undefined>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    workloadSelector?: pulumi.Input<inputs.gateway.GatewayGatewayWorkloadSelector | undefined>;
}

/**
 * The set of arguments for constructing a GatewayGateway resource.
 */
export interface GatewayGatewayArgs {
    /**
     * Metadata values that will be add into the Istio generated configurations. When using YAML APIs like `tctl` or `gitops`, put them into the `metadata.labels` or `metadata.annotations` instead. This field is only necessary when using gRPC APIs directly.
     */
    configGenerationMetadata?: pulumi.Input<inputs.gateway.GatewayGatewayConfigGenerationMetadata | undefined>;
    /**
     * A description of the resource.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * User friendly name for the resource.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * External services are onboarded into the mesh via service entry, and these services are exposed on the Gateway for egress access. By default, access is denied for these hosts. Users can configure EgressAuthorizationSettings to specify which service accounts are allowed.
     */
    egressAuthorizations?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayGatewayEgressAuthorization>[] | undefined>;
    /**
     * One or more HTTP or HTTPS servers exposed by the gateway. The server exposes configuration for TLS termination, request authentication/authorization, HTTP routing, rate limiting, etc.
     */
    https?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayGatewayHttp>[] | undefined>;
    /**
     * Short name of the Gateway resource.
     */
    name: pulumi.Input<string>;
    /**
     * The parent id for the Gateway resource.
     */
    parent: pulumi.Input<string>;
    /**
     * One or more non-HTTP and non-passthrough servers which use TCP based protocols. This server also exposes configuration for terminating TLS.
     */
    tcps?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayGatewayTcp>[] | undefined>;
    /**
     * One or more TLS servers exposed by the gateway. The server does not terminate TLS and exposes config for SNI based routing.
     */
    tls?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayGatewayTl>[] | undefined>;
    /**
     * WAF settings to be enabled for traffic passing through the HttpServer.
     */
    waf?: pulumi.Input<inputs.gateway.GatewayGatewayWaf | undefined>;
    /**
     * WasmPlugins specifies all the WasmExtensionAttachment assigned to this Gateway with the specific configuration for each plugin. This custom configuration will override the one configured globally to the plugin. Each plugin has a global configuration including priority that will condition the execution of the assigned plugins.
     */
    wasmPlugins?: pulumi.Input<pulumi.Input<inputs.gateway.GatewayGatewayWasmPlugin>[] | undefined>;
    /**
     * Specify the gateway workloads (pod labels and Kubernetes namespace) under the gateway group that should be configured with this gateway. There can be only one gateway for a workload selector in a namespace.
     */
    workloadSelector: pulumi.Input<inputs.gateway.GatewayGatewayWorkloadSelector>;
}
