// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { GatewayEgressGatewayArgs, GatewayEgressGatewayState } from "./gatewayEgressGateway";
export type GatewayEgressGateway = import("./gatewayEgressGateway").GatewayEgressGateway;
export const GatewayEgressGateway: typeof import("./gatewayEgressGateway").GatewayEgressGateway = null as any;
utilities.lazyLoad(exports, ["GatewayEgressGateway"], () => require("./gatewayEgressGateway"));

export { GatewayGatewayArgs, GatewayGatewayState } from "./gatewayGateway";
export type GatewayGateway = import("./gatewayGateway").GatewayGateway;
export const GatewayGateway: typeof import("./gatewayGateway").GatewayGateway = null as any;
utilities.lazyLoad(exports, ["GatewayGateway"], () => require("./gatewayGateway"));

export { GatewayGroupArgs, GatewayGroupState } from "./gatewayGroup";
export type GatewayGroup = import("./gatewayGroup").GatewayGroup;
export const GatewayGroup: typeof import("./gatewayGroup").GatewayGroup = null as any;
utilities.lazyLoad(exports, ["GatewayGroup"], () => require("./gatewayGroup"));

export { GatewayIngressGatewayArgs, GatewayIngressGatewayState } from "./gatewayIngressGateway";
export type GatewayIngressGateway = import("./gatewayIngressGateway").GatewayIngressGateway;
export const GatewayIngressGateway: typeof import("./gatewayIngressGateway").GatewayIngressGateway = null as any;
utilities.lazyLoad(exports, ["GatewayIngressGateway"], () => require("./gatewayIngressGateway"));

export { GatewayInstallGatewayArgs, GatewayInstallGatewayState } from "./gatewayInstallGateway";
export type GatewayInstallGateway = import("./gatewayInstallGateway").GatewayInstallGateway;
export const GatewayInstallGateway: typeof import("./gatewayInstallGateway").GatewayInstallGateway = null as any;
utilities.lazyLoad(exports, ["GatewayInstallGateway"], () => require("./gatewayInstallGateway"));

export { GatewayInstallGatewayTemplateArgs, GatewayInstallGatewayTemplateState } from "./gatewayInstallGatewayTemplate";
export type GatewayInstallGatewayTemplate = import("./gatewayInstallGatewayTemplate").GatewayInstallGatewayTemplate;
export const GatewayInstallGatewayTemplate: typeof import("./gatewayInstallGatewayTemplate").GatewayInstallGatewayTemplate = null as any;
utilities.lazyLoad(exports, ["GatewayInstallGatewayTemplate"], () => require("./gatewayInstallGatewayTemplate"));

export { GatewaySharedGatewayReferenceGrantArgs, GatewaySharedGatewayReferenceGrantState } from "./gatewaySharedGatewayReferenceGrant";
export type GatewaySharedGatewayReferenceGrant = import("./gatewaySharedGatewayReferenceGrant").GatewaySharedGatewayReferenceGrant;
export const GatewaySharedGatewayReferenceGrant: typeof import("./gatewaySharedGatewayReferenceGrant").GatewaySharedGatewayReferenceGrant = null as any;
utilities.lazyLoad(exports, ["GatewaySharedGatewayReferenceGrant"], () => require("./gatewaySharedGatewayReferenceGrant"));

export { GatewayTier1GatewayArgs, GatewayTier1GatewayState } from "./gatewayTier1Gateway";
export type GatewayTier1Gateway = import("./gatewayTier1Gateway").GatewayTier1Gateway;
export const GatewayTier1Gateway: typeof import("./gatewayTier1Gateway").GatewayTier1Gateway = null as any;
utilities.lazyLoad(exports, ["GatewayTier1Gateway"], () => require("./gatewayTier1Gateway"));

export { IstioGatewayAuthorizationPolicyArgs, IstioGatewayAuthorizationPolicyState } from "./istioGatewayAuthorizationPolicy";
export type IstioGatewayAuthorizationPolicy = import("./istioGatewayAuthorizationPolicy").IstioGatewayAuthorizationPolicy;
export const IstioGatewayAuthorizationPolicy: typeof import("./istioGatewayAuthorizationPolicy").IstioGatewayAuthorizationPolicy = null as any;
utilities.lazyLoad(exports, ["IstioGatewayAuthorizationPolicy"], () => require("./istioGatewayAuthorizationPolicy"));

export { IstioGatewayGatewayArgs, IstioGatewayGatewayState } from "./istioGatewayGateway";
export type IstioGatewayGateway = import("./istioGatewayGateway").IstioGatewayGateway;
export const IstioGatewayGateway: typeof import("./istioGatewayGateway").IstioGatewayGateway = null as any;
utilities.lazyLoad(exports, ["IstioGatewayGateway"], () => require("./istioGatewayGateway"));

export { IstioGatewayRequestAuthenticationArgs, IstioGatewayRequestAuthenticationState } from "./istioGatewayRequestAuthentication";
export type IstioGatewayRequestAuthentication = import("./istioGatewayRequestAuthentication").IstioGatewayRequestAuthentication;
export const IstioGatewayRequestAuthentication: typeof import("./istioGatewayRequestAuthentication").IstioGatewayRequestAuthentication = null as any;
utilities.lazyLoad(exports, ["IstioGatewayRequestAuthentication"], () => require("./istioGatewayRequestAuthentication"));

export { IstioGatewayVirtualServiceArgs, IstioGatewayVirtualServiceState } from "./istioGatewayVirtualService";
export type IstioGatewayVirtualService = import("./istioGatewayVirtualService").IstioGatewayVirtualService;
export const IstioGatewayVirtualService: typeof import("./istioGatewayVirtualService").IstioGatewayVirtualService = null as any;
utilities.lazyLoad(exports, ["IstioGatewayVirtualService"], () => require("./istioGatewayVirtualService"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tsb:gateway/gatewayEgressGateway:GatewayEgressGateway":
                return new GatewayEgressGateway(name, <any>undefined, { urn })
            case "tsb:gateway/gatewayGateway:GatewayGateway":
                return new GatewayGateway(name, <any>undefined, { urn })
            case "tsb:gateway/gatewayGroup:GatewayGroup":
                return new GatewayGroup(name, <any>undefined, { urn })
            case "tsb:gateway/gatewayIngressGateway:GatewayIngressGateway":
                return new GatewayIngressGateway(name, <any>undefined, { urn })
            case "tsb:gateway/gatewayInstallGateway:GatewayInstallGateway":
                return new GatewayInstallGateway(name, <any>undefined, { urn })
            case "tsb:gateway/gatewayInstallGatewayTemplate:GatewayInstallGatewayTemplate":
                return new GatewayInstallGatewayTemplate(name, <any>undefined, { urn })
            case "tsb:gateway/gatewaySharedGatewayReferenceGrant:GatewaySharedGatewayReferenceGrant":
                return new GatewaySharedGatewayReferenceGrant(name, <any>undefined, { urn })
            case "tsb:gateway/gatewayTier1Gateway:GatewayTier1Gateway":
                return new GatewayTier1Gateway(name, <any>undefined, { urn })
            case "tsb:gateway/istioGatewayAuthorizationPolicy:IstioGatewayAuthorizationPolicy":
                return new IstioGatewayAuthorizationPolicy(name, <any>undefined, { urn })
            case "tsb:gateway/istioGatewayGateway:IstioGatewayGateway":
                return new IstioGatewayGateway(name, <any>undefined, { urn })
            case "tsb:gateway/istioGatewayRequestAuthentication:IstioGatewayRequestAuthentication":
                return new IstioGatewayRequestAuthentication(name, <any>undefined, { urn })
            case "tsb:gateway/istioGatewayVirtualService:IstioGatewayVirtualService":
                return new IstioGatewayVirtualService(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tsb", "gateway/gatewayEgressGateway", _module)
pulumi.runtime.registerResourceModule("tsb", "gateway/gatewayGateway", _module)
pulumi.runtime.registerResourceModule("tsb", "gateway/gatewayGroup", _module)
pulumi.runtime.registerResourceModule("tsb", "gateway/gatewayIngressGateway", _module)
pulumi.runtime.registerResourceModule("tsb", "gateway/gatewayInstallGateway", _module)
pulumi.runtime.registerResourceModule("tsb", "gateway/gatewayInstallGatewayTemplate", _module)
pulumi.runtime.registerResourceModule("tsb", "gateway/gatewaySharedGatewayReferenceGrant", _module)
pulumi.runtime.registerResourceModule("tsb", "gateway/gatewayTier1Gateway", _module)
pulumi.runtime.registerResourceModule("tsb", "gateway/istioGatewayAuthorizationPolicy", _module)
pulumi.runtime.registerResourceModule("tsb", "gateway/istioGatewayGateway", _module)
pulumi.runtime.registerResourceModule("tsb", "gateway/istioGatewayRequestAuthentication", _module)
pulumi.runtime.registerResourceModule("tsb", "gateway/istioGatewayVirtualService", _module)
