// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.

// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const GroupSyncMode = {
    Off: "OFF",
    DryRun: "DRY_RUN",
    MembershipOnly: "MEMBERSHIP_ONLY",
} as const;

export type GroupSyncMode = (typeof GroupSyncMode)[keyof typeof GroupSyncMode];
